enum UiLanguage { zh, en, tw, th }

String tr(UiLanguage language, String key) {
  assert(copy.containsKey(key), 'Missing translation: $key');
  return copy[key]?.split('|')[language.index] ?? key;
}

const copy = <String, String>{
  'staffWelcome': '欢迎使用 KING 收银台|Welcome to KING|歡迎使用 KING 收銀台|ยินดีต้อนรับสู่ KING',
  'staffQrHint': '使用 KING APP 扫码登录，或向扫码器出示员工会员码|Scan with KING APP, or scan your staff member code|使用 KING APP 掃碼登入，或向掃碼器出示員工會員碼|สแกนด้วยแอป KING หรือแสดงรหัสสมาชิกพนักงาน',
  'staffPasswordMode': '手机号密码登录|Phone and password|手機號密碼登入|เข้าสู่ระบบด้วยเบอร์โทรและรหัสผ่าน',
  'staffQrMode': '二维码登录|QR login|二維碼登入|เข้าสู่ระบบด้วย QR',
  'staffQrRefresh': '刷新二维码|Refresh QR|重新整理二維碼|รีเฟรช QR',
  'staffQrExpired': '二维码已失效，请刷新|QR expired. Refresh to continue.|二維碼已失效，請重新整理|QR หมดอายุ โปรดรีเฟรช',
  'staffQrFailed': '暂时无法连接，请重试或使用手机号登录|Connection unavailable. Retry or use phone login.|暫時無法連線，請重試或使用手機號登入|เชื่อมต่อไม่ได้ โปรดลองอีกครั้งหรือใช้เบอร์โทร',
  'staffQrDenied': '登录未完成，请确认会员码有效且有本店员工权限|Login failed. Check your member code and staff access.|登入未完成，請確認會員碼有效且有本店員工權限|เข้าสู่ระบบไม่ได้ โปรดตรวจสอบรหัสสมาชิกและสิทธิ์พนักงาน',

  'togetherAdmissionClose': '关闭|Close|關閉|ปิด',
  'togetherAdmission': '活动入场|Event admission|活動入場|เข้างาน',
  'togetherAdmissionHelp': '扫描顾客活动入场码，确认核销后放行。|Scan the guest’s event ticket and admit only after confirmation.|掃描顧客活動入場碼，確認核銷後放行。|สแกนบัตรเข้างานและให้เข้าหลังยืนยันสำเร็จ',
  'togetherAdmissionSuccess':
      '核销成功，可入场|Admission confirmed|核銷成功，可入場|ยืนยันเข้างานสำเร็จ',
  'togetherAdmissionRepeated': '此票已核销，请勿重复放行|Already admitted. Do not admit twice.|此票已核銷，請勿重複放行|บัตรนี้ใช้แล้ว ห้ามให้เข้าซ้ำ',
  'togetherAdmissionFailed': '未能确认核销，请勿放行。请重扫原入场码核对结果。|Admission unconfirmed. Do not admit. Rescan the original code to check.|未能確認核銷，請勿放行。請重掃原入場碼核對結果。|ยังยืนยันไม่ได้ ห้ามให้เข้า โปรดสแกนรหัสเดิมเพื่อตรวจสอบ',

  'checkoutDiscount': '整单打折|Bill discount|整單打折|ส่วนลดทั้งบิล',
  'checkoutWaive': '整单免单|Waive bill|整單免單|ยกเว้นทั้งบิล',
  'checkoutDiscountScope': '仅调整本桌未付款商品，按当前单价计算|Applies to unpaid items at current unit prices|僅調整本桌未付款商品，按當前單價計算|ปรับเฉพาะสินค้าที่ยังไม่ชำระตามราคาต่อหน่วยปัจจุบัน',
  'checkoutManagerScan': '请负责人出示 KING 会员码授权|Scan an authorized manager’s KING member code|請負責人出示 KING 會員碼授權|สแกนรหัสสมาชิก KING ของผู้จัดการที่มีสิทธิ์',
  'checkoutDiscountFailed': '未能确认结果，请查询原操作；未执行的可刷新负责人会员码重扫|Result unconfirmed. Check the original operation before retrying with a fresh manager code.|未能確認結果，請查詢原操作；未執行的可刷新負責人會員碼重掃|ยังยืนยันผลไม่ได้ โปรดตรวจสอบรายการเดิมก่อนสแกนรหัสใหม่',
  'checkoutDiscountQuery': '查询优惠结果|Check discount result|查詢優惠結果|ตรวจสอบผลส่วนลด',

  'checkoutUnpaidTicket': '打印未付款小票|Print unpaid bill|列印未付款小票|พิมพ์ใบแจ้งยอดยังไม่ชำระ',
  'checkoutNotPaymentProof': '未付款 · 非收款凭证|UNPAID · Not proof of payment|未付款 · 非收款憑證|ยังไม่ชำระ · ไม่ใช่หลักฐานการชำระเงิน',

  'provider_pos': 'POS 刷卡|POS card|POS 刷卡|บัตรผ่าน POS',
  'checkoutPosReference': 'POS 凭证号|POS receipt reference|POS 憑證號|เลขอ้างอิง POS',
  'checkoutPosConsent': '请确认独立 POS 已刷卡成功，金额一致。本操作仅记录收款。|Confirm the independent POS payment succeeded for this amount. This records the receipt only.|請確認獨立 POS 已刷卡成功，金額一致。本操作僅記錄收款。|ยืนยันว่าชำระผ่าน POS สำเร็จและยอดตรงกัน การทำรายการนี้บันทึกการรับชำระเท่านั้น',

  'checkoutTotal': '总额|Total|總額|ยอดรวม',
  'checkoutPaid': '已付|Paid|已付|ชำระแล้ว',
  'checkoutDue': '应收|Due|應收|ยอดที่ต้องชำระ',
  'checkoutStart': '开始收款|Start collection|開始收款|เริ่มรับชำระ',
  'checkoutExactCash': '实收等于应收|Exact amount|實收等於應收|รับเงินพอดี',
  'checkoutCouponUnavailable': '打折券：规则待配置|Discount vouchers: rules pending|打折券：規則待配置|คูปองส่วนลด: รอกำหนดเงื่อนไข',

  'reserveTable': '预留桌位|Reserve table|預留桌位|จองโต๊ะ',
  'reserveGuest': '客人称呼|Guest name|客人稱呼|ชื่อลูกค้า',
  'reservePeople': '人数|Guests|人數|จำนวนคน',
  'reserveTime': '到店时间|Arrival time|到店時間|เวลามาถึง',
  'reserveHours': '预留小时数|Hours reserved|預留小時數|จำนวนชั่วโมง',
  'reserveCancel': '取消预留|Cancel reservation|取消預留|ยกเลิกการจอง',
  'reserveSave': '确认预留|Confirm reservation|確認預留|ยืนยันการจอง',
  'reserveConflict': '这个时段已被预订，请换桌或换时间|Time already reserved; choose another table or time|這個時段已被預訂，請換桌或換時間|ช่วงเวลานี้ถูกจองแล้ว โปรดเปลี่ยนโต๊ะหรือเวลา',
  'reserveFailed': '未能确认预留，请核对人数与时间后重试|Could not confirm; check guests and time and retry|未能確認預留，請核對人數與時間後重試|ยืนยันไม่ได้ ตรวจสอบจำนวนคนและเวลาแล้วลองใหม่',
  'reserveRetry':
      '查询/重试原预留|Check / retry reservation|查詢／重試原預留|ตรวจสอบหรือลองการจองเดิม',
  'reserveApp': 'APP组局|APP party|APP組局|กิจกรรมแอป',
  'reserveNone': '该营业日暂无预订|No reservations for this business date|該營業日暫無預訂|ไม่มีการจองสำหรับวันทำการนี้',
  'reserveAppPending': 'APP组局同步尚未在此服务器启用|APP party sync is not enabled on this server|APP組局同步尚未在此伺服器啟用|ยังไม่เปิดซิงค์กิจกรรมแอปบนเซิร์ฟเวอร์นี้',
  'tableTomorrow': '明日|Tomorrow|明日|พรุ่งนี้',
  'tableHistory': '历史订单|Order history|歷史訂單|ประวัติคำสั่งซื้อ',
  'tableHistoryEmpty': '该营业日暂无开台记录|No sessions for this business date|該營業日暫無開檯記錄|ไม่มีรอบสำหรับวันทำการนี้',
  'tableHistoryDay': '按营业日查看，点击场次查看订单|By business date; tap a session for orders|按營業日查看，點擊場次查看訂單|ดูตามวันทำการ แตะรอบเพื่อดูคำสั่งซื้อ',
  'tableReservationsUnavailable': '预订数据尚未接通，暂不能确认该日预订情况|Reservations are not connected; availability cannot be confirmed|預訂資料尚未接通，暫不能確認該日預訂情況|ยังไม่ได้เชื่อมต่อการจอง ไม่สามารถยืนยันสถานะได้',
  'tableReserved': '预订|Reserved|預訂|จองแล้ว',
  'tableClosed': '已结束|Closed|已結束|สิ้นสุดแล้ว',
  'tableMoreHistory': '更多记录|More records|更多記錄|เพิ่มเติม',
  'tableKind_manual': '空降台|Walk-in|空降檯|โต๊ะวอล์กอิน',
  'tableKind_aa': 'AA台|AA|AA檯|โต๊ะแชร์จ่าย',
  'tableKind_minimum_spend': '抵消台|Min. spend|抵消檯|โต๊ะขั้นต่ำ',
  'tableKind_minimum_people': '限人数台|Min. guests|限人數檯|โต๊ะขั้นต่ำคน',
  'tableConsumptionTotal': '消费总额|Total consumption|消費總額|ยอดใช้จ่ายรวม',
  'tableToday': '今日|Today|今日|วันนี้',
  'tableYesterday': '昨日|Yesterday|昨日|เมื่อวาน',
  'tableMinutes': '分|min|分|นาที',
  'tableHours': '小时|h|小時|ชม.',
  'tableDays': '天|d|天|วัน',
  'itemReturnPending':
      '退库取消待确认|Pending item returns|退庫取消待確認|รายการคืนสต็อกรอยืนยัน',
  'itemReturnNotice': '商品实物退回后，取消所选数量并减少未付金额。|Return the physical goods to cancel this quantity and reduce the amount due.|商品實物退回後，取消所選數量並減少未付金額。|รับสินค้าคืนแล้วจึงยกเลิกจำนวนที่เลือกและลดยอดค้างชำระ',
  'itemReturnConfirm': '实物已退回，确认取消|Goods returned — confirm cancellation|實物已退回，確認取消|รับสินค้าคืนแล้ว ยืนยันยกเลิก',
  'itemReturnDueReduction': '减少应付|Reduce amount due|減少應付|ลดยอดค้างชำระ',
  'itemReturnPendingNotice': '结果待核对，请查询原操作，不要重新退库。|Check the original operation; do not return the goods again.|結果待核對，請查詢原操作，不要重新退庫。|โปรดตรวจสอบรายการเดิม อย่าคืนสินค้าอีกครั้ง',
  'itemReturnRetryNotice': '使用原请求再次确认退库取消，不是再次退回商品。|Retry the original cancellation request. Do not physically return the goods again.|使用原請求再次確認退庫取消，不是再次退回商品。|ยืนยันคำขอยกเลิกเดิมอีกครั้ง ไม่ต้องคืนสินค้าอีกครั้ง',
  'billRecall': '召回|Recall|召回|เรียกคืน',
  'billRecallWait':
      '改回未上，等待重上|Recall for redelivery|改回未上，等待重上|เรียกคืนเพื่อเสิร์ฟใหม่',
  'billRecallReturn':
      '退库并取消商品|Return stock and cancel item|退庫並取消商品|คืนสต็อกและยกเลิกสินค้า',
  'billRecallWaitNotice': '保留消费和付款，将所选数量改回未上；不退库、不退款。|Keep the charge and payment; mark the selected quantity as not served. No restock or refund.|保留消費和付款，將所選數量改回未上；不退庫、不退款。|คงรายการและการชำระเงิน เปลี่ยนจำนวนที่เลือกเป็นยังไม่เสิร์ฟ ไม่คืนสต็อกหรือเงิน',
  'billRecallQuantity': '召回数量|Recall quantity|召回數量|จำนวนที่เรียกคืน',
  'billRecallConfirmed': '召回已确认，等待重上|Recall confirmed; awaiting redelivery|召回已確認，等待重上|ยืนยันเรียกคืนแล้ว รอเสิร์ฟใหม่',
  'billSingleRefund': '单独退款|Item refund|單獨退款|คืนเงินเฉพาะรายการ',
  'billReductionRefresh': '减量结果待核对，正在刷新账单，请确认数量后再操作。|Refreshing bill to verify the reduction. Check the quantity before continuing.|減量結果待核對，正在重新整理帳單，請確認數量後再操作。|กำลังโหลดบิลเพื่อตรวจสอบการลดจำนวน โปรดตรวจสอบก่อนทำต่อ',
  'billReductionPaymentBusy': '这笔订单已有收款请求，请先确认收款结果再减数量。|Resolve the payment request before reducing items.|這筆訂單已有收款請求，請先確認收款結果再減數量。|โปรดตรวจสอบผลการชำระเงินก่อนลดจำนวน',
  'billUnitPrice': '单价|Unit price|單價|ราคาต่อหน่วย',
  'billTotal': '总金额|Total|總金額|ยอดรวม',
  'billPaidAmount': '已付|Paid|已付|ชำระแล้ว',
  'billUnpaidAmount': '未付|Unpaid|未付|ยังไม่ชำระ',
  'billNotServed': '未上|Not served|未上|ยังไม่เสิร์ฟ',
  'billServed': '已上|Served|已上|เสิร์ฟแล้ว',
  'billProgressUnknown':
      '出酒进度待确认|Delivery unconfirmed|出酒進度待確認|รอยืนยันการเสิร์ฟ',
  'billNoItems': '暂无此类商品|No matching items|暫無此類商品|ไม่มีรายการในหมวดนี้',
  'billDraft': '待下单|Not submitted|待下單|ยังไม่ส่งรายการ',
  'tableBillSubmitted': '本桌已点|Table orders|本桌已點|รายการที่สั่งแล้ว',
  'tableBillPaid': '已付款|Paid|已付款|ชำระแล้ว',
  'tableBillUnpaid': '未付款|Unpaid|未付款|ยังไม่ชำระ',
  'tableBillRefunded': '已退款|Refunded|已退款|คืนเงินแล้ว',
  'billOrderRefunded':
      '原订单已退|Original order refunded|原訂單已退|ยอดคืนเงินของคำสั่งซื้อเดิม',
  'billNetReceived': '剩余实收|Net received|剩餘實收|ยอดรับสุทธิคงเหลือ',
  'tableBillMore': '更多已点商品|More table orders|更多已點商品|ดูรายการเพิ่ม',
  'tableBillRetry': '账单读取失败，点击重试|Bill unavailable. Retry|帳單讀取失敗，點擊重試|โหลดบิลไม่สำเร็จ ลองใหม่',
  'tableOrderStart': '点单|Order|點單|สั่งอาหาร',
  'paymentStockUnavailable': '商品已售罄，未发起扣款，请修改订单。|Item sold out. No charge was initiated. Please change the order.|商品已售罄，未發起扣款，請修改訂單。|สินค้าหมด ยังไม่ได้เรียกเก็บเงิน โปรดแก้ไขคำสั่งซื้อ',
  'cashStockUnavailable': '商品已售罄，未完成结账；如已收现金，请退还后修改订单。|Item sold out; checkout was not completed. Return any cash received before changing the order.|商品已售罄，未完成結帳；如已收現金，請退還後修改訂單。|สินค้าหมด ยังไม่ได้ปิดบิล หากรับเงินสดแล้ว โปรดคืนเงินก่อนแก้ไขคำสั่งซื้อ',
  'seatingTitle': '扫码入座|Scan to seat|掃碼入座|สแกนเพื่อเข้าที่นั่ง',
  'seatingArrived':
      '已确认该会员本人到店|This member is present|已確認該會員本人到店|ยืนยันว่าสมาชิกมาถึงแล้ว',
  'seatingReservation': '已核对本桌预约与会员归属|Table reservation and member checked|已核對本桌預約與會員歸屬|ตรวจสอบการจองโต๊ะและสมาชิกแล้ว',
  'seatingConfirm': '确认入座|Confirm seating|確認入座|ยืนยันเข้าที่นั่ง',
  'seatingPending':
      '原入座请求待确认|Seating request pending|原入座請求待確認|คำขอเข้าที่นั่งรอยืนยัน',
  'seatingLookup': '查原结果|Check result|查原結果|ตรวจผลเดิม',
  'seatingCancel':
      '取消未执行请求|Cancel unsent request|取消未執行請求|ยกเลิกคำขอที่ยังไม่สำเร็จ',
  'seatingKeep': '保留请求|Keep request|保留請求|เก็บคำขอไว้',
  'seatingCancelNotice': '只取消尚未完成的原入座请求；如果服务器已经确认，将恢复原成功结果，不会让会员离座。|Cancel only if the original seating has not completed. If already confirmed, recover that result without removing the member.|只取消尚未完成的原入座請求；若伺服器已確認，將恢復原成功結果，不會讓會員離座。|ยกเลิกได้เฉพาะคำขอเดิมที่ยังไม่สำเร็จ หากยืนยันแล้วจะแสดงผลเดิมโดยไม่ให้สมาชิกออกจากที่นั่ง',
  'seatingUnknown': '入座结果暂未确认，请查询原请求。|Seating result uncertain. Check the original request.|入座結果暫未確認，請查詢原請求。|ยังยืนยันผลไม่ได้ โปรดตรวจคำขอเดิม',
  'seatingAlreadyAssigned': '该会员已在其他桌台入座，本次未入座。请取消本次未执行请求，返回原桌台继续。|This member is already seated at another table. Cancel this unexecuted request and continue at the original table.|該會員已在其他桌台入座，本次未入座。請取消本次未執行請求，返回原桌台繼續。|สมาชิกนั่งอยู่ที่โต๊ะอื่นแล้ว ยกเลิกคำขอนี้ที่ยังไม่ได้ดำเนินการ แล้วกลับไปที่โต๊ะเดิม',
  'seatingNotObserved': '服务器暂未记录原请求。请继续查询，或明确取消后重新扫码。|No result recorded yet. Check again, or cancel before scanning again.|伺服器暫未記錄原請求。請繼續查詢，或明確取消後重新掃碼。|ยังไม่พบผลบนเซิร์ฟเวอร์ ตรวจอีกครั้งหรือยกเลิกก่อนสแกนใหม่',
  'seatingConfirmed': '服务器已确认原入座结果，正在刷新会员名单。|Seating confirmed. Refreshing the member list.|伺服器已確認原入座結果，正在重新整理會員名單。|ยืนยันผลเข้าที่นั่งแล้ว กำลังโหลดรายชื่อใหม่',
  'seatingCancelled': '原请求已取消，可以重新扫码。|Original request cancelled. You can scan again.|原請求已取消，可以重新掃碼。|ยกเลิกคำขอเดิมแล้ว สแกนใหม่ได้',
  'seatingRecoveryFailed': '无法读取原入座请求，请刷新后再操作。|Could not load pending seating requests. Refresh before proceeding.|無法讀取原入座請求，請重新整理後再操作。|โหลดคำขอเดิมไม่ได้ โปรดรีเฟรชก่อนดำเนินการ',
  'memberIdentityTitle': '扫码识别会员|Scan member identity|掃碼識別會員|สแกนรหัสสมาชิก',
  'memberIdentityHelp': '请顾客打开 KING APP「我的二维码」，将扫码枪对准会员码。|Ask the guest to open My QR code in KING and scan the member code.|請顧客開啟 KING APP「我的二維碼」，將掃碼槍對準會員碼。|ให้ลูกค้าเปิดรหัส QR ของฉันใน KING แล้วสแกนรหัสสมาชิก',
  'memberIdentityInput': '扫描会员身份码|Scan member code|掃描會員身分碼|สแกนรหัสสมาชิก',
  'memberIdentityScan': '识别|Identify|識別|ตรวจสอบ',
  'memberIdentityFailed': '未能确认会员，请检查身份码并让顾客刷新后重扫。|Could not confirm this member. Ask the guest to refresh their identity code and scan again.|未能確認會員，請檢查身分碼並請顧客重新整理後重掃。|ยืนยันสมาชิกไม่ได้ ให้ลูกค้ารีเฟรชรหัสสมาชิกแล้วสแกนอีกครั้ง',
  'memberIdentityRecognized':
      '已确认当前会员身份|Current member identified|已確認目前會員身分|ยืนยันตัวตนสมาชิกแล้ว',
  'memberIdentityNotice': '身份识别不代表已入座或已付款。结果短时有效，更换顾客请重新扫码。|Identity only; this does not seat or charge the guest. This result expires shortly. Scan again for the next guest.|身分識別不代表已入座或已付款。結果短時有效，更換顧客請重新掃碼。|ยืนยันตัวตนเท่านั้น ไม่ใช่การจัดที่นั่งหรือชำระเงิน ผลมีอายุสั้น กรุณาสแกนใหม่เมื่อลูกค้าเปลี่ยน',
  'memberIdentityClear':
      '清除，下一位|Clear for next guest|清除，下一位|ล้างเพื่อลูกค้าคนถัดไป',
  'tablePaymentPending': '有未付订单|Unpaid orders|有未付訂單|มีรายการยังไม่ชำระ',
  'tableTools':
      '业务工具与待处理|Tools & pending tasks|業務工具與待處理|เครื่องมือและงานรอดำเนินการ',
  'memberIntegrationPending': '会员、预约与存取酒正在接入，暂不可操作。|Member, reservation and bottle services are not yet available.|會員、預約與存取酒正在接入，暫不可操作。|บริการสมาชิก การจอง และฝากรับเครื่องดื่มยังไม่พร้อมใช้งาน',
  'staffChooseStore': '选择门店|Choose a store|選擇門店|เลือกร้าน',
  'staffCancelSelection': '取消|Cancel|取消|ยกเลิก',
  'voucherLookupTitle':
      '原核销查询|Original redemption lookup|原核銷查詢|ค้นหาการใช้คูปองเดิม',
  'voucherLookupNotice': '只查当前员工的原请求，不重新核销。未查到或结果不明时不要换号重试；逐券成功不代表订单已结账。|Reads this employee’s original request only; never redeems again. Missing or unknown is not permission to retry with a new ID. Coupon success does not mean order settlement.|只查目前員工原請求，不重新核銷。未查到或結果不明時勿換號重試；逐券成功不代表订单已結帳。|อ่านคำขอเดิมของพนักงานนี้เท่านั้น ไม่ใช้คูปองซ้ำ หากไม่พบหรือไม่ทราบผล อย่าสร้างรหัสใหม่ คูปองสำเร็จไม่ได้หมายถึงปิดบิลแล้ว',
  'voucherLookupRequest': '原请求编号（小写UUID，不是券码）|Original request ID (lowercase UUID, not coupon code)|原請求編號（小寫UUID，非券碼）|รหัสคำขอเดิม (UUID ตัวเล็ก ไม่ใช่รหัสคูปอง)',
  'voucherLookupRead': '查询原回执|Read original receipt|查詢原回執|อ่านผลคำขอเดิม',
  'voucherLookup_not_observed': '未查到本员工原请求，请核对编号，不要重新核销。|Original not found for this employee. Check the ID; do not redeem again.|未查到本員工原請求，請核對編號，勿重新核銷。|ไม่พบคำขอเดิมของพนักงานนี้ ตรวจสอบรหัส อย่าใช้คูปองซ้ำ',
  'voucherLookup_unknown': '原核销结果不明，需要对账；请保留原请求。|Original outcome unknown; reconciliation required. Keep the original ID.|原核銷結果不明，需對帳；請保留原請求。|ยังไม่ทราบผล ต้องตรวจสอบยอด เก็บรหัสเดิมไว้',
  'voucherLookup_recorded': '已记录官方回执，请逐项核对。|Provider receipt recorded. Review each item.|已記錄官方回執，請逐項核對。|บันทึกผลแพลตฟอร์มแล้ว ตรวจสอบแต่ละรายการ',
  'voucherLookupSuccess': '该券核销成功|Coupon redeemed|該券核銷成功|ใช้คูปองนี้สำเร็จ',
  'voucherLookupNotSuccess': '该项未确认成功（渠道结果码）|Item not confirmed successful (provider code)|該項未確認成功（渠道結果碼）|รายการยังไม่ยืนยันสำเร็จ (รหัสผลแพลตฟอร์ม)',
  'voucherReportPrevious': '上一页明细|Previous details|上一頁明細|รายละเอียดหน้าก่อน',
  'voucherReportNext': '下一页明细|Next details|下一頁明細|รายละเอียดหน้าถัดไป',
  'voucherReportUnknown': '待确认|Unconfirmed|待確認|รอยืนยัน',
  'voucherReportReversed':
      '已撤销核销|Redemption reversed|已撤銷核銷|ยกเลิกการใช้คูปองแล้ว',
  'voucherReportRedemptionDay': '核销日期|Redemption date|核銷日期|วันที่ใช้คูปอง',
  'voucherReportExpectedDay':
      '预计到账日|Expected receipt date|預計到帳日|วันที่คาดว่าจะรับเงิน',
  'voucherReportDetailsNotice': '截至结束日的逐券余额，包含期初历史；每页最多50条，翻页重新读取。|Per-voucher balances through the end date, including opening history. Up to 50 per page; each page is read afresh.|截至結束日的逐券餘額，含期初歷史；每頁最多50條，翻頁重新讀取。|ยอดรายคูปองถึงวันสิ้นสุด รวมประวัติก่อนงวด สูงสุด 50 รายการต่อหน้า อ่านข้อมูลใหม่เมื่อเปลี่ยนหน้า',
  'voucherDetail_netReceivableCents':
      '已估值净应收|Assessed net receivable|已估值淨應收|ยอดค้างรับสุทธิที่ประเมินแล้ว',
  'voucherDetail_outstandingCents': '待到账|Outstanding|待到帳|ยอดค้างรับ',
  'voucherDetail_receivedCents':
      '累计实际到账|Total actual receipts|累計實際到帳|ยอดรับเงินจริงสะสม',
  'voucherDetail_returnedCents':
      '累计实际退回|Total actual returns|累計實際退回|ยอดคืนเงินจริงสะสม',
  'voucherDetail_repayableCents':
      '应退平台|Repayable to provider|應退平台|ยอดต้องคืนแพลตฟอร์ม',
  'voucherReportTitle': '团购应收与到账|Voucher receivables and receipts|團購應收與到帳|ยอดค้างรับและรับเงินจริงจากคูปอง',
  'voucherReportNotice': '区间汇总，不是明细页合计。核销不等于现金到账；未估值金额尚未计入应收。日期按服务端账务日记录，非交班报表。|Full-range summary, not page totals. Redemption is not cash received; unvalued vouchers are not included in receivables. Dates use server accounting days, not shifts.|區間彙總，非明細頁合計。核銷不等於現金到帳；未估值金額尚未計入應收。日期按服務端帳務日，非交班報表。|สรุปทั้งช่วง ไม่ใช่ยอดรวมเฉพาะหน้า การใช้คูปองไม่ใช่การรับเงิน ยอดที่ยังไม่ประเมินไม่รวมในยอดค้างรับ ใช้วันบัญชี ไม่ใช่รายงานกะ',
  'voucherReportFailed': '报表未能确认，请刷新；不会显示为零收入。|Report unavailable. Refresh; this is not zero income.|報表未能確認，請刷新；不代表零收入。|ไม่สามารถยืนยันรายงาน โปรดรีเฟรช ไม่ได้หมายถึงรายได้เป็นศูนย์',
  'voucherReport_all': '全部渠道|All providers|全部渠道|ทุกช่องทาง',
  'voucherReport_douyin': '抖音|Douyin|抖音|Douyin',
  'voucherReport_meituan': '美团|Meituan|美團|Meituan',
  'voucherReport_verifiedCount':
      '期间核销数|Redemptions in period|期間核銷數|จำนวนใช้คูปองในช่วง',
  'voucherReport_unvaluedCount':
      '尚未估值数|Unvalued vouchers|尚未估值數|คูปองที่ยังไม่ประเมินมูลค่า',
  'voucherReport_unscheduledCount':
      '到账日期未确定数|Unscheduled receivables|到帳日期未確定數|รายการที่ยังไม่มีกำหนดรับเงิน',
  'voucherReport_unconfirmedDateCount': '核销日期待确认数|Unconfirmed redemption dates|核銷日期待確認數|รายการที่ยังไม่ยืนยันวันใช้คูปอง',
  'voucherReport_assessedGrossCents':
      '期间已估值总额|Assessed gross in period|期間已估值總額|ยอดประเมินรวมในช่วง',
  'voucherReport_feeCents':
      '期间平台费用|Provider fees in period|期間平台費用|ค่าธรรมเนียมในช่วง',
  'voucherReport_adjustmentCents':
      '期间调整额|Adjustments in period|期間調整額|ยอดปรับปรุงในช่วง',
  'voucherReport_assessedNetCents':
      '期间新增净应收|New net receivables|期間新增淨應收|ยอดค้างรับสุทธิเพิ่มใหม่',
  'voucherReport_openingReceivableCents':
      '期初应收|Opening receivables|期初應收|ยอดค้างรับต้นงวด',
  'voucherReport_reversedReceivableCents':
      '期间撤销应收|Reversed receivables|期間撤銷應收|ยอดค้างรับที่ยกเลิก',
  'voucherReport_receivedCents':
      '期间实际到账|Actual receipts in period|期間實際到帳|ยอดรับเงินจริงในช่วง',
  'voucherReport_returnedCents':
      '期间实际退回|Actual returns in period|期間實際退回|ยอดคืนเงินจริงในช่วง',
  'voucherReport_cashNetCents':
      '期间净到账|Net receipts in period|期間淨到帳|ยอดรับเงินสุทธิในช่วง',
  'voucherReport_closingReceivableCents':
      '期末待到账|Closing receivables|期末待到帳|ยอดค้างรับปลายงวด',
  'voucherReport_repayableCents':
      '期末应退平台|Repayable to provider|期末應退平台|ยอดต้องคืนแพลตฟอร์ม',
  'voucherReport_overdueCents':
      '期末逾期未到账|Overdue receivables|期末逾期未到帳|ยอดค้างรับเกินกำหนด',
  'tableCheckoutTitle': '整桌结账|Table checkout|整桌結帳|ชำระเงินทั้งโต๊ะ',
  'tableCheckoutNotice': '仅收取本场次待付订单。平台现金与本店充值余额分开使用；关闭页面不会取消原交易。|Collect only unpaid orders in this session. Platform cash and store balance stay separate. Closing does not cancel a transaction.|僅收取本場次待付訂單。平台現金與本店儲值餘額分開使用；關閉頁面不會取消原交易。|เรียกเก็บเฉพาะรายการค้างชำระรอบนี้ เงินแพลตฟอร์มกับยอดร้านแยกกัน การปิดหน้าไม่ยกเลิกธุรกรรม',
  'tableCheckoutQuote': '读取整桌账单|Read table bill|讀取整桌帳單|อ่านบิลทั้งโต๊ะ',
  'tableCheckoutUnavailable': '本店暂未开通整桌结账|Table checkout is not available at this store yet|本店暫未開通整桌結帳|ร้านนี้ยังไม่เปิดใช้การชำระทั้งโต๊ะ',
  'tableCheckoutConsent': '我已核对桌台、支付账户和整桌金额|I checked the table, payment account and total|我已核對桌台、付款帳戶和整桌金額|ฉันตรวจสอบโต๊ะ บัญชี และยอดรวมแล้ว',
  'tableCheckoutPrepare': '确认账单（尚不收款）|Confirm bill (no collection yet)|確認帳單（尚不收款）|ยืนยันบิล (ยังไม่เรียกเก็บ)',
  'tableCheckoutQuery': '查询原结账单|Find original checkout|查詢原結帳單|ค้นหารายการเดิม',
  'tableCheckoutRetryPrepare': '重试原准备请求（不换编号、不收款）|Retry original preparation (same ID, no collection)|重試原準備請求（不換編號、不收款）|ลองเตรียมรายการเดิมอีกครั้ง (รหัสเดิม ยังไม่เก็บเงิน)',
  'tableCheckoutRecover': '恢复原交易结果（不重新收款）|Recover original result (no new collection)|恢復原交易結果（不重新收款）|ตรวจสอบผลรายการเดิม (ไม่เก็บเงินใหม่)',
  'tableCheckoutCode': '顾客付款码／会员专用动态付款码|Customer payer code / dedicated member payment code|顧客付款碼／會員專用動態付款碼|รหัสชำระเงินลูกค้า / รหัสชำระเงินสมาชิก',
  'tableCheckoutCollectConsent': '已核对金额；现金方式表示已实际收到现金|Amount checked; cash means money was physically received|已核對金額；現金方式表示已實際收到現金|ตรวจสอบยอดแล้ว กรณีเงินสดหมายถึงได้รับเงินจริงแล้ว',
  'tableCheckoutCollect': '确认收款|Confirm collection|確認收款|ยืนยันรับชำระ',
  'tableCheckoutReview': '未确认完成。请查询原单，不要换号或重复收款。|Completion unconfirmed. Query the original; do not create a new ID or collect again.|未確認完成。請查詢原單，不要換號或重複收款。|ยังไม่ยืนยันว่าเสร็จ โปรดตรวจสอบรายการเดิม อย่าสร้างรหัสใหม่หรือเก็บซ้ำ',
  'tableCheckoutMissing': '尚未查到原单；可人工重试原准备请求，不会自动收款。|Original not found. You may retry its preparation; no automatic collection.|尚未查到原單；可人工重試原準備請求，不會自動收款。|ยังไม่พบรายการเดิม ลองเตรียมรายการเดิมได้ ไม่มีการเก็บเงินอัตโนมัติ',
  'tableCheckout_not_sent':
      '尚未发起收款|Collection not sent|尚未發起收款|ยังไม่ส่งคำขอเก็บเงิน',
  'tableCheckout_pending': '收款处理中，请查询原单|Collection pending; query original|收款處理中，請查詢原單|กำลังรับชำระ โปรดตรวจสอบรายการเดิม',
  'tableCheckout_unknown': '结果不明，请查询原单|Unknown result; query original|結果不明，請查詢原單|ยังไม่ทราบผล โปรดตรวจสอบรายการเดิม',
  'tableCheckout_review_required': '原交易需要核对，请勿重收|Original transaction needs review; do not recollect|原交易需要核對，請勿重收|ต้องตรวจสอบรายการเดิม อย่าเก็บเงินซ้ำ',
  'tableCheckout_settlement_pending': '已收款，业务入账待完成；请恢复原单|Collected; settlement pending. Recover original.|已收款，業務入帳待完成；請恢復原單|รับเงินแล้ว รอบันทึกรายการ โปรดกู้คืนรายการเดิม',
  'receiptReprint': '补打小票|Receipt copy|補印小票|สำเนาใบเสร็จ',
  'checkoutSuccess': '收款成功|Payment successful|收款成功|ชำระเงินสำเร็จ',
  'checkoutDone': '完成，返回桌台|Done|完成，返回桌台|เสร็จสิ้น',
  'checkoutPrinting': '正在打印小票…|Printing receipt…|正在列印小票…|กำลังพิมพ์ใบเสร็จ…',
  'checkoutPrintSent': '小票已发送至打印机|Receipt sent to printer|小票已傳送至印表機|ส่งใบเสร็จไปยังเครื่องพิมพ์แล้ว',
  'checkoutPrintFailed': '已收款，小票打印未确认，请检查打印机|Paid. Receipt output unconfirmed; check printer.|已收款，小票列印未確認，請檢查印表機|ชำระแล้ว โปรดตรวจสอบเครื่องพิมพ์',
  'checkoutPrintUnavailable': '已收款，请连接小票机并在设置中允许 USB 访问|Paid. Connect printer and allow USB access in settings.|已收款，請連接小票機並在設定中允許 USB 存取|ชำระแล้ว โปรดเชื่อมต่อเครื่องพิมพ์และอนุญาต USB',
  'tableCheckout_settled': '原整桌结算已完成|Original table checkout settled|原整桌結算已完成|ชำระและบันทึกรายการทั้งโต๊ะเสร็จแล้ว',
  'tableCheckout_closed_unpaid': '本次收款已关闭，未付款。消费账单保留，可重新结账|Payment attempt closed unpaid. The bill remains; start a new checkout|本次收款已關閉，未付款。消費帳單保留，可重新結帳|ปิดรายการชำระโดยยังไม่ได้ชำระ บิลยังคงอยู่ เริ่มชำระใหม่ได้',
  'tableReceiptTitle': '整桌结账小票|Table checkout receipt|整桌結帳小票|ใบเสร็จรวมโต๊ะ',
  'tableReceiptAllocation':
      '本单分摊金额|Allocated order amount|本單分攤金額|ยอดจัดสรรของคำสั่งซื้อนี้',
  'tableReceiptOrders': '分摊订单数|Allocated orders|分攤訂單數|จำนวนคำสั่งซื้อที่จัดสรร',
  'tableReceiptSettledAt':
      '结算完成时间|Settlement completed|結算完成時間|เวลาที่เสร็จสิ้นการชำระบัญชี',
  'tableReceiptNotice': '整桌只收款一次，下列订单为金额分摊。此页未发送打印，不是税务发票。|One collection for the table; orders below are allocations. This view sends no print data and is not a tax invoice.|整桌只收款一次，下列訂單為金額分攤。此頁未傳送列印，不是稅務發票。|รับชำระรวมโต๊ะครั้งเดียว รายการด้านล่างคือยอดจัดสรร หน้านี้ไม่ส่งข้อมูลพิมพ์และไม่ใช่ใบกำกับภาษี',
  'rechargeCollectTitle':
      '本店充值收款|Store top-up collection|本店儲值收款|รับชำระเติมเงินร้าน',
  'rechargeOriginalRef': '扫描或输入原充值单编号|Scan or enter original top-up ID|掃描或輸入原儲值單編號|สแกนหรือกรอกรหัสรายการเติมเดิม',
  'rechargeReadOriginal':
      '读取后台原单|Load original server order|讀取後台原單|โหลดรายการเดิมจากเซิร์ฟเวอร์',
  'rechargeMemberRef':
      '原单会员引用|Original member reference|原單會員引用|รหัสอ้างอิงสมาชิกเดิม',
  'rechargeGiftExpiry':
      '赠送期限（UTC）|Gift expiry (UTC)|贈送期限（UTC）|วันหมดอายุโบนัส (UTC)',
  'rechargeNoExpiry': '原活动无到期日|No expiry in original offer|原活動無到期日|ข้อเสนอเดิมไม่กำหนดวันหมดอายุ',
  'recharge_principal_first': '先扣本金，再按规则使用赠送|Principal first, then eligible gifts|先扣本金，再按規則使用贈送|หักเงินต้นก่อน แล้วใช้โบนัสตามเงื่อนไข',
  'recharge_gift_first': '先按规则扣赠送，再扣本金|Eligible gifts first, then principal|先按規則扣贈送，再扣本金|ใช้โบนัสตามเงื่อนไขก่อน แล้วหักเงินต้น',
  'rechargeGiftCap': '赠送抵扣比例上限|Maximum gift deduction ratio|贈送抵扣比例上限|สัดส่วนสูงสุดที่ใช้โบนัสหักได้',
  'rechargeProducts': '赠送适用商品编号|Gift-eligible product references|贈送適用商品編號|รหัสสินค้าที่ใช้โบนัสได้',
  'rechargeAllProducts': '全部商品（仍受其他规则限制）|All products, subject to other rules|全部商品（仍受其他規則限制）|สินค้าทั้งหมด ภายใต้เงื่อนไขอื่น',
  'rechargeNoProducts': '无适用商品|No eligible products|無適用商品|ไม่มีสินค้าที่ใช้ได้',
  'rechargeLocatorNotice': '充值编号仅定位原单，不是付款授权。请与会员核对后台显示的归属、金额及赠送规则。|The top-up ID locates an order; it does not authorize payment. Verify the server-provided member, amounts and gift terms with the member.|儲值編號僅定位原單，不是付款授權。請與會員核對後台顯示的歸屬、金額及贈送規則。|รหัสเติมใช้ค้นหารายการ ไม่ใช่การอนุญาตชำระ โปรดยืนยันสมาชิก ยอด และเงื่อนไขโบนัสจากเซิร์ฟเวอร์',
  'rechargeUseRecovery': '已有处理记录，请到待处理充值查询原单；勿重新收款|An attempt exists. Query the original in pending top-ups; do not charge again|已有處理記錄，請至待處理儲值查詢原單；勿重新收款|มีรายการดำเนินการแล้ว ตรวจสอบรายการเดิมในรายการค้าง อย่าเรียกเก็บซ้ำ',
  'rechargeResumeTitle': '继续未发送的原充值|Continue unsent top-up|繼續未發送的原儲值|ดำเนินรายการเติมเดิมที่ยังไม่ส่ง',
  'rechargeResumeConsent': '已与会员核对原充值单、收款渠道和本金金额|I verified the original top-up, payment channel and principal with the member|已與會員核對原儲值單、收款渠道和本金金額|ตรวจสอบรายการเดิม ช่องทาง และเงินต้นกับสมาชิกแล้ว',
  'rechargeResumeNotice': '提交前会再查原单，仅明确未发送才收款。赠送额不计入实付。关闭页面不能撤销已发出的付款。|The original is queried again before payment; only an unsent request may be sent. Gifts are not charged. Closing cannot cancel a sent payment.|提交前會再查原單，僅明確未發送才收款。贈送額不計入實付。關閉頁面不能撤銷已發出的付款。|ตรวจสอบรายการเดิมอีกครั้งก่อนชำระ ส่งได้เฉพาะที่ยังไม่ส่ง ไม่เรียกเก็บโบนัส การปิดหน้าไม่ยกเลิกการชำระที่ส่งแล้ว',
  'rechargeResumeSubmit': '确认后扫码收取本金|Confirm and collect principal|確認後掃碼收取本金|ยืนยันและเรียกเก็บเงินต้น',
  'rechargeClose':
      '关闭并保留原单|Close; keep original request|關閉並保留原單|ปิดและเก็บรายการเดิม',
  'rechargeRecoveryTitle':
      '待处理本店充值|Pending store top-ups|待處理本店儲值|การเติมเงินร้านที่ค้าง',
  'rechargeRecoveryNotice': '仅显示本设备当前员工的原充值请求；查询可能完成已付款的到账，不会重新扣款。本金与赠送分别记账。|Original requests for this employee on this device. Query may finish crediting an existing payment but never charges again. Principal and gifts stay separate.|僅顯示本裝置目前員工的原儲值請求；查詢可能完成已付款的入帳，不會重新扣款。本金與贈送分別記帳。|คำขอเดิมของพนักงานบนอุปกรณ์นี้ การตรวจสอบอาจเพิ่มยอดที่ชำระแล้วแต่ไม่เรียกเก็บซ้ำ เงินต้นและโบนัสแยกกัน',
  'rechargeReload':
      '重新读取待处理记录|Reload pending records|重新讀取待處理記錄|โหลดรายการค้างใหม่',
  'rechargeQuery': '查询原充值|Query original top-up|查詢原儲值|ตรวจสอบรายการเติมเดิม',
  'rechargeUnavailable': '暂不可用，请保留原单并重新查询|Unavailable; keep the original request and query again|暫不可用，請保留原單並重新查詢|ไม่พร้อมใช้งาน เก็บรายการเดิมและตรวจสอบอีกครั้ง',
  'rechargeRecoveryEmpty': '本设备当前员工暂无待处理充值；不代表其他设备没有记录|No pending top-ups for this employee on this device; other devices may have records|本裝置目前員工暫無待處理儲值；不代表其他裝置沒有記錄|ไม่มีรายการค้างของพนักงานบนเครื่องนี้ เครื่องอื่นอาจมีรายการ',
  'rechargePrincipal': '充值本金|Top-up principal|儲值本金|เงินต้นที่เติม',
  'rechargeGift': '本店赠送金额|Store gift amount|本店贈送金額|ยอดโบนัสของร้าน',
  'rechargeWechat': '微信|WeChat Pay|微信|WeChat Pay',
  'rechargeAlipay': '支付宝|Alipay|支付寶|Alipay',
  'rechargeState_not_sent': '尚未发送付款，请核对后继续原单|Payment not sent; review before continuing the original request|尚未發送付款，請核對後繼續原單|ยังไม่ส่งการชำระเงิน ตรวจสอบก่อนดำเนินรายการเดิม',
  'rechargeState_pending': '付款待确认，勿重复扣款|Payment pending; do not charge again|付款待確認，勿重複扣款|รอยืนยันการชำระเงิน อย่าเรียกเก็บซ้ำ',
  'rechargeState_unknown': '付款结果不明，请查原单|Payment uncertain; query the original request|付款結果不明，請查原單|ผลชำระเงินไม่แน่นอน ตรวจสอบรายการเดิม',
  'rechargeState_review_required': '需要核对渠道结果，不自动退款或重扣|Provider result needs review; no automatic refund or recharge|需要核對渠道結果，不自動退款或重扣|ต้องตรวจสอบผลช่องทาง ไม่คืนเงินหรือเรียกเก็บซ้ำอัตโนมัติ',
  'rechargeState_credit_pending': '付款已确认，余额待到账|Payment confirmed; balance credit pending|付款已確認，餘額待入帳|ยืนยันชำระแล้ว รอเพิ่มยอดเงิน',
  'rechargeState_credited':
      '本店余额已到账|Store balance credited|本店餘額已入帳|เพิ่มยอดร้านแล้ว',
  'refundRecoveryTitle':
      '未决余额退款|Pending balance refunds|未決餘額退款|การคืนยอดเงินที่ค้าง',
  'refundRecoveryNotice': '仅显示当前员工在本设备、当前门店的原退款请求，与是否清台无关；先查询原结果，不新增退款。|Original refund requests for this employee, device and store, independent of table clearance. Query original results; do not create another refund.|僅顯示目前員工在本裝置、目前門店的原退款請求，與是否清台無關；先查詢原結果，不新增退款。|คำขอคืนเดิมของพนักงาน อุปกรณ์ และร้านนี้ ไม่ขึ้นกับการเคลียร์โต๊ะ ตรวจสอบผลเดิม อย่าสร้างรายการคืนใหม่',
  'refundRecoveryEmpty': '没有本机当前员工的未决退款；不代表其他设备没有退款|No pending refunds for this employee on this device; other devices may have requests|沒有本機目前員工的未決退款；不代表其他裝置沒有退款|ไม่มีคำขอคืนค้างของพนักงานบนเครื่องนี้ แต่อุปกรณ์อื่นอาจมีคำขอ',
  'refundTitle':
      '余额原路退款／查询|Balance refund / query|餘額原路退款／查詢|คืนยอดเงิน / ตรวจสอบ',
  'refundNotice': '仅支持原余额全额退款。本金与赠送按原账户、原批次恢复，赠送有效期不延长；退款不代表全部实物退回。|Full original balance refund only. Principal and gifts return to original accounts and lots without extending gift expiry. Refund does not mean all goods were returned.|僅支援原餘額全額退款。本金與贈送按原帳戶、原批次恢復，贈送期限不延長；退款不代表全部實物退回。|คืนยอดเดิมเต็มจำนวนเท่านั้น เงินต้นและของแถมคืนบัญชีและล็อตเดิม ไม่ต่ออายุของแถม การคืนเงินไม่ได้หมายถึงคืนสินค้าทั้งหมด',
  'refundReason': '退款原因|Refund reason|退款原因|เหตุผลคืนเงิน',
  'refundDispositionReason':
      '本批次处置说明|Lot disposition reason|本批次處置說明|เหตุผลการจัดการล็อตนี้',
  'refundIssued': '原出库数量|Originally issued|原出庫數量|จำนวนที่จ่ายออกเดิม',
  'refundReturnQuantity': '实际退回数量（未退回填 0）|Actual returned quantity (0 if none)|實際退回數量（未退回填 0）|จำนวนที่คืนจริง (0 หากไม่คืน)',
  'refundPhysical': '已核对收到实物，可退回原库存批次|Physical goods received and eligible for return to original stock lot|已核對收到實物，可退回原庫存批次|ตรวจรับสินค้าจริงแล้วและคืนเข้าล็อตเดิมได้',
  'refundConsent': '我已核对原账户、全额退款及每批实物处置|I verified the original account, full refund and every lot disposition|我已核對原帳戶、全額退款及每批實物處置|ฉันตรวจสอบบัญชีเดิม ยอดคืนเต็มจำนวน และการจัดการทุกล็อตแล้ว',
  'refundSubmit':
      '确认原路退款|Confirm original-account refund|確認原路退款|ยืนยันคืนบัญชีเดิม',
  'refundQuery':
      '只查询原退款|Query original refund only|只查詢原退款|ตรวจสอบคำขอคืนเดิมเท่านั้น',
  'refundRetry': '核对后继续原退款请求|Continue the original refund after review|核對後繼續原退款請求|ดำเนินคำขอคืนเดิมหลังตรวจสอบ',
  'refundReload': '重新读取原订单／未决退款|Reload order / pending refund|重新讀取原訂單／未決退款|โหลดคำสั่งซื้อ / คำขอคืนที่ค้างใหม่',
  'refundDone': '服务端已核验原退款完成|Original refund verified by server|服務端已核驗原退款完成|เซิร์ฟเวอร์ตรวจสอบการคืนเดิมสำเร็จแล้ว',
  'refundUnavailable': '暂不能读取退款信息，请核对权限、订单或连接|Refund details unavailable; check permission, order or connection|暫不能讀取退款資訊，請核對權限、訂單或連線|อ่านข้อมูลคืนไม่ได้ ตรวจสอบสิทธิ์ คำสั่งซื้อ หรือการเชื่อมต่อ',
  'refundDecisionsRequired': '请填写原因和每批退回数量；退回实物需勾选核对|Enter reasons and each returned quantity; confirm physical returns|請填寫原因和每批退回數量；退回實物需勾選核對|กรอกเหตุผลและจำนวนคืนทุกล็อต พร้อมยืนยันรับสินค้าจริง',
  'refundUnknown': '结果未确认，请查询原退款，不要新建请求|Result unconfirmed; query the original refund, do not create another|結果未確認，請查詢原退款，不要新建請求|ผลยังไม่ยืนยัน ตรวจสอบคำขอคืนเดิม อย่าสร้างใหม่',
  'refundNotObserved': '未观察到原退款，核对后可继续同一请求|Original refund not observed; review before continuing the same request|未觀察到原退款，核對後可繼續同一請求|ยังไม่พบการคืนเดิม ตรวจสอบก่อนดำเนินคำขอเดิมต่อ',
  'provider_member_balance': '会员余额|Member balance|會員餘額|ยอดคงเหลือสมาชิก',
  'balance_store_balance':
      '本店充值余额|This store balance|本店儲值餘額|ยอดเติมเงินของร้านนี้',
  'balance_platform_cash':
      '平台现金余额|Platform cash balance|平台現金餘額|ยอดเงินสดของแพลตฟอร์ม',
  'balance_account_notice': '请选择与会员付款码一致的账户，不混扣、不自动补足。|Choose the account authorized by the member code. No mixing or automatic top-up.|請選擇與會員付款碼一致的帳戶，不混扣、不自動補足。|เลือกบัญชีที่ตรงกับรหัสชำระเงินของสมาชิก ไม่หักรวมบัญชีหรือเติมส่วนขาดอัตโนมัติ',
  'provider_recovery': '渠道收款恢复|Payment recovery|渠道收款恢復|กู้คืนรายการชำระเงิน',
  'provider_recovery_notice': '仅显示当前员工在本设备的原请求；金额不是付款凭证，请先查原单。|Original requests for this employee and device only. Amounts are not payment evidence; query first.|僅顯示目前員工在本裝置的原請求；金額不是付款憑證，請先查原單。|แสดงคำขอเดิมของพนักงานและอุปกรณ์นี้เท่านั้น ยอดเงินไม่ใช่หลักฐานชำระเงิน โปรดตรวจสอบก่อน',
  'provider_empty': '没有待恢复的渠道收款请求|No pending payment requests|沒有待恢復的渠道收款請求|ไม่มีคำขอชำระเงินที่รอกู้คืน',
  'provider_retry':
      '确认继续原请求|Continue original request|確認繼續原請求|ดำเนินคำขอเดิมต่อ',
  'provider_not_observed': '未找到原请求，核对后可继续原请求|Original request not found; review before continuing it|未找到原請求，核對後可繼續原請求|ไม่พบคำขอเดิม ตรวจสอบก่อนดำเนินการต่อ',
  'provider_title': '渠道收款 · 请核对订单金额|Payment · verify order amount|渠道收款 · 請核對訂單金額|รับชำระเงิน · ตรวจสอบยอดคำสั่งซื้อ',
  'provider_wechat': '微信|WeChat Pay|微信|WeChat Pay',
  'provider_alipay': '支付宝|Alipay|支付寶|Alipay',
  'provider_code': '扫描或输入顾客付款码|Scan or enter customer payment code|掃描或輸入顧客付款碼|สแกนหรือกรอกรหัสชำระเงินของลูกค้า',
  'provider_collect':
      '确认金额并收款|Confirm amount and collect|確認金額並收款|ยืนยันยอดและรับชำระ',
  'provider_query': '查询原交易，勿重复收款|Check original transaction; do not charge again|查詢原交易，勿重複收款|ตรวจสอบรายการเดิม อย่าเรียกเก็บซ้ำ',
  'provider_closed_unpaid': '商品已售罄，本单未扣款并已关闭，请重新选择商品。|Sold out. This order was closed without a charge. Please select items again.|商品已售罄，本單未扣款並已關閉，請重新選擇商品。|สินค้าหมด ปิดคำสั่งซื้อแล้วโดยไม่มีการหักเงิน โปรดเลือกสินค้าใหม่',
  'provider_close_attempt': '结束本次收款（保留账单）|End payment attempt (keep bill)|結束本次收款（保留帳單）|ยุติการชำระครั้งนี้ (เก็บบิลไว้)',
  'provider_attempt_closed': '本次收款已关闭，未扣款。消费账单保留，可重新收款。|Payment attempt closed without a charge. The bill remains; collect again.|本次收款已關閉，未扣款。消費帳單保留，可重新收款。|ปิดการชำระครั้งนี้โดยไม่หักเงิน บิลยังคงอยู่ สามารถรับชำระใหม่ได้',
  'provider_confirmed': '服务端已确认付款|Payment confirmed by server|服務端已確認付款|เซิร์ฟเวอร์ยืนยันการชำระเงินแล้ว',
  'provider_pending': '等待付款结果，请查询原交易|Payment pending; check original transaction|等待付款結果，請查詢原交易|รอผลชำระเงิน โปรดตรวจสอบรายการเดิม',
  'provider_unknown': '付款结果未知，请查询原交易|Payment result unknown; check original transaction|付款結果未知，請查詢原交易|ไม่ทราบผลชำระเงิน โปรดตรวจสอบรายการเดิม',
  'provider_closed_or_refunded': '交易关闭或已退款，需要核对|Closed or refunded; review required|交易關閉或已退款，需要核對|รายการปิดหรือคืนเงินแล้ว ต้องตรวจสอบ',
  'provider_balance_refunded': '原余额付款已退款，不再收款|Original balance payment refunded; do not collect again|原餘額付款已退款，不再收款|คืนเงินการชำระด้วยยอดคงเหลือเดิมแล้ว ไม่เรียกเก็บซ้ำ',
  'receiptDocumentTitle':
      '服务端结账单据|Server settlement record|伺服器結帳單據|เอกสารชำระเงินจากเซิร์ฟเวอร์',
  'receiptDocumentNotice': '这是读取时的原单快照，30秒后需刷新；不是税务发票，也不代表已打印。|Original order snapshot at read time; refresh after 30 seconds. Not a tax invoice or proof of printing.|這是讀取時的原單快照，30秒後需重新整理；不是稅務發票，也不代表已列印。|ข้อมูลคำสั่งซื้อ ณ เวลาอ่าน ต้องโหลดใหม่หลัง 30 วินาที ไม่ใช่ใบกำกับภาษีหรือหลักฐานว่าพิมพ์แล้ว',
  'receiptDocumentFailed': '单据读取失败或记录需核对，请重新查询。|Could not verify the record. Reload or review the original order.|單據讀取失敗或記錄需核對，請重新查詢。|อ่านหรือตรวจสอบเอกสารไม่สำเร็จ โปรดโหลดใหม่หรือตรวจสอบคำสั่งซื้อเดิม',
  'receiptDocumentReload': '请刷新读取当前单据。|Refresh to read the current record.|請重新整理讀取目前單據。|โปรดโหลดเอกสารปัจจุบันใหม่',
  'receiptConfirmedAt': '原收款确认时间|Original payment confirmation time|原收款確認時間|เวลายืนยันการรับชำระเดิม',
  'receiptPrincipal': '原扣本金|Original principal debit|原扣本金|เงินต้นที่หักเดิม',
  'receiptGift': '原扣赠送|Original gift debit|原扣贈送|ยอดของแถมที่หักเดิม',
  'receiptRefundedAmount': '已退款金额|Refunded amount|已退款金額|ยอดคืนเงินแล้ว',
  'receiptPartialRefund': '部分退款|Partially refunded|部分退款|คืนเงินบางส่วน',
  'receiptNetAmount':
      '退款后净收款|Net payment after refund|退款後淨收款|ยอดรับสุทธิหลังคืนเงิน',
  'receiptCash': '现金收款|Cash payment|現金收款|รับชำระเงินสด',
  'tableCheckoutCancelQuery': '查询原请求取消结果|Query original cancellation|查詢原請求取消結果|ตรวจสอบผลยกเลิกรายการเดิม',
  'tableCheckoutCancelConsent': '确认仅取消尚未发送的收款请求，不取消订单、不退款。|Cancel only an unsent payment request. Orders remain; this is not a refund.|確認僅取消尚未發送的收款請求，不取消訂單、不退款。|ยืนยันยกเลิกเฉพาะคำขอชำระที่ยังไม่ส่ง ไม่ยกเลิกคำสั่งซื้อและไม่คืนเงิน',
  'tableCheckoutCancel':
      '取消未发送请求|Cancel unsent request|取消未發送請求|ยกเลิกคำขอที่ยังไม่ส่ง',
  'tableCheckoutCancelled': '后台已确认取消未发送请求。原订单保留；关闭后重新读取账单。|Server confirmed cancellation of the unsent request. Orders remain; close and reload the bill.|後台已確認取消未發送請求。原訂單保留；關閉後重新讀取帳單。|เซิร์ฟเวอร์ยืนยันยกเลิกคำขอที่ยังไม่ส่งแล้ว คำสั่งซื้อยังอยู่ โปรดปิดและโหลดบิลใหม่',
  'tableCheckoutNotCancelled': '未取得取消回执，原请求保留。请查原单，不要重复收款。|No cancellation receipt. Original request retained. Query it; do not collect again.|未取得取消回執，原請求保留。請查原單，不要重複收款。|ยังไม่มีหลักฐานยกเลิก เก็บรายการเดิมไว้ โปรดตรวจสอบและอย่าเก็บเงินซ้ำ',
  'tableCheckoutRecoveryTitle':
      '整桌结账恢复|Table checkout recovery|整桌結帳恢復|กู้คืนการชำระทั้งโต๊ะ',
  'tableCheckoutRecoveryNotice': '仅显示本设备当前员工在本店的未决原请求，不是新的待收金额；打开后人工查询，不自动收款。|Original unresolved requests for this employee, device and store, not new amounts due. Query explicitly; no automatic charge.|僅顯示本設備目前員工在本店的未決原請求，不是新的待收金額；開啟後人工查詢，不自動收款。|แสดงคำขอเดิมที่ยังไม่สิ้นสุดของพนักงาน อุปกรณ์ และร้านนี้ ไม่ใช่ยอดใหม่ ต้องตรวจสอบเอง ไม่มีการเรียกเก็บอัตโนมัติ',
  'receiptRasterTitle':
      '小票点阵预览|Receipt raster preview|收據點陣預覽|ตัวอย่างภาพจุดใบเสร็จ',
  'receiptRasterNotice': '候选点宽不代表本机兼容；仅预览，不发送打印。所有分页共同组成原单。|Candidate width is not proof of printer compatibility. Preview only, no output. All pages form one record.|候選點寬不代表本機相容；僅預覽，不發送列印。所有分頁共同組成原單。|ความกว้างที่เลือกไม่ได้ยืนยันความเข้ากันได้ ดูตัวอย่างเท่านั้น ไม่ส่งพิมพ์ ทุกหน้ารวมเป็นเอกสารเดียว',
  'receiptPreviousPage': '上一页|Previous page|上一頁|หน้าก่อน',
  'receiptNextPage': '下一页|Next page|下一頁|หน้าถัดไป',
  'receiptOutputNotice': '仅明确确认后发送原单全部分页。关闭或失效会阻止后续页，但不能撤回已发送内容；异常请核对，勿重复打印。|All pages are sent only after confirmation. Closing or expiry stops later pages, not bytes already sent. Review errors; do not reprint.|僅明確確認後發送原單全部分頁。關閉或失效會阻止後續頁，但不能撤回已發送內容；異常請核對，勿重複列印。|ส่งทุกหน้าเมื่อยืนยันเท่านั้น การปิดหรือหมดอายุหยุดหน้าถัดไปแต่เรียกคืนข้อมูลที่ส่งแล้วไม่ได้ หากผิดพลาดให้ตรวจสอบ อย่าพิมพ์ซ้ำ',
  'receiptSelectPrinter': '读取并选择已授权打印机|Read and select an authorized printer|讀取並選擇已授權印表機|อ่านและเลือกเครื่องพิมพ์ที่อนุญาตแล้ว',
  'receiptPrinterUnavailable': '未找到已授权的兼容USB输出端点，请先在设备检查页核对。|No authorized compatible USB endpoint found. Check the device diagnostics first.|未找到已授權的相容USB輸出端點，請先在設備檢查頁核對。|ไม่พบช่อง USB ที่อนุญาตและรองรับ โปรดตรวจสอบหน้าอุปกรณ์ก่อน',
  'receiptOutputConsent': '确认向所选设备发送本单全部分页；不切纸、不开钱箱。页数|Send all pages to the selected device, without cutting or opening the drawer. Pages|確認向所選設備發送本單全部分頁；不切紙、不開錢箱。頁數|ยืนยันส่งทุกหน้าไปยังเครื่องที่เลือก ไม่ตัดกระดาษหรือเปิดลิ้นชัก จำนวนหน้า',
  'receiptPaperNotice': '原订单读取快照；非税务发票。请保留完整分页，付款与退款以服务器记录为准。|Original order snapshot, not a tax invoice. Keep every page; server payment and refund records prevail.|原訂單讀取快照；非稅務發票。請保留完整分頁，付款與退款以伺服器記錄為準。|ข้อมูลคำสั่งซื้อเดิม ไม่ใช่ใบกำกับภาษี โปรดเก็บทุกหน้าและยึดบันทึกการชำระและคืนเงินของเซิร์ฟเวอร์',
  'printerOutputDisabled': 'USB 输出未启用；当前仅预览。|USB output is disabled; preview only.|USB 輸出未啟用；目前僅預覽。|ยังไม่เปิดการส่ง USB ดูตัวอย่างเท่านั้น',
  'printerOutputCompatibility': '已核实本机支持 GS v 0、所选点宽，且处于标准模式、行首、空缓冲（铭牌 ESC/POS 不足以证明）。|I verified GS v 0, dot width, standard mode, line start and an empty buffer on this printer; an ESC/POS label is insufficient.|已核實本機支援 GS v 0、所選點寬，且處於標準模式、行首、空緩衝（銘牌 ESC/POS 不足以證明）。|ตรวจสอบว่าเครื่องรองรับ GS v 0 และความกว้างจุด อยู่ในโหมดมาตรฐาน ต้นบรรทัด และบัฟเฟอร์ว่างแล้ว ป้าย ESC/POS อย่างเดียวไม่เพียงพอ',
  'printerOutputConsent': '确认向上述设备发送一张非交易测试单，不切纸、不开钱箱。关闭页面不保证取消，异常不自动重打。|Send one non-transaction test receipt to this device, without cutting or opening the drawer. Closing may not cancel output; no automatic retry.|確認向上述設備發送一張非交易測試單，不切紙、不開錢箱。關閉頁面不保證取消，異常不自動重打。|ยืนยันส่งใบทดสอบที่ไม่ใช่ธุรกรรมหนึ่งใบ ไม่ตัดกระดาษหรือเปิดลิ้นชัก การปิดหน้าอาจไม่ยกเลิก และไม่ส่งซ้ำอัตโนมัติ',
  'printerOutputSend':
      '发送一张测试单|Send one test receipt|發送一張測試單|ส่งใบทดสอบหนึ่งใบ',
  'printerOutputAccepted': '字节已交给 USB；请现场核对纸张，不代表打印成功。|USB accepted the bytes. Check the paper; this is not proof of printing.|位元組已交給 USB；請現場核對紙張，不代表列印成功。|USB รับข้อมูลแล้ว โปรดตรวจสอบกระดาษ ยังไม่ยืนยันว่าพิมพ์สำเร็จ',
  'printerOutputReview': '输出结果需人工核对，请勿重打或重置队列绕过。|Output requires manual review. Do not reprint or reset the queue to bypass it.|輸出結果需人工核對，請勿重印或重置佇列繞過。|ต้องตรวจสอบผลด้วยตนเอง อย่าพิมพ์ซ้ำหรือล้างคิวเพื่อข้ามการตรวจสอบ',
  'printerOutputPreview': '预览并确认测试打印|Preview and confirm test printing|預覽並確認測試列印|ดูตัวอย่างและยืนยันการพิมพ์ทดสอบ',
  'provider_not_sent': '原请求尚未发送，请核对后处理|Original request not sent; review required|原請求尚未發送，請核對後處理|ยังไม่ได้ส่งคำขอเดิม ต้องตรวจสอบ',
  'provider_review': '状态需要核对，勿重复收款|Review status; do not charge again|狀態需要核對，勿重複收款|ต้องตรวจสอบสถานะ อย่าเรียกเก็บซ้ำ',
  'sessionSummaryTitle': '本场次全部订单汇总（非结账金额）|All session orders (not a checkout amount)|本場次全部訂單彙總（非結帳金額）|สรุปทุกคำสั่งซื้อในรอบนี้ (ไม่ใช่ยอดเรียกเก็บ)',
  'sessionSummaryUnknown': '本场次汇总未知，不能用本页金额代替。|Session totals unavailable; this page is not the full bill.|本場次彙總未知，不能用本頁金額代替。|ไม่ทราบยอดรวมรอบนี้ ยอดหน้านี้ไม่ใช่บิลทั้งหมด',
  'orderPreviewTitle': '单笔订单预览（未打印）|Single-order preview (not printed)|單筆訂單預覽（未列印）|ดูคำสั่งซื้อเดียว (ยังไม่พิมพ์)',
  'orderPreviewNotice': '仅为订单快照，不是整桌结账单、收款凭证或发票。未发送打印数据。|Order snapshot only, not a whole-table bill, payment receipt or invoice. Nothing sent to a printer.|僅為訂單快照，不是整桌結帳單、收款憑證或發票。未傳送列印資料。|ข้อมูลคำสั่งซื้อเท่านั้น ไม่ใช่บิลรวมโต๊ะ หลักฐานรับเงิน หรือใบกำกับภาษี ยังไม่ส่งข้อมูลไปพิมพ์',
  'orderPreviewStatus':
      '服务端订单状态|Server order status|伺服器訂單狀態|สถานะคำสั่งซื้อจากเซิร์ฟเวอร์',
  'orderPreviewTotal': '本订单金额|This order amount|本訂單金額|ยอดคำสั่งซื้อนี้',
  'orderPreviewExpired': '预览已失效，请关闭并重新查询。|Preview is no longer current. Close and reload.|預覽已失效，請關閉並重新查詢。|ข้อมูลตัวอย่างไม่เป็นปัจจุบันแล้ว ปิดแล้วโหลดใหม่',
  'printerInspectTitle': '打印设备检查|Printer check|列印設備檢查|ตรวจสอบเครื่องพิมพ์',
  'printerInspectNotice': '打开此页仅发现本机服务及USB打印类候选设备，不自动连接打印服务。不打印、不走纸、不切纸、不开钱箱，无需员工登录。|Opening this page only discovers local services and USB printer-class candidates; it does not connect automatically. No printing, feeding, cutting or drawer opening. No staff login required.|開啟此頁僅發現本機服務及USB列印類候選設備，不自動連接列印服務。不列印、不走紙、不切紙、不開錢箱，無需員工登入。|เมื่อเปิดหน้านี้จะค้นหาบริการและอุปกรณ์ USB ประเภทเครื่องพิมพ์เท่านั้น ไม่เชื่อมต่ออัตโนมัติ ไม่พิมพ์ เลื่อนหรือตัดกระดาษ หรือเปิดลิ้นชัก ไม่ต้องเข้าสู่ระบบพนักงาน',
  'printerInspectFailed': '无法完成检查；不代表没有打印机。请稍后手动重试。|Check unavailable; this does not mean no printer exists. Retry manually later.|無法完成檢查；不代表沒有印表機。請稍後手動重試。|ตรวจสอบไม่ได้ ไม่ได้หมายความว่าไม่มีเครื่องพิมพ์ โปรดลองใหม่ภายหลัง',
  'printerInspectStale': '旧结果已清除，请重新检查。|Previous results cleared. Run a new check.|舊結果已清除，請重新檢查。|ล้างผลเดิมแล้ว โปรดตรวจสอบใหม่',
  'printerDetected': '是|Yes|是|ใช่',
  'printerNotDetected': '否|No|否|ไม่ใช่',
  'printerUnknown': '未知|Unknown|未知|ไม่ทราบ',
  'printerServiceInstalled':
      'SUNMI服务已安装|SUNMI service installed|SUNMI服務已安裝|ติดตั้งบริการ SUNMI แล้ว',
  'printerServiceEnabled': '服务已启用|Service enabled|服務已啟用|เปิดใช้บริการแล้ว',
  'printerServiceResolvable':
      '系统可解析服务|Service resolves in system|系統可解析服務|ระบบค้นหาบริการได้',
  'printerServiceVersion': '服务版本|Service version|服務版本|เวอร์ชันบริการ',
  'printerUsbCandidates': 'USB打印类候选数量|USB printer-class candidates|USB列印類候選數量|จำนวนอุปกรณ์ USB ประเภทเครื่องพิมพ์',
  'printerObservedAt': '本次检查时间|Checked at|本次檢查時間|เวลาตรวจสอบ',
  'printerReadinessUnknown': '发现服务或USB设备不代表可打印。硬件状态须单独读取；即使报告正常，也不代表小票已打印。|Finding a service or USB device does not prove readiness. Read hardware status separately; even a normal report does not prove a printed receipt.|發現服務或USB設備不代表可列印。硬體狀態須單獨讀取；即使報告正常，也不代表收據已列印。|การพบบริการหรืออุปกรณ์ USB ไม่ยืนยันว่าพร้อมพิมพ์ ต้องอ่านสถานะฮาร์ดแวร์แยกต่างหาก แม้รายงานปกติก็ไม่ยืนยันว่าพิมพ์ใบเสร็จแล้ว',
  'printerInspectRefresh': '重新检查|Check again|重新檢查|ตรวจสอบอีกครั้ง',
  'printerInspectClose': '关闭|Close|關閉|ปิด',
  'printerStatusInspect':
      '商米内置状态|SUNMI internal status|商米內建狀態|สถานะภายใน SUNMI',
  'printerUsbPermission':
      '本应用USB授权|USB permission for this app|本應用USB授權|สิทธิ์ USB ของแอปนี้',
  'printerUsbAuthorize': '申请USB授权|Request USB access|申請USB授權|ขอสิทธิ์ USB',
  'printerTestTitle': '测试小票 / 非交易凭证|TEST SLIP / NOT A TRANSACTION|測試小票 / 非交易憑證|ใบทดสอบ / ไม่ใช่หลักฐานธุรกรรม',
  'printerTestPreview': '测试单预览（未打印）|Test preview (not printed)|測試單預覽（未列印）|ดูใบทดสอบ (ยังไม่พิมพ์)',
  'printerTestPreviewNotice': '仅生成本地点阵图，不连接打印机。宽度是候选点数，不是已验证纸宽；真实出纸仍需另行确认。|Local bitmap only; no printer connection. Width is a candidate dot count, not verified paper width. Physical printing requires separate confirmation.|僅產生本機點陣圖，不連接印表機。寬度是候選點數，不是已驗證紙寬；實際出紙仍需另行確認。|สร้างภาพในเครื่องเท่านั้น ไม่เชื่อมต่อเครื่องพิมพ์ ความกว้างเป็นจำนวนจุดทดลอง ไม่ใช่ขนาดกระดาษที่ยืนยัน การพิมพ์จริงต้องยืนยันแยกต่างหาก',
  'printerTestPreviewFailed': '无法生成预览，请重试。未连接打印机。|Could not render preview. Retry; no printer was connected.|無法產生預覽，請重試。未連接印表機。|สร้างภาพตัวอย่างไม่ได้ โปรดลองใหม่ ยังไม่ได้เชื่อมต่อเครื่องพิมพ์',
  'printerTestBody': '仅检查文字、宽度和清晰度。|Text, width and legibility check only.|僅檢查文字、寬度和清晰度。|ตรวจสอบข้อความ ความกว้าง และความชัดเจนเท่านั้น',
  'printerTestDotWidth': '候选宽度（点，未实测）|Candidate width (dots, unverified)|候選寬度（點，未實測）|ความกว้างทดลอง (จุด ยังไม่ยืนยัน)',
  'printerTestGlyphs': '简体中文：酒水、桌台、会员|English: drinks, tables, members|繁體中文：酒水、桌檯、會員|ภาษาไทย: เครื่องดื่ม โต๊ะ สมาชิก',
  'printerTestNoTransaction': '无订单、无收款、无会员数据。|No order, payment or member data.|無訂單、無收款、無會員資料。|ไม่มีคำสั่งซื้อ การชำระเงิน หรือข้อมูลสมาชิก',
  'printerUsbAuthorizeNotice': '仅向系统申请访问所选USB打印设备。不会打开接口、发送数据或试打，也不改变收银员工权限。请在系统提示中核对设备；拔插后需重新检查。|Only request OS access to the selected USB printer. No interface opening, data transfer, test print or staff permission changes. Check the device in the system prompt; inspect again after reconnection.|僅向系統申請存取所選USB列印設備。不會開啟介面、傳送資料或試印，也不改變收銀員工權限。請在系統提示中核對設備；拔插後需重新檢查。|ขอสิทธิ์ระบบเพื่อเข้าถึงเครื่องพิมพ์ USB ที่เลือกเท่านั้น ไม่เปิดอินเทอร์เฟซ ส่งข้อมูล ทดลองพิมพ์ หรือเปลี่ยนสิทธิ์พนักงาน ตรวจสอบอุปกรณ์ในหน้าต่างระบบและตรวจใหม่หลังเชื่อมต่ออีกครั้ง',
  'printerUsbAuthorizeWaiting': '等待系统授权结果；不会自动打印。关闭此页仅停止等待，不代表撤销系统授权。|Waiting for OS authorization; no automatic printing. Closing this page only stops waiting, not revoking OS access.|等待系統授權結果；不會自動列印。關閉此頁僅停止等待，不代表撤銷系統授權。|รอผลอนุญาตจากระบบ ไม่พิมพ์อัตโนมัติ การปิดหน้านี้หยุดรอเท่านั้น ไม่ได้เพิกถอนสิทธิ์ระบบ',
  'printerUsbAuthorizeRefresh': '授权请求已结束或结果不确定。请点“重新检查”读取当前设备及真实授权状态，未执行打印。|Authorization finished or is uncertain. Check again to read the current device and actual access state. Nothing was printed.|授權請求已結束或結果不確定。請點「重新檢查」讀取目前設備及真實授權狀態，未執行列印。|คำขอสิ้นสุดหรือผลยังไม่แน่ชัด โปรดตรวจสอบอีกครั้งเพื่ออ่านอุปกรณ์และสิทธิ์จริง ยังไม่มีการพิมพ์',
  'printerUsbInterface': '接口/备用设置（类/子类/协议）|Interface/alternate (class/subclass/protocol)|介面/備用設定（類別/子類別/協定）|อินเทอร์เฟซ/ทางเลือก (คลาส/คลาสย่อย/โปรโตคอล)',
  'printerUsbBulkOut': '打印类批量输出端点|Printer-class bulk output endpoint|列印類批量輸出端點|ปลายทางส่งออกแบบ bulk ของคลาสเครื่องพิมพ์',
  'printerUsbNotice': '仅列出USB描述和当前授权；未打开或占用接口、未发送数据。USB编号不能单独确定品牌或打印协议，外接打印机不受下方商米内置状态代表。|USB descriptors and current permission only; no interface opened or claimed, no data sent. IDs alone do not identify brand or print protocol. The SUNMI internal status below does not describe external printers.|僅列出USB描述及目前授權；未開啟或占用介面、未傳送資料。USB編號不能單獨確定品牌或列印協定，外接印表機不受下方商米內建狀態代表。|แสดงรายละเอียด USB และสิทธิ์ปัจจุบันเท่านั้น ไม่เปิดหรือยึดอินเทอร์เฟซและไม่ส่งข้อมูล รหัสไม่ยืนยันยี่ห้อหรือคำสั่งพิมพ์ สถานะ SUNMI ด้านล่างไม่ใช่สถานะเครื่องพิมพ์ภายนอก',
  'printerStatusNotice': '“商米内置状态”仅短暂查询商米内置服务，不代表外接芯烨打印机。不初始化、不打印；纸张原始码不等于毫米，实际纸宽及出纸仍需核验。|SUNMI internal status briefly queries only the internal service, not an external Xprinter. No initialization or printing. Raw paper codes are not millimetres; physical width and output still need verification.|「商米內建狀態」僅短暫查詢商米內建服務，不代表外接芯燁印表機。不初始化、不列印；紙張原始碼不等於毫米，實際紙寬及出紙仍需核驗。|สถานะภายใน SUNMI ตรวจเฉพาะบริการภายในชั่วคราว ไม่ใช่เครื่อง Xprinter ภายนอก ไม่เริ่มต้นหรือพิมพ์ รหัสกระดาษไม่ใช่มิลลิเมตร ยังต้องตรวจความกว้างและการพิมพ์จริง',
  'printerStatusReport':
      '商米内置服务状态|SUNMI internal service status|商米內建服務狀態|สถานะบริการภายใน SUNMI',
  'printerPaperRaw':
      '纸张原始码（非毫米）|Raw paper code (not mm)|紙張原始碼（非毫米）|รหัสกระดาษ (ไม่ใช่ มม.)',
  'printerStateNormal': '报告正常（未试打）|Reported normal (not print-tested)|報告正常（未試印）|รายงานปกติ (ยังไม่ทดลองพิมพ์)',
  'printerStatePreparing': '准备中|Preparing|準備中|กำลังเตรียม',
  'printerStateCommunication':
      '通信异常|Communication error|通訊異常|การสื่อสารผิดพลาด',
  'printerStateNoPaper': '缺纸|Out of paper|缺紙|กระดาษหมด',
  'printerStateHot': '过热|Overheated|過熱|ร้อนเกินไป',
  'printerStateCover': '纸仓盖打开|Cover open|紙倉蓋開啟|ฝาเปิด',
  'printerStateCutterError': '切刀异常|Cutter error|切刀異常|ใบมีดผิดพลาด',
  'printerStateCutterRecovered': '切刀恢复|Cutter recovered|切刀恢復|ใบมีดกลับสู่ปกติ',
  'printerStateBlackMark': '未检测到黑标|Black mark not detected|未偵測到黑標|ไม่พบแถบดำ',
  'printerStateNotDetected': '服务未检测到打印机|Service did not detect a printer|服務未偵測到印表機|บริการไม่พบเครื่องพิมพ์',
  'printerStateFirmware':
      '固件更新失败|Firmware update failed|韌體更新失敗|อัปเดตเฟิร์มแวร์ล้มเหลว',
  'cartDraftsTitle': '本机草稿|Local drafts|本機草稿|ร่างในเครื่อง',
  'cartDraftsNotice': '仅显示当前员工在本门店、本设备保存的未提交草稿，包含旧场次。恢复请返回当前桌台选择仍在座的会员；不能把旧草稿转到新场次。有待确认订单时先处理原请求。|Unsubmitted drafts saved by this employee for this store and device, including old sessions. To restore, return to the current table and select a seated member. Never transfer old drafts to a new session. Resolve pending order requests first.|僅顯示當前員工在本門店、本裝置儲存的未提交草稿，包含舊場次。恢復請返回當前桌台選擇仍在座的會員；不能把舊草稿轉到新場次。有待確認訂單時先處理原請求。|แสดงร่างที่ยังไม่ส่งของพนักงานนี้สำหรับร้านและเครื่องนี้ รวมรอบเก่า หากต้องการเรียกคืน ให้กลับไปโต๊ะปัจจุบันและเลือกสมาชิกที่ยังนั่งอยู่ ห้ามย้ายร่างเก่าไปรอบใหม่ จัดการคำขอคำสั่งซื้อที่ยังไม่ทราบผลก่อน',
  'cartDraftsEmpty': '没有可见的本机草稿|No visible local drafts|沒有可見的本機草稿|ไม่มีร่างในเครื่องที่แสดงได้',
  'cartDraftSavedAt': '保存时间|Saved at|儲存時間|เวลาที่บันทึก',
  'cartDraftEstimate': '保存时估算金额，非账单|Saved estimate, not a bill|儲存時估算金額，非帳單|ยอดประมาณตอนบันทึก ไม่ใช่ใบเรียกเก็บเงิน',
  'cartDraftLocalDeleteNotice': '只删除本机这份未提交草稿，不取消订单、不退款，也不清台。请确认桌台、场次和会员。|Delete this local unsubmitted draft only. No order cancellation, refund or table clearing. Check the table, session and member.|只刪除本機這份未提交草稿，不取消訂單、不退款，也不清台。請確認桌台、場次和會員。|ลบเฉพาะร่างที่ยังไม่ส่งในเครื่องนี้ ไม่ยกเลิกคำสั่งซื้อ คืนเงิน หรือปิดโต๊ะ โปรดตรวจสอบโต๊ะ รอบ และสมาชิก',
  'cartDraftSave': '保存草稿|Save draft|儲存草稿|บันทึกร่าง',
  'cartDraftRestore': '恢复草稿|Restore draft|恢復草稿|เรียกคืนร่าง',
  'cartDraftDiscard': '删除草稿|Delete draft|刪除草稿|ลบร่าง',
  'cartDraftNotice': '草稿只保存在本设备，未下单、不锁价或库存。未保存的修改离页即丢失。|Drafts stay on this device. No order, price lock or stock reservation. Unsaved edits are lost on leaving.|草稿只儲存在本裝置，未下單、不鎖價或庫存。未儲存的修改離頁即遺失。|ร่างอยู่ในเครื่องนี้เท่านั้น ยังไม่ได้สั่งซื้อ ล็อกราคา หรือจองสต็อก การแก้ไขที่ไม่บันทึกจะหายเมื่อออก',
  'cartDraftFound': '发现本场次草稿，请恢复或删除后继续。|A draft exists for this session. Restore or delete it to continue.|發現本場次草稿，請恢復或刪除後繼續。|พบร่างของรอบนี้ โปรดเรียกคืนหรือลบก่อนดำเนินการต่อ',
  'cartDraftSaved': '草稿已保存，尚未下单。|Draft saved. No order placed.|草稿已儲存，尚未下單。|บันทึกร่างแล้ว ยังไม่ได้สั่งซื้อ',
  'cartDraftRestored': '已按当前会员、价格及库存核对草稿，请再次确认后下单。|Draft checked against current membership, prices and stock. Review before placing the order.|已按當前會員、價格及庫存核對草稿，請再次確認後下單。|ตรวจสอบสมาชิก ราคา และสต็อกปัจจุบันแล้ว โปรดตรวจทานก่อนสั่งซื้อ',
  'cartDraftDiscardNotice': '只删除本设备这份草稿并清空当前选择，不取消任何订单。|Delete this local draft and clear current selections only. No order is cancelled.|只刪除本裝置這份草稿並清空當前選擇，不取消任何訂單。|ลบเฉพาะร่างนี้ในเครื่องและล้างรายการที่เลือก ไม่ยกเลิกคำสั่งซื้อใด',
  'cartDraftDiscarded': '草稿已删除，未操作订单。|Draft deleted. Orders unchanged.|草稿已刪除，未操作訂單。|ลบร่างแล้ว ไม่ได้เปลี่ยนคำสั่งซื้อ',
  'cartDraftResave': '选择已修改，请先重新保存草稿再下单。|Selections changed. Save the updated draft before ordering.|選擇已修改，請先重新儲存草稿再下單。|รายการเปลี่ยนแล้ว โปรดบันทึกร่างใหม่ก่อนสั่งซื้อ',
  'cartDraftFailed': '草稿处理未完成。请核对场次、商品和网络；保存或删除失败后请返回重进，读取实际保存结果。|Draft action incomplete. Check session, items and connection. After a save or delete failure, return and reopen to read the actual saved state.|草稿處理未完成。請核對場次、商品和網路；儲存或刪除失敗後請返回重進，讀取實際儲存結果。|ดำเนินการกับร่างไม่สำเร็จ ตรวจสอบรอบ สินค้า และเครือข่าย หากบันทึกหรือลบไม่สำเร็จ ให้กลับแล้วเปิดใหม่เพื่อตรวจสอบสถานะจริง',
  'tableClearConfirm': '核对并清台|Review and clear table|核對並清台|ตรวจสอบและปิดโต๊ะ',
  'tableClearCancel': '暂不清台|Not now|暫不清台|ยังไม่ปิดโต๊ะ',
  'tableClearConfirmNotice': '确认顾客已离座且现场已整理。本操作关闭这个场次，不收款、不退款，也不删除历史。服务器将核对全部订单、付款与上菜记录；未满足条件会拒绝。|Confirm guests have left and the table is ready. Closes this session only; no payment, refund or history deletion. The server checks all orders, payments and delivery records and rejects unmet conditions.|確認顧客已離座且現場已整理。本操作關閉這個場次，不收款、不退款，也不刪除歷史。伺服器將核對全部訂單、付款與上菜記錄；未滿足條件會拒絕。|ยืนยันว่าลูกค้าออกและจัดโต๊ะเรียบร้อย ปิดเฉพาะรอบนี้ ไม่รับเงิน คืนเงิน หรือลบประวัติ เซิร์ฟเวอร์ตรวจคำสั่งซื้อ การชำระเงิน และการเสิร์ฟทั้งหมด และจะปฏิเสธหากไม่ผ่านเงื่อนไข',
  'tableClearRecoveryTitle':
      '清台请求处理|Table clearing requests|清台請求處理|จัดการคำขอปิดโต๊ะ',
  'tableClearRecoveryNotice': '仅处理本员工本设备的原请求。历史清台回执不代表当前桌台为空；返回后重新读取当前桌台。|Original requests for this employee and device only. A historical receipt does not mean the table is empty now. Return to reload current tables.|僅處理本員工本裝置的原請求。歷史清台回執不代表目前桌台為空；返回後重新讀取目前桌台。|จัดการคำขอเดิมของพนักงานและเครื่องนี้เท่านั้น ใบยืนยันย้อนหลังไม่ได้แปลว่าโต๊ะว่างตอนนี้ กลับไปโหลดสถานะโต๊ะใหม่',
  'tableClearLookup': '查询原请求|Look up original|查詢原請求|ตรวจสอบคำขอเดิม',
  'tableClearRetry':
      '恢复原清台请求|Resume original clearing|恢復原清台請求|ดำเนินคำขอปิดโต๊ะเดิมต่อ',
  'tableClearRetryNotice': '仅重发原场次、原请求号，不清除新场次。请再次核对该场次已具备清台条件；未查到不代表原请求已取消。|Resend only the original session and request ID, never a new session. Recheck that this session is ready to clear. Not observed does not mean cancelled.|僅重發原場次、原請求號，不清除新場次。請再次核對該場次已具備清台條件；未查到不代表原請求已取消。|ส่งเฉพาะรอบและรหัสคำขอเดิม ไม่ปิดรอบใหม่ ตรวจสอบอีกครั้งว่ารอบนี้พร้อมปิด การไม่พบผลไม่ได้หมายถึงยกเลิก',
  'tableClearConfirmed': '服务器已确认原场次清台。返回重新读取当前桌台。|Server confirmed clearing the original session. Return to reload current tables.|伺服器已確認原場次清台。返回重新讀取目前桌台。|เซิร์ฟเวอร์ยืนยันปิดรอบเดิมแล้ว กลับไปโหลดสถานะโต๊ะปัจจุบันใหม่',
  'tableClearUnresolved': '尚未查到结果，保留原请求，未自动重发。|No result observed. Original request retained; not resent automatically.|尚未查到結果，保留原請求，未自動重發。|ยังไม่พบผล เก็บคำขอเดิมไว้ ไม่ส่งซ้ำอัตโนมัติ',
  'tableClearNoPending': '暂无可见未决清台请求|No visible unresolved clearing requests|暫無可見未決清台請求|ไม่มีคำขอปิดโต๊ะที่ยังไม่ทราบผลที่แสดงได้',
  'tableClearFailed': '清台或查询未完成。请核对员工权限、订单及原请求；不能视为已清台或记录为空。|Clearing or lookup did not complete. Review permissions, orders and original requests; do not assume success or an empty journal.|清台或查詢未完成。請核對員工權限、訂單及原請求；不能視為已清台或記錄為空。|ปิดโต๊ะหรือตรวจสอบไม่สำเร็จ ตรวจสิทธิ์ คำสั่งซื้อ และคำขอเดิม ห้ามถือว่าสำเร็จหรือไม่มีบันทึก',
  'servingConfirm': '确认上菜记录|Confirm delivery|確認上菜記錄|ยืนยันบันทึกการเสิร์ฟ',
  'servingThisQuantity': '本次实际已上数量|Quantity actually delivered now|本次實際已上數量|จำนวนที่เสิร์ฟจริงครั้งนี้',
  'servingConfirmNotice': '仅登记已实际交付的数量，不是下单、出库或收款。请核对后确认。|Record goods actually delivered, not a new order, stock issue or payment. Verify before confirming.|僅登記已實際交付的數量，不是下單、出庫或收款。請核對後確認。|บันทึกเฉพาะจำนวนที่เสิร์ฟจริง ไม่ใช่การสั่งซื้อ ตัดสต็อก หรือชำระเงิน โปรดตรวจสอบก่อนยืนยัน',
  'servingRecoveryTitle': '上菜请求处理|Delivery requests|上菜請求處理|จัดการคำขอเสิร์ฟ',
  'servingRecoveryNotice': '仅显示本员工本设备的未决原请求。先查回结果，不能据此重复交付实物。|Unresolved original requests for this employee and device. Look up results first; do not deliver goods again.|僅顯示本員工本設備的未決原請求。先查回結果，不能據此重複交付實物。|แสดงคำขอเดิมที่ยังไม่ทราบผลของพนักงานและเครื่องนี้ ตรวจสอบผลก่อน ห้ามเสิร์ฟสินค้าซ้ำ',
  'servingLookup': '查询原请求|Look up original|查詢原請求|ตรวจสอบคำขอเดิม',
  'servingRetry': '恢复原登记|Resume original record|恢復原登記|ดำเนินการบันทึกเดิมต่อ',
  'servingRetryNotice': '只重发原始登记，不再交付一份商品。若已由其他员工登记或数量冲突，请先核对，不新建替代请求。|Resend the original record only. Do not deliver goods again. If another employee recorded it or counts conflict, review before proceeding; do not create a replacement request.|只重發原始登記，不再交付一份商品。若已由其他員工登記或數量衝突，請先核對，不新建替代請求。|ส่งบันทึกเดิมอีกครั้งเท่านั้น ห้ามเสิร์ฟซ้ำ หากพนักงานอื่นบันทึกแล้วหรือจำนวนขัดแย้ง ให้ตรวจสอบก่อน ห้ามสร้างคำขอแทน',
  'servingConfirmed': '原登记已由服务器确认。返回订单刷新当前数量。|Original record confirmed by the server. Return and refresh current order counts.|原登記已由伺服器確認。返回訂單重新整理當前數量。|เซิร์ฟเวอร์ยืนยันบันทึกเดิมแล้ว กลับไปรีเฟรชจำนวนปัจจุบันของรายการ',
  'servingUnresolved': '尚未查到原请求结果；记录仍保留，未自动重发。|No original result observed. The record is retained; nothing was resent automatically.|尚未查到原請求結果；記錄仍保留，未自動重發。|ยังไม่พบผลของคำขอเดิม เก็บบันทึกไว้แล้วและไม่ได้ส่งซ้ำอัตโนมัติ',
  'servingNoPending': '暂无可见未决上菜请求|No visible unresolved delivery requests|暫無可見未決上菜請求|ไม่มีคำขอเสิร์ฟที่ยังไม่ทราบผลที่แสดงได้',
  'servingFailed': '查询或登记未完成，请保留原请求后再核对。|Lookup or recording did not complete. Retain the original request and review.|查詢或登記未完成，請保留原請求後再核對。|ตรวจสอบหรือบันทึกไม่สำเร็จ โปรดเก็บคำขอเดิมไว้และตรวจสอบอีกครั้ง',
  'servingDelivered': '已上|Delivered|已上|เสิร์ฟแล้ว',
  'servingRemaining': '待上|Remaining|待上|ยังไม่เสิร์ฟ',
  'servingUnknown': '服务器未提供上菜记录|Delivery record unavailable from server|伺服器未提供上菜記錄|เซิร์ฟเวอร์ยังไม่มีข้อมูลการเสิร์ฟ',
  'servingProgressNotice': '已上数量仅代表系统确认记录，不代表已付款；历史交付需核对。|Delivery counts reflect confirmed records, not payment. Verify historical deliveries.|已上數量僅代表系統確認記錄，不代表已付款；歷史交付需核對。|จำนวนที่เสิร์ฟแสดงเฉพาะบันทึกที่ยืนยัน ไม่ใช่การชำระเงิน โปรดตรวจสอบการเสิร์ฟย้อนหลัง',
  'cashPrepare': '准备现金收款|Prepare cash payment|準備現金收款|เตรียมรับเงินสด',
  'cashPrepareCancel': '暂不收款|Not now|暫不收款|ยังไม่รับเงิน',
  'cashPrepareNotice': '仅准备本笔订单的现金请求，不代表已收款。准备后先查询状态，再核对实际收妥金额。异常时处理原请求，不重复创建。|Prepare a cash request for this order only; this does not mark it paid. Then look up its state and review cash actually received. Recover the original request after an error; do not create another.|僅準備本筆訂單的現金請求，不代表已收款。準備後先查詢狀態，再核對實際收妥金額。異常時處理原請求，不重複建立。|สร้างคำขอเงินสดสำหรับคำสั่งซื้อนี้เท่านั้น ยังไม่ถือว่าชำระแล้ว ตรวจสอบสถานะและยอดเงินที่รับจริง หากผิดพลาดให้กู้คืนคำขอเดิม ไม่สร้างซ้ำ',
  'ordersSnapshotNotice': '订单明细不是整桌结账单。现金入口仅适用于获授权的员工订单，结果以服务端确认为准。|These orders are not a whole-table bill. Cash preparation is limited to authorized staff orders; the server confirms the outcome.|訂單明細不是整桌結帳單。現金入口僅適用於獲授權的員工訂單，結果以服務端確認為準。|รายการนี้ไม่ใช่บิลรวมทั้งโต๊ะ รับเงินสดได้เฉพาะคำสั่งซื้อของพนักงานที่มีสิทธิ์ ผลยืนยันจากเซิร์ฟเวอร์',
  'cashRecoveryTitle': '现金请求处理|Cash request recovery|現金請求處理|จัดการคำขอเงินสด',
  'cashRecoveryNotice': '只处理当前员工在本设备保存的原请求。先查回状态；请求金额不是付款凭证。|Original requests saved for this employee on this device. Look up first; amounts are not payment evidence.|只處理目前員工在本裝置儲存的原請求。先查回狀態；請求金額不是付款憑證。|จัดการเฉพาะคำขอเดิมของพนักงานนี้บนอุปกรณ์นี้ ตรวจสอบก่อน ยอดเงินไม่ใช่หลักฐานการชำระเงิน',
  'cashConfirm': '核对现金收妥|Review cash received|核對現金收妥|ตรวจสอบเงินสดที่รับ',
  'cashClose': '终止未收款意图|Close uncollected cash intent|終止未收款意圖|ยุติรายการที่ยังไม่ได้รับเงินสด',
  'cashRetry': '查回并重试原准备请求|Look up and retry original preparation|查回並重試原準備請求|ตรวจสอบและลองเตรียมคำขอเดิมอีกครั้ง',
  'cashDue': '应收|Amount due|應收|ยอดที่ต้องชำระ',
  'cashReceived': '实收现金|Cash received|實收現金|เงินสดที่รับ',
  'cashChange': '应找零|Change due|應找零|เงินทอน',
  'cashAmountInvalid': '请输入不低于应收的现金金额，最多两位小数。|Enter cash received, at least the amount due, with up to two decimals.|請輸入不低於應收的現金金額，最多兩位小數。|กรอกเงินสดที่รับไม่น้อยกว่ายอดชำระ ทศนิยมไม่เกินสองตำแหน่ง',
  'cashReceivedNotice': '仅在现金确已收到后确认。实收金额会持久保存，超时后不能改成未收款终止。|Confirm only after physically receiving cash. The amount is saved and cannot be changed to uncollected after a timeout.|僅在現金確已收到後確認。實收金額會持久儲存，逾時後不能改成未收款終止。|ยืนยันเมื่อได้รับเงินสดจริงเท่านั้น ยอดจะถูกบันทึก หากหมดเวลาจะเปลี่ยนเป็นยังไม่ได้รับเงินไม่ได้',
  'cashReturnClose':
      '退回现金后结束|Close after returning cash|退回現金後結束|ยุติหลังคืนเงินสด',
  'cashReturnNotice': '仅限原收款尚未记账。请确认顾客现金已全部退还，没有留存；这不会撤销已记账的付款。|Only for an unposted collection. Confirm all customer cash has been returned and none retained. This does not reverse a posted payment.|僅限原收款尚未記帳。請確認顧客現金已全部退還，沒有留存；這不會撤銷已記帳的付款。|ใช้กับรายการที่ยังไม่บันทึกรับเงินเท่านั้น ยืนยันว่าคืนเงินสดลูกค้าครบแล้วและไม่ได้เก็บไว้ ไม่ใช่การยกเลิกยอดที่บันทึกแล้ว',
  'cashReturnedConfirm': '现金已全部退还|All cash returned|現金已全部退還|คืนเงินสดครบแล้ว',
  'cashCloseNotice': '仅在确认未收取现金时终止。此操作不是退款，也不取消订单；已收到或不确定时请勿继续。|Close only if no cash was collected. This is not a refund or order cancellation. Do not continue if cash was received or you are unsure.|僅在確認未收取現金時終止。此操作不是退款，也不取消訂單；已收到或不確定時請勿繼續。|ยุติเฉพาะเมื่อยังไม่ได้รับเงินสด ไม่ใช่การคืนเงินหรือยกเลิกคำสั่งซื้อ หากรับเงินแล้วหรือไม่แน่ใจห้ามดำเนินการ',
  'cashRetryNotice': '仅重试原收款准备，不确认付款、不生成新请求号。|Retries the original preparation only; no payment confirmation or new request ID.|僅重試原收款準備，不確認付款、不產生新請求號。|ลองเตรียมคำขอเดิมเท่านั้น ไม่ยืนยันการชำระเงินหรือสร้างรหัสใหม่',
  'cashReceivedConfirm':
      '我确认现金已收妥|I have received the cash|我確認現金已收妥|ฉันได้รับเงินสดแล้ว',
  'cashNotReceivedConfirm':
      '我确认未收取现金|I have not collected cash|我確認未收取現金|ฉันยังไม่ได้รับเงินสด',
  'cashPaid': '服务器已确认该笔现金付款。|Server confirmed this cash payment.|伺服器已確認該筆現金付款。|เซิร์ฟเวอร์ยืนยันการชำระเงินสดนี้แล้ว',
  'cashClosed': '原现金意图已终止；不是退款或订单取消。|Original cash intent closed; not a refund or order cancellation.|原現金意圖已終止；不是退款或訂單取消。|รายการเงินสดเดิมยุติแล้ว ไม่ใช่การคืนเงินหรือยกเลิกคำสั่งซื้อ',
  'cashUnknown': '原请求尚待查回，不代表取消或付款失败。|Original request needs lookup; this does not mean cancellation or failed payment.|原請求尚待查回，不代表取消或付款失敗。|ต้องตรวจสอบคำขอเดิม ไม่ได้หมายถึงยกเลิกหรือชำระเงินล้มเหลว',
  'cashNeedsLookup': '已有现金意图，请查回当前状态。|Cash intent exists. Look up its current state.|已有現金意圖，請查回目前狀態。|มีรายการเงินสดแล้ว โปรดตรวจสอบสถานะปัจจุบัน',
  'cashPrepared': '服务器返回待确认；请核对金额及现金。|Server reports prepared. Verify the amount and physical cash.|伺服器回傳待確認；請核對金額及現金。|เซิร์ฟเวอร์แจ้งว่าพร้อมยืนยัน โปรดตรวจยอดและเงินสด',
  'cashCannotConfirm': '当前不可确认收款。若现金已收到，请保留记录并联系负责人核实。|Cannot confirm now. If cash was received, keep this record and ask a manager to reconcile.|目前不可確認收款。若現金已收到，請保留記錄並聯絡負責人核實。|ยังยืนยันไม่ได้ หากได้รับเงินแล้วให้เก็บบันทึกนี้และติดต่อผู้จัดการตรวจสอบ',
  'cashUnconfirmed': '结果未确认，原请求已保留。请查回；勿重复收钱或改换请求。|Result unconfirmed. Original request retained. Look it up; do not collect again or replace the request.|結果未確認，原請求已保留。請查回；勿重複收錢或改換請求。|ยังไม่ยืนยันผล เก็บคำขอเดิมไว้แล้ว โปรดตรวจสอบ ห้ามเก็บเงินซ้ำหรือเปลี่ยนคำขอ',
  'cashLoadFailed': '无法读取现金记录；不能将其视为空。请检查安全存储或员工会话。|Cannot read cash records; this is not an empty list. Check secure storage or the employee session.|無法讀取現金記錄；不能將其視為空。請檢查安全儲存或員工會話。|อ่านบันทึกเงินสดไม่ได้ ไม่ได้หมายความว่าไม่มีรายการ โปรดตรวจที่เก็บปลอดภัยหรือเซสชันพนักงาน',
  'cashEmpty': '本设备当前员工没有待处理现金请求。|No pending cash requests for this employee on this device.|本裝置目前員工沒有待處理現金請求。|ไม่มีคำขอเงินสดค้างของพนักงานนี้บนอุปกรณ์นี้',
  'cashDecisionReceived': '本机已记录现金收妥，服务器结果待核实。|Cash receipt recorded locally; server result needs verification.|本機已記錄現金收妥，伺服器結果待核實。|บันทึกว่ารับเงินสดแล้วในเครื่อง ต้องตรวจสอบผลจากเซิร์ฟเวอร์',
  'cashDecisionClose': '本机已记录未收款终止决定，服务器结果待核实。|Uncollected-cash closure recorded locally; server result needs verification.|本機已記錄未收款終止決定，伺服器結果待核實。|บันทึกการยุติโดยไม่ได้รับเงินสดในเครื่อง ต้องตรวจสอบผลจากเซิร์ฟเวอร์',
  'cartTitle': '点单购物车|Order cart|點單購物車|ตะกร้าสั่งซื้อ',
  'cartNotice': '商品与库存为查询时快照，下单由服务器重新核对。|Catalog and stock are observations, rechecked by the server on submission.|商品與庫存為查詢時快照，下單由伺服器重新核對。|สินค้าและสต็อกเป็นข้อมูลขณะค้นหา เซิร์ฟเวอร์จะตรวจสอบอีกครั้งเมื่อสั่งซื้อ',
  'cartAdd': '加入／增加|Add|加入／增加|เพิ่ม',
  'cartRemove': '减少数量|Reduce quantity|減少數量|ลดจำนวน',
  'cartDelete': '移除商品|Remove item|移除商品|นำสินค้าออก',
  'cartDraftEmpty': '尚未选择商品|No items selected|尚未選擇商品|ยังไม่ได้เลือกสินค้า',
  'cartSubmit': '下单|Place order|下單|สั่งซื้อ',
  'cartConfirmOrder': '确认点单|Confirm order|確認點單|ยืนยันสั่งซื้อ',
  'billSettled': '已结账|Settled|已結帳|ชำระแล้ว',
  'cartRecording': '正在记单|Recording|正在記單|กำลังบันทึก',
  'cartConfirmNotice': '先付款订单付款时确认库存，售罄不收款；后付款按实际出酒扣库存。选择会员不会扣余额。|Prepay stock is confirmed at payment; sold-out items are not charged. Postpay stock is deducted when issued. Selecting a member does not debit their balance.|先付款訂單付款時確認庫存，售罄不收款；後付款按實際出酒扣庫存。選擇會員不會扣餘額。|คำสั่งซื้อแบบจ่ายก่อนตรวจสต็อกเมื่อชำระเงิน สินค้าหมดจะไม่เรียกเก็บเงิน แบบจ่ายทีหลังตัดสต็อกเมื่อส่งสินค้า การเลือกสมาชิกไม่หักยอดเงิน',
  'cartRefreshing': '正在核对商品，已选内容已保留。|Checking items; your selection is retained.|正在核對商品，已選內容已保留。|กำลังตรวจสอบสินค้า โดยเก็บรายการที่เลือกไว้',
  'cartRefreshFailed': '暂不能下单，已保留所选商品。请重试核对；如商品或入座信息已变更，请返回调整。|Cannot submit yet. Selection retained. Retry checking, or go back if items or seating changed.|暫不能下單，已保留所選商品。請重試核對；如商品或入座資訊已變更，請返回調整。|ยังส่งรายการไม่ได้ เก็บสินค้าที่เลือกไว้แล้ว ลองตรวจสอบอีกครั้ง หรือกลับไปแก้ไขหากสินค้าหรือที่นั่งเปลี่ยน',
  'cartRefreshRetry': '重新核对|Check again|重新核對|ตรวจสอบอีกครั้ง',
  'cartStale': '场次或会话已变化，请返回重新选择会员和商品。|Context changed. Return and select the member and items again.|場次或會話已變化，請返回重新選擇會員和商品。|บริบทเปลี่ยนแล้ว โปรดกลับไปเลือกสมาชิกและสินค้าใหม่',
  'cartPending': '本桌已有待确认原请求，请先查回，勿重复下单。|This table has an unresolved request. Look it up before placing another order.|本桌已有待確認原請求，請先查回，勿重複下單。|โต๊ะนี้มีคำขอที่ยังไม่ยืนยัน โปรดตรวจสอบก่อนสั่งซื้ออีกครั้ง',
  'cartLimit': '无法增加：库存不足、超出数量／金额限制或商品版本变化；请核对或移除后重新选择。|Cannot add: stock, quantity or amount limit, or changed product version. Review or remove and select again.|無法增加：庫存不足、超出數量／金額限制或商品版本變化；請核對或移除後重新選擇。|เพิ่มไม่ได้ สต็อกไม่พอ เกินจำนวนหรือยอดเงิน หรือสินค้าเปลี่ยนเวอร์ชัน โปรดตรวจสอบหรือลบแล้วเลือกใหม่',
  'orderRecoveryTitle':
      '待确认订单请求|Pending order requests|待確認訂單請求|คำขอสั่งซื้อที่รอยืนยัน',
  'orderRecoveryNotice': '仅处理当前员工在本设备保存的原请求。查回不重新下单；记录金额不是付款凭证。|Original requests saved for this employee on this device only. Lookup does not resubmit; the amount is not proof of payment.|僅處理目前員工在本裝置儲存的原請求。查回不重新下單；記錄金額不是付款憑證。|เฉพาะคำขอเดิมของพนักงานนี้ที่บันทึกในอุปกรณ์นี้ การตรวจสอบไม่ส่งคำสั่งซื้อซ้ำ ยอดเงินไม่ใช่หลักฐานการชำระเงิน',
  'orderRecoveryRetry': '查回并重试原订单|Look up and retry original order|查回並重試原訂單|ตรวจสอบและลองคำสั่งซื้อเดิมอีกครั้ง',
  'orderRecoveryCancel':
      '终止原下单请求|Terminate original request|終止原下單請求|ยุติคำขอสั่งซื้อเดิม',
  'orderRecoveryConfirm': '按原商品、数量和价格重试。先付款下单不占库存，后付款出酒扣库存。终止仅停止尚未成单的请求，不退单、不退款。|Retry with the original items, quantities and prices. Prepay orders do not reserve stock; postpay issues deduct stock. Termination only stops an unsubmitted request, without cancelling or refunding an existing order.|按原商品、數量和價格重試。先付款下單不占庫存，後付款出酒扣庫存。終止僅停止尚未成單的請求，不退單、不退款。|ลองใหม่ด้วยสินค้า จำนวน และราคาเดิม แบบจ่ายก่อนไม่จองสต็อกตอนสั่ง แบบจ่ายทีหลังตัดสต็อกเมื่อส่งสินค้า การยุติหยุดเฉพาะคำขอที่ยังไม่เป็นคำสั่งซื้อ ไม่ยกเลิกหรือคืนเงินคำสั่งซื้อเดิม',
  'orderRecoveryConfirmed': '原请求已成单，不代表已付款。请返回桌台查看订单。|Original order confirmed, not payment. Return to the table to view orders.|原請求已成單，不代表已付款。請返回桌檯查看訂單。|ยืนยันคำสั่งซื้อเดิมแล้ว ไม่ใช่การยืนยันชำระเงิน กลับไปดูคำสั่งซื้อที่โต๊ะ',
  'orderRecoveryCancelled': '原下单请求已终止，不代表退单或退款。|Original request terminated, not an order cancellation or refund.|原下單請求已終止，不代表退單或退款。|ยุติคำขอเดิมแล้ว ไม่ใช่การยกเลิกคำสั่งซื้อหรือคืนเงิน',
  'orderRecoveryUnknown': '仍未确认原请求结果，不要另建重复订单。|Original result is not confirmed. Do not create a duplicate order.|仍未確認原請求結果，不要另建重複訂單。|ยังไม่ยืนยันผลคำขอเดิม อย่าสร้างคำสั่งซื้อซ้ำ',
  'orderRecoveryUnconfirmed': '本次未能确认结果，原请求保留待查。|Result could not be confirmed. Keep the original request for lookup.|本次未能確認結果，原請求保留待查。|ยังยืนยันผลไม่ได้ เก็บคำขอเดิมไว้ตรวจสอบ',
  'orderRecoveryFailed': '无法读取待确认记录，请重试；不会清除记录。|Unable to read pending records. Retry; records will not be cleared.|無法讀取待確認記錄，請重試；不會清除記錄。|อ่านรายการที่รอยืนยันไม่ได้ โปรดลองใหม่ ระบบจะไม่ลบบันทึก',
  'orderRecoveryEmpty': '本设备当前员工暂无待确认订单请求。|No pending requests for this employee on this device.|本裝置目前員工暫無待確認訂單請求。|ไม่มีคำขอที่รอยืนยันของพนักงานนี้ในอุปกรณ์นี้',
  'orderMembersTitle': '入座会员|Seated members|入座會員|สมาชิกที่นั่งอยู่',
  'orderMembersNotice': '选择本场次消费会员后进入点单；不代表付款或余额扣款授权。|Select a consumer in this session to order. Selection is not payment or wallet debit consent.|選擇本場次消費會員後進入點單；不代表付款或餘額扣款授權。|เลือกสมาชิกผู้ใช้บริการในรอบนี้เพื่อสั่งซื้อ การเลือกไม่ใช่การอนุมัติชำระเงินหรือหักยอดเงิน',
  'orderMembersEmpty': '本页暂无入座会员；人数不等于会员入座记录。|No seated members on this page. Guest count is not a membership record.|本頁暫無入座會員；人數不等於會員入座記錄。|ไม่มีสมาชิกที่นั่งในหน้านี้ จำนวนคนไม่ใช่บันทึกสมาชิก',
  'orderMembersFailed': '无法确认当前场次或会员，请刷新或返回桌台。|Unable to confirm this session or its members. Refresh or return to tables.|無法確認目前場次或會員，請重新整理或返回桌檯。|ยืนยันรอบหรือสมาชิกไม่ได้ โปรดรีเฟรชหรือกลับไปหน้าโต๊ะ',
  'orderMemberUnnamed': '未设置昵称|Nickname not set|未設定暱稱|ยังไม่ได้ตั้งชื่อเล่น',
  'orderMemberIneligible': '当前不可选择|Currently unavailable|目前不可選擇|ยังเลือกไม่ได้',
  'orderMemberSelected': '当前选择（未下单）|Selected (no order placed)|目前選擇（未下單）|เลือกแล้ว (ยังไม่ได้สั่งซื้อ)',
  'catalogTitle': '商品目录|Product catalog|商品目錄|รายการสินค้า',
  'catalogNotice': '仅浏览实时目录，不锁价、不占用库存。员工下单尚未开放。|Catalog observation only; no price lock or stock reservation. Staff ordering is not enabled.|僅瀏覽即時目錄，不鎖價、不佔用庫存。員工下單尚未開放。|ดูรายการเท่านั้น ไม่ล็อกราคาหรือจองสต็อก ยังไม่เปิดให้พนักงานสั่งซื้อ',
  'catalogEmpty': '本页暂无商品|No products on this page|本頁暫無商品|ไม่มีสินค้าในหน้านี้',
  'catalogUnknown': '库存未知|Stock unknown|庫存未知|ไม่ทราบสต็อก',
  'catalogSoldOut': '暂无可售库存|No available stock|暫無可售庫存|ไม่มีสต็อกพร้อมขาย',
  'catalogAvailable': '当前可售数量|Available quantity|目前可售數量|จำนวนพร้อมขาย',
  'openingSubmit': '确认开台|Open table|確認開檯|ยืนยันเปิดโต๊ะ',
  'openingPending': '待确认开台请求|Pending openings|待確認開檯請求|คำขอเปิดโต๊ะที่รอยืนยัน',
  'openingRefresh': '刷新开台信息|Refresh opening info|重新整理開檯資訊|รีเฟรชข้อมูลเปิดโต๊ะ',
  'openingNotice': '开台由服务器确认，不代表付款成功。人数不自动绑定会员；AA 必须核对真实入座会员。|Opening is server-confirmed, not payment. Guest count does not link members; AA requires verified seated members.|開檯由伺服器確認，不代表付款成功。人數不自動綁定會員；AA 必須核對真實入座會員。|เซิร์ฟเวอร์ยืนยันการเปิดโต๊ะ ไม่ใช่การชำระเงิน จำนวนคนไม่เชื่อมสมาชิกอัตโนมัติ AA ต้องตรวจสอบสมาชิกที่นั่งจริง',
  'openingConfirmNotice': '请核对桌台与原请求。重试沿用原参数；终止不关闭已经开出的场次。|Check the table and original request. Retry keeps original details; termination does not close an existing session.|請核對桌檯與原請求。重試沿用原參數；終止不關閉已開出的場次。|ตรวจสอบโต๊ะและคำขอเดิม การลองใหม่ใช้ข้อมูลเดิม การยุติไม่ปิดรอบที่เปิดแล้ว',
  'openingConfirmed': '原请求已确认开台，请返回桌台查看当前场次。|Opening confirmed. Return to tables to check the current session.|原請求已確認開檯，請返回桌檯查看目前場次。|ยืนยันเปิดโต๊ะแล้ว กลับไปตรวจสอบรอบปัจจุบันที่หน้าโต๊ะ',
  'openingCancelled': '原请求已永久终止；准备新请求前请刷新开台信息。|Original request terminated. Refresh opening info before a new request.|原請求已永久終止；準備新請求前請重新整理開檯資訊。|ยุติคำขอเดิมแล้ว รีเฟรชข้อมูลก่อนสร้างคำขอใหม่',
  'openingUnknown': '尚未确认结果，不代表开台失败。请先查询原请求。|Result unconfirmed, not proof of failure. Query the original request first.|尚未確認結果，不代表開檯失敗。請先查詢原請求。|ยังไม่ยืนยันผล ไม่ได้หมายความว่าเปิดโต๊ะล้มเหลว โปรดตรวจสอบคำขอเดิมก่อน',
  'openingUnconfirmed': '本次操作未能确认结果。保留待确认记录，请查询原请求，勿重复新开台。|Result could not be confirmed. Keep pending records and query the original request; do not create another opening.|本次操作未能確認結果。保留待確認記錄，請查詢原請求，勿重複新開檯。|ยืนยันผลไม่ได้ เก็บคำขอที่รอไว้และตรวจสอบคำขอเดิม อย่าเปิดโต๊ะซ้ำ',
  'openingReadFailed': '读取未完成，请检查连接及员工权限后刷新。旧规则不可用于提交。|Read incomplete. Check connection and staff access, then refresh. Old rules cannot be submitted.|讀取未完成，請檢查連線及員工權限後重新整理。舊規則不可用於提交。|อ่านข้อมูลไม่ครบ ตรวจสอบเครือข่ายและสิทธิ์แล้วรีเฟรช ห้ามส่งด้วยกฎเก่า',
  'billAllConsumption': '全部消费|All items|全部消費|ทั้งหมด',
  'billDone': '完成|Done|完成|เสร็จ',
  'billAddOrder': '加单|Add more|加單|สั่งเพิ่ม',
  'billAddUnavailable': '商品当前不可加单，请刷新菜单后重试。|Product cannot be added now. Refresh the menu and retry.|商品目前不可加單，請重新整理菜單後重試。|ไม่สามารถเพิ่มสินค้านี้ได้ กรุณาโหลดเมนูใหม่',
  'billFirstSync': '正在同步本台消费|Syncing this table|正在同步本檯消費|กำลังซิงค์รายการโต๊ะ',
  'billSyncing': '后台核对中|Checking for updates|背景核對中|กำลังตรวจสอบข้อมูล',
  'billMixedPrices': '含不同成交单价|Multiple unit prices|含不同成交單價|มีหลายราคาต่อหน่วย',
  'billChooseOriginal': '选择原加单记录|Choose original order|選擇原加單記錄|เลือกรายการเดิม',
  'billItemQuantity': '数量|Quantity|數量|จำนวน',
  'billSubmittedQuantityUnavailable': '增加数量请加单；已提交数量暂不支持直接减少。|Use Add more to increase quantity. Submitted quantities cannot be reduced directly yet.|增加數量請加單；已提交數量暫不支援直接減少。|เพิ่มจำนวนด้วยการสั่งเพิ่ม ยังลดรายการที่ส่งแล้วไม่ได้',
  'billServedReturnOnly': '已上的商品不能直接减少，只能退货处理。|Served items require a return; quantity cannot be reduced directly.|已上的商品不能直接減少，只能退貨處理。|สินค้าที่เสิร์ฟแล้วต้องทำรายการคืน',
  'billReturnUnavailable': '此订单的退货入口暂未接通。|Returns are not available for this order yet.|此訂單的退貨入口暫未接通。|ยังไม่รองรับการคืนสำหรับรายการนี้',
  'billReturnOrderScope': '进入原订单退货流程，将核对订单内全部商品，不会只凭此卡片直接退款。|Opens the original order return review for all its items.|進入原訂單退貨流程，將核對全部商品。|ตรวจสอบสินค้าทั้งคำสั่งซื้อก่อนคืน',
  'billReturnAction': '退货处理|Review return|退貨處理|ตรวจสอบการคืน',
  'billVoucher': '核券|Vouchers|核券|คูปอง',
  'billGift': '赠送|Gifts|贈送|ของแถม',
  'billAllUnserved': '全部未上|Unserved|全部未上|ยังไม่เสิร์ฟ',
  'billPartUnserved': '部分未上|Part served|部分未上|เสิร์ฟบางส่วน',
  'billSourceUnavailable': '当前账单接口尚未提供此分类，暂不能查询。|This category is not yet available from the bill service.|目前帳單介面尚未提供此分類，暫不能查詢。|บริการยังไม่รองรับหมวดนี้',
  'billPartyUnavailable': '当前人数来自服务器。员工修改人数接口尚未接通，暂不能在收银端保存修改。|Guest count comes from the server. Staff count editing is not connected yet.|目前人數來自伺服器，員工修改人數介面尚未接通。|ยังไม่รองรับการแก้จำนวนคนโดยพนักงาน',
  'billOpeningAttribute': '开台属性|Opening rule|開檯屬性|กฎเปิดโต๊ะ',
  'billRuleUnavailable': '当前接口未返回本次开台的规则快照，暂显示已开台。|The opening rule snapshot is not supplied yet.|目前介面未回傳本次開檯規則，暫顯示已開檯。|ยังไม่มีข้อมูลกฎของรอบนี้',
  'openingRule': '今日开台规则|Daily opening rule|今日開檯規則|กฎเปิดโต๊ะวันนี้',
  'openingRevision': '版本|Revision|版本|เวอร์ชัน',
  'openingRule_manual': '人工确认|Staff confirmation|人工確認|พนักงานยืนยัน',
  'openingRule_aa': 'AA 会员开台|AA member opening|AA 會員開檯|เปิดโต๊ะสมาชิก AA',
  'openingRule_minimum_people': '最低人数|Minimum guests|最低人數|จำนวนคนขั้นต่ำ',
  'openingRule_minimum_spend': '最低消费|Minimum spend|最低消費|ยอดใช้จ่ายขั้นต่ำ',
  'openingDefaultRule': '未配置专门规则，服务端使用默认人工规则。|No custom rule; server uses the manual default.|未設定專門規則，伺服器使用預設人工規則。|ยังไม่ตั้งกฎเฉพาะ เซิร์ฟเวอร์ใช้กฎพนักงานยืนยันเริ่มต้น',
  'openingMinimumPeople': '要求人数|Required guests|要求人數|จำนวนคนที่กำหนด',
  'openingMinimumSpend': '最低消费（门店货币）|Minimum spend (store currency)|最低消費（門店貨幣）|ยอดขั้นต่ำ (สกุลเงินร้าน)',
  'openingDisabled': '服务器暂未开放开台提交。|Server opening submissions are disabled.|伺服器暫未開放開檯提交。|เซิร์ฟเวอร์ยังไม่เปิดรับคำขอเปิดโต๊ะ',
  'openingOccupied': '已有营业场次，不能再次开台。|An active session already exists.|已有營業場次，不能再次開檯。|มีรอบใช้งานอยู่แล้ว เปิดซ้ำไม่ได้',
  'openingAaUnavailable': 'AA 入座会员选择尚未接入，请勿以空会员清单开台。|AA member selection is not connected. Do not open with an empty member list.|AA 入座會員選擇尚未接入，請勿以空會員清單開檯。|ยังไม่เชื่อมการเลือกสมาชิก AA ห้ามเปิดด้วยรายชื่อว่าง',
  'openingArrival': '我已确认客人到店及桌台归属|I verified arrival and the correct table|我已確認客人到店及桌檯歸屬|ตรวจสอบลูกค้ามาถึงและโต๊ะถูกต้องแล้ว',
  'openingReservation': '我已人工核对预约，无占用冲突（系统未自动核验）|I checked reservations and conflicts manually (not automatically verified)|我已人工核對預約，無佔用衝突（系統未自動核驗）|ตรวจสอบการจองและความขัดแย้งด้วยตนเองแล้ว (ระบบยังไม่ตรวจอัตโนมัติ)',
  'openingNoPending': '当前员工没有待确认开台请求。|No pending opening requests for this employee.|目前員工沒有待確認開檯請求。|พนักงานนี้ไม่มีคำขอเปิดโต๊ะที่รอยืนยัน',
  'openingRequest': '原请求号|Original request ID|原請求號|รหัสคำขอเดิม',
  'openingQuery': '查询原结果|Query original result|查詢原結果|ตรวจสอบผลเดิม',
  'openingRetry': '重试原请求|Retry original request|重試原請求|ลองคำขอเดิมอีกครั้ง',
  'openingCancel': '终止原请求|Terminate original request|終止原請求|ยุติคำขอเดิม',
  'orderOperations': '出酒 / 退款 / 小票|Serve / refund / receipt|出酒 / 退款 / 小票|เสิร์ฟ / คืนเงิน / ใบเสร็จ',
  'ordersDetails': '消费明细|Order details|消費明細|รายละเอียดรายการ',
  'ordersBack': '返回桌台|Back to tables|返回桌檯|กลับไปที่โต๊ะ',
  'ordersRefresh': '刷新明细|Refresh orders|重新整理明細|รีเฟรชรายการ',
  'ordersEmpty':
      '本场次暂无订单|No orders in this session|本場次暫無訂單|ยังไม่มีรายการในรอบนี้',
  'ordersReadOnly': '只读成交明细 · 不代表最终结账金额；付款和核销尚未开放。|Read-only order details · Not a final bill. Payment and redemption are not available.|唯讀成交明細 · 不代表最終結帳金額；付款和核銷尚未開放。|รายละเอียดแบบอ่านอย่างเดียว ไม่ใช่ยอดบิลสุดท้าย ยังไม่เปิดชำระเงินหรือใช้คูปอง',
  'order_pending': '待付款|Pending payment|待付款|รอชำระเงิน',
  'order_paid': '已付款|Paid|已付款|ชำระแล้ว',
  'order_expired': '已失效|Expired|已失效|หมดอายุ',
  'liveRealtimeReadOnly': '只读桌台快照 · 收到门店变更提示后重新查询；通知不代表付款或核销成功。|Read-only snapshot · Store change hints trigger a new query, not payment or redemption confirmation.|唯讀桌檯快照 · 收到門店變更提示後重新查詢；通知不代表付款或核銷成功。|ข้อมูลโต๊ะแบบอ่านอย่างเดียว · แจ้งการเปลี่ยนแปลงแล้วจึงอ่านใหม่ ไม่ใช่การยืนยันชำระเงินหรือใช้คูปอง',
  'realtimeOffline': '实时通道未连接，可手动刷新|Realtime disconnected; manual refresh available|即時通道未連線，可手動重新整理|ช่องทางอัปเดตขาดการเชื่อมต่อ รีเฟรชด้วยตนเองได้',
  'realtimeConnecting': '正在连接门店实时通道…|Connecting to store updates…|正在連接門店即時通道…|กำลังเชื่อมต่อการอัปเดตร้าน…',
  'realtimeConnected': '门店实时通道已连接|Store update channel connected|門店即時通道已連線|เชื่อมต่อช่องทางอัปเดตร้านแล้ว',
  'tableDisabled': '停用桌台|Disabled table|停用桌檯|โต๊ะปิดใช้งาน',
  'tableOpen': '已开台|Open session|已開檯|เปิดโต๊ะแล้ว',
  'tableTemporaryHold': '临时占座|Temporary hold|臨時佔座|จองโต๊ะชั่วคราว',
  'liveRefresh': '刷新桌台|Refresh tables|重新整理桌檯|รีเฟรชโต๊ะ',
  'liveReadOnly': '只读桌台快照 · 尚未接入实时推送，请手动刷新；未付款订单合计不等于最终结账金额。|Read-only snapshot · No live updates yet; refresh manually. Pending orders are not the final bill.|唯讀桌檯快照 · 尚未接入即時推送，請手動重新整理；未付款訂單合計不等於最終結帳金額。|ข้อมูลโต๊ะ ณ เวลาที่อ่าน · ยังไม่อัปเดตอัตโนมัติ โปรดรีเฟรช ยอดคำสั่งซื้อค้างชำระไม่ใช่ยอดบิลสุดท้าย',
  'liveObserved': '本页查询时间|Page observed at|本頁查詢時間|เวลาข้อมูลหน้านี้',
  'liveBusinessDate': '营业日|Business date|營業日|วันที่ดำเนินธุรกิจ',
  'liveReadFailed': '桌台读取失败，已清除旧显示。请检查连接或门店权限后刷新。|Unable to read tables; old display cleared. Check connection or store access and refresh.|桌檯讀取失敗，已清除舊顯示。請檢查連線或門店權限後重新整理。|อ่านโต๊ะไม่สำเร็จ ล้างข้อมูลเดิมแล้ว โปรดตรวจสอบการเชื่อมต่อหรือสิทธิ์ร้านและรีเฟรช',
  'liveNoTables': '服务器返回本页无桌台|No tables returned for this page|伺服器回傳本頁無桌檯|เซิร์ฟเวอร์ไม่ส่งโต๊ะในหน้านี้',
  'livePrevious': '上一页|Previous|上一頁|ก่อนหน้า',
  'liveNext': '下一页|Next|下一頁|ถัดไป',
  'livePage': '页码|Page|頁碼|หน้า',
  'livePrepay': '先付款|Pay first|先付款|ชำระก่อน',
  'livePostpay': '后付款|Pay later|後付款|ชำระภายหลัง',
  'livePaid':
      '未退款已付合计|Paid total excluding refunds|未退款已付合計|ยอดชำระที่ยังไม่คืนเงิน',
  'livePending': '未付订单合计|Pending order total|未付訂單合計|ยอดคำสั่งซื้อค้างชำระ',
  'liveRefunded': '已退款|Refunded|已退款|คืนเงินแล้ว',
  'grossCollected': '原已付（含后续退款）|Original paid (including later refunds)|原已付（含後續退款）|ยอดชำระเดิม (รวมที่คืนภายหลัง)',
  'refundPrincipal':
      '退回本金／现金|Returned principal / cash|退回本金／現金|คืนเงินต้น / เงินสด',
  'refundGift': '退回原赠送|Returned original gifts|退回原贈送|คืนยอดของแถมเดิม',
  'staffExitPreview': '退出后清空演示草稿，进入员工登录；如本机保存有员工会话，将向服务器验证恢复。|Discard preview drafts and open staff sign-in. A saved staff session will be verified with the server.|退出後清空示範草稿，進入員工登入；如本機儲存有員工工作階段，將向伺服器驗證恢復。|ล้างรายการร่างตัวอย่างและเปิดหน้าล็อกอิน หากมีเซสชันที่บันทึกไว้จะตรวจสอบกับเซิร์ฟเวอร์',
  'staffReconnect': '重新连接|Reconnect|重新連線|เชื่อมต่อใหม่',
  'staffReconnectNotice': '网络暂不可用，恢复网络后点重新连接，无需重新输入密码。|Network unavailable. Reconnect when online; no password needed.|網路暫不可用，恢復網路後點重新連線，無需重新輸入密碼。|เครือข่ายไม่พร้อม เมื่อออนไลน์แล้วให้เชื่อมต่อใหม่โดยไม่ต้องกรอกรหัสผ่าน',
  'staffLogin': '独立员工登录|Staff sign-in|獨立員工登入|เข้าสู่ระบบพนักงาน',
  'staffStore': '门店编号|Store reference|門店編號|รหัสร้าน',
  'staffAccount': '员工账号|Employee account|員工帳號|บัญชีพนักงาน',
  'staffPassword': '员工密码|Employee password|員工密碼|รหัสผ่านพนักงาน',
  'staffSignIn': '登录门店|Sign in to store|登入門店|เข้าสู่ร้าน',
  'staffSignOut': '退出员工会话|Sign out|登出員工工作階段|ออกจากระบบ',
  'staffVerifying': '正在与服务器确认会话…|Verifying session with server…|正在與伺服器確認工作階段…|กำลังตรวจสอบเซสชันกับเซิร์ฟเวอร์…',
  'staffRequired': '请填写此项|This field is required|請填寫此項|กรุณากรอกข้อมูลนี้',
  'staffAuthFailure': '无法确认员工会话，请核对网络、账号及门店授权后重试。|Could not verify staff session. Check network, account and store access.|無法確認員工工作階段，請核對網路、帳號及門店授權後重試。|ยืนยันเซสชันไม่ได้ โปรดตรวจสอบเครือข่าย บัญชีและสิทธิ์ร้าน',
  'staffStorageFailure': '安全存储操作失败，请勿将此设备交给其他员工，先处理设备存储问题。|Secure storage failed. Resolve device storage before handing over this terminal.|安全儲存操作失敗，請勿將此設備交給其他員工，先處理設備儲存問題。|พื้นที่จัดเก็บปลอดภัยขัดข้อง โปรดแก้ไขก่อนส่งมอบเครื่องให้พนักงานอื่น',
  'staffLogoutUnconfirmed': '本机已退出，但服务器撤销尚未确认。请联系管理员核查会话。|Signed out locally; server revocation is unconfirmed. Ask an administrator to check the session.|本機已登出，但伺服器撤銷尚未確認。請聯絡管理員核查工作階段。|ออกจากเครื่องแล้ว แต่ยังไม่ยืนยันการยกเลิกบนเซิร์ฟเวอร์ โปรดแจ้งผู้ดูแล',
  'staffConnected': '员工会话已验证。真实桌台界面仍在接入中；此页不会开台、下单或收款。|Staff session verified. Live tables are still being connected; this page cannot open tables, place orders or take payments.|員工工作階段已驗證。真實桌檯介面仍在接入中；此頁不會開檯、下單或收款。|ยืนยันเซสชันแล้ว กำลังเชื่อมต่อหน้าโต๊ะจริง หน้านี้ไม่เปิดโต๊ะ สั่งซื้อหรือรับชำระเงิน',
  'workbench': '门店工作台|Store workspace|門店工作台|พื้นที่ทำงานร้าน',
  'tables': '桌台|Tables|桌檯|โต๊ะ',
  'ordering': '点单|Menu|點單|เมนู',
  'orders': '订单|Orders|訂單|คำสั่งซื้อ',
  'members': '会员|Members|會員|สมาชิก',
  'reports': '交班报表|Shift reports|交班報表|รายงานกะ',
  'settings': '设置|Settings|設定|ตั้งค่า',
  'preview': '界面演示|UI preview|介面示範|ตัวอย่างหน้าจอ',
  'live': '待接入门店|Store not connected|待接入門店|ยังไม่เชื่อมต่อร้าน',
  'sampleStore': '演示空间 · 非真实门店|Sample space · fictional store|示範空間 · 非真實門店|ร้านตัวอย่าง · ไม่ใช่ร้านจริง',
  'banner': '演示模式 · 桌台、商品、订单均为虚构样例，不会下单或收款|PREVIEW · Fictional data. No orders or payments are submitted.|示範模式 · 桌檯、商品、訂單均為虛構樣例，不會下單或收款|ตัวอย่าง · ข้อมูลสมมติ ไม่มีการสั่งซื้อหรือรับชำระเงิน',
  'liveBanner': '尚未建立员工会话 · 不显示演示营业数据|No staff session · No sample trading data|尚未建立員工工作階段 · 不顯示示範營業資料|ยังไม่มีเซสชันพนักงาน · ไม่แสดงข้อมูลตัวอย่าง',
  'all': '全部|All|全部|ทั้งหมด',
  'hall': '大厅|Hall|大廳|โถง',
  'booth': '卡座|Booths|卡座|ที่นั่งส่วนตัว',
  'free': '空台|Available|空檯|ว่าง',
  'taking': '点单中|Ordering|點單中|กำลังสั่ง',
  'unpaid': '待结账|Unpaid|待結帳|รอชำระ',
  'cleaning': '待清台|To clear|待清檯|รอเก็บโต๊ะ',
  'searchTable': '搜索桌号|Search tables|搜尋桌號|ค้นหาโต๊ะ',
  'overview': '桌台总览|Table overview|桌檯總覽|ภาพรวมโต๊ะ',
  'selectTable': '请选择桌台|Select a table|請選擇桌檯|เลือกโต๊ะ',
  'selectHint': '查看当前状态，或创建本桌点单草稿|View status or prepare a local draft|查看目前狀態，或建立本檯點單草稿|ดูสถานะหรือเตรียมรายการร่าง',
  'guests': '人数|Guests|人數|จำนวนคน',
  'elapsed': '已用分钟|Minutes|已用分鐘|นาที',
  'currentBill': '场次待付（样例）|Session due (sample)|場次待付（樣例）|ยอดค้าง (ตัวอย่าง)',
  'draft': '本桌草稿|Table draft|本檯草稿|รายการร่างของโต๊ะ',
  'localOnly': '仅存本次运行内存，退出应用不保留|Memory only; lost when the app closes|僅存本次執行記憶體，退出應用不保留|เก็บในหน่วยความจำ ปิดแอปแล้วข้อมูลหาย',
  'startDraft': '进入点单|Open menu|進入點單|เปิดเมนู',
  'tableActions': '开台 / 清台|Open / clear table|開檯 / 清檯|เปิด / เก็บโต๊ะ',
  'notConnected': '接口尚未接入|Not connected yet|介面尚未接入|ยังไม่เชื่อมต่อ',
  'blocked': '员工授权与经营接口尚未接入，没有执行任何业务操作。|Staff authorization and trading APIs are not connected. No business action was performed.|員工授權與經營介面尚未接入，沒有執行任何業務操作。|ยังไม่เชื่อมต่อสิทธิ์พนักงานและ API ไม่มีการดำเนินการทางธุรกิจ',
  'emptyLive': '连接门店后查看实时桌台|Connect your store to see tables|連接門店後查看即時桌檯|เชื่อมต่อร้านเพื่อดูโต๊ะ',
  'authHint': '需要收银员工授权；不会使用手机会员会话或自动授予权限。|A cashier staff session is required. Mobile sessions and permissions are not reused.|需要收銀員工授權；不會使用手機會員工作階段或自動授予權限。|ต้องมีสิทธิ์แคชเชียร์ ไม่ใช้เซสชันสมาชิกในมือถือ',
  'enterPreview': '体验界面演示|Try UI preview|體驗介面示範|ลองหน้าจอตัวอย่าง',
  'leavePreview': '退出演示|Exit preview|退出示範|ออกจากตัวอย่าง',
  'previewConfirm': '载入虚构样例，仅用于界面体验。切换模式会清空本地草稿，不会连接经营接口。|Load fictional UI samples. Switching modes clears drafts. No trading APIs will be called.|載入虛構樣例，僅用於介面體驗。切換模式會清空本地草稿，不會連接經營介面。|โหลดข้อมูลสมมติ การสลับโหมดจะล้างรายการร่าง ไม่เรียก API ธุรกิจ',
  'cancel': '取消|Cancel|取消|ยกเลิก',
  'confirm': '确认|Confirm|確認|ยืนยัน',
  'back': '返回桌台|Back to tables|返回桌檯|กลับไปโต๊ะ',
  'searchProduct': '搜索商品名称|Search products|搜尋商品名稱|ค้นหาสินค้า',
  'beer': '啤酒|Beer|啤酒|เบียร์',
  'spirits': '烈酒|Spirits|烈酒|สุรา',
  'soft': '软饮|Soft drinks|軟飲|เครื่องดื่ม',
  'snacks': '小食|Snacks|小食|อาหารว่าง',
  'sets': '套餐|Sets|套餐|ชุด',
  'lager': '清爽拉格（样例）|Lager (sample)|清爽拉格（樣例）|ลาเกอร์ (ตัวอย่าง)',
  'wheat': '小麦白啤（样例）|Wheat beer (sample)|小麥白啤（樣例）|วีทเบียร์ (ตัวอย่าง)',
  'ipa': '精酿 IPA（样例）|Craft IPA (sample)|精釀 IPA（樣例）|คราฟต์ IPA (ตัวอย่าง)',
  'whisky': '橡木威士忌（样例）|Whisky (sample)|橡木威士忌（樣例）|วิสกี้ (ตัวอย่าง)',
  'gin': '花香金酒（样例）|Gin (sample)|花香琴酒（樣例）|จิน (ตัวอย่าง)',
  'soda': '气泡水（样例）|Soda (sample)|氣泡水（樣例）|โซดา (ตัวอย่าง)',
  'juice': '鲜橙汁（样例）|Orange juice (sample)|鮮橙汁（樣例）|น้ำส้ม (ตัวอย่าง)',
  'water': '矿泉水（样例）|Water (sample)|礦泉水（樣例）|น้ำแร่ (ตัวอย่าง)',
  'fries': '香脆薯条（样例）|Fries (sample)|香脆薯條（樣例）|เฟรนช์ฟรายส์ (ตัวอย่าง)',
  'nuts': '混合坚果（样例）|Mixed nuts (sample)|混合堅果（樣例）|ถั่วรวม (ตัวอย่าง)',
  'fruit': '时令果盘（样例）|Fruit plate (sample)|時令果盤（樣例）|ผลไม้รวม (ตัวอย่าง)',
  'sharing': '轻聚分享套餐（样例）|Sharing set (sample)|輕聚分享套餐（樣例）|ชุดแบ่งปัน (ตัวอย่าง)',
  'bottle': '单瓶|Bottle|單瓶|ขวด',
  'six': '六瓶装|6 bottles|六瓶裝|6 ขวด',
  'glass': '单杯|Glass|單杯|แก้ว',
  'plate': '一份|Plate|一份|จาน',
  'set': '一套|Set|一套|ชุด',
  'postpayStockUnavailable': '剩余商品库存不足，未发起扣款，已出酒账单保留|Remaining items are out of stock. No charge initiated; delivered items remain on the bill.|剩餘商品庫存不足，未發起扣款，已出酒帳單保留|สินค้าที่เหลือไม่พอ ยังไม่เรียกเก็บเงิน รายการที่เสิร์ฟแล้วยังคงอยู่ในบิล',
  'postpayCashStockUnavailable': '剩余商品库存不足；如已收现金请先退回，原消费账单保留|Remaining items are out of stock. Return any cash collected; the original bill remains.|剩餘商品庫存不足；如已收現金請先退回，原消費帳單保留|สินค้าที่เหลือไม่พอ หากรับเงินสดแล้วให้คืนก่อน บิลเดิมยังคงอยู่',
  'soldOut': '已售罄|Sold out|已售罄|หมด',
  'variants': '选择规格|Choose an option|選擇規格|เลือกขนาด',
  'add': '加入草稿|Add to draft|加入草稿|เพิ่มในรายการร่าง',
  'cartEmpty': '从右侧选择商品|Choose items on the right|從右側選擇商品|เลือกสินค้าด้านขวา',
  'clear': '清空草稿|Clear draft|清空草稿|ล้างรายการร่าง',
  'clearConfirm': '清空本桌未提交的商品和备注？不会修改服务端订单。|Clear this draft and note? Server orders will not change.|清空本檯未提交的商品和備註？不會修改伺服器訂單。|ล้างรายการร่างและหมายเหตุ? ไม่เปลี่ยนคำสั่งซื้อจริง',
  'note': '订单备注|Draft note|訂單備註|หมายเหตุ',
  'total': '草稿合计|Draft total|草稿合計|รวมรายการร่าง',
  'items': '件|items|件|รายการ',
  'checkout': '核对结账|Review checkout|核對結帳|ตรวจสอบยอด',
  'checkoutHint': '草稿估算，不是服务端应收账单。优惠、库存及应付金额需后台确认。|Draft estimate, not a server bill. Discounts, stock and amounts require server confirmation.|草稿估算，不是伺服器應收帳單。優惠、庫存及應付金額需後台確認。|ยอดประมาณการ ไม่ใช่ใบเรียกเก็บจริง ต้องยืนยันจากเซิร์ฟเวอร์',
  'paymentDisabled': '未接入收款 · 不可支付|Payment not connected|未接入收款 · 不可支付|ยังไม่เชื่อมต่อการชำระเงิน',
  'paid': '已结账|Paid|已結帳|ชำระแล้ว',
  'sampleOrders': '样例订单 · 非实时营业记录|Sample orders · not live records|樣例訂單 · 非即時營業記錄|คำสั่งซื้อตัวอย่าง · ไม่ใช่ข้อมูลจริง',
  'orderDetails': '订单详情|Order details|訂單詳情|รายละเอียดคำสั่งซื้อ',
  'orderId': '订单编号|Order ID|訂單編號|รหัสคำสั่งซื้อ',
  'amount': '订单金额|Order amount|訂單金額|ยอดคำสั่งซื้อ',
  'source': '订单来源|Source|訂單來源|ที่มา',
  'sampleSource': '内置演示样例|Built-in preview fixture|內建示範樣例|ข้อมูลตัวอย่างในแอป',
  'print': '打印小票|Print receipt|列印收據|พิมพ์ใบเสร็จ',
  'noResults': '没有匹配内容|No matches|沒有符合內容|ไม่พบข้อมูล',
  'pendingModule': '此模块等待真实接口接入|This module needs live APIs|此模組等待真實介面接入|โมดูลนี้รอเชื่อมต่อ API',
  'memberHint': '会员和资产需独立授权，不生成示例会员隐私。|Members and assets require authorization. No fictional personal records.|會員和資產需獨立授權，不產生示例會員隱私。|สมาชิกและสินทรัพย์ต้องมีสิทธิ์ ไม่สร้างข้อมูลส่วนบุคคล',
  'reportHint': '交班、现金、收款统计以后台账务为准，不显示虚构营业额。|Shift and payment reports need server accounting. No fictional revenue shown.|交班、現金、收款統計以後台帳務為準，不顯示虛構營業額。|รายงานกะและเงินต้องมาจากบัญชีเซิร์ฟเวอร์ ไม่แสดงรายได้สมมติ',
  'connection': '服务连接|Service connection|服務連接|การเชื่อมต่อ',
  'connectionHint': '检查统一服务的 /ready；健康不代表已登录或有门店权限。|Check /ready. Readiness is not login or store authorization.|檢查統一服務的 /ready；健康不代表已登入或有門店權限。|ตรวจสอบ /ready ไม่ได้หมายถึงเข้าสู่ระบบหรือมีสิทธิ์ร้าน',
  'endpoint': '服务地址（HTTPS）|Service URL (HTTPS)|服務位址（HTTPS）|URL บริการ (HTTPS)',
  'check': '检查连接|Check connection|檢查連接|ตรวจสอบการเชื่อมต่อ',
  'checking': '正在检查…|Checking…|正在檢查…|กำลังตรวจสอบ…',
  'ready': '服务就绪 · 尚未登录|Service ready · not signed in|服務就緒 · 尚未登入|บริการพร้อม · ยังไม่เข้าสู่ระบบ',
  'failed': '检查未通过，请核对网络及服务地址|Check failed. Verify network and URL.|檢查未通過，請核對網路及服務位址|ตรวจสอบไม่สำเร็จ โปรดตรวจเครือข่ายและ URL',
  'invalidUrl': '请输入无账号、参数或片段的 HTTPS 地址|Enter HTTPS URL without credentials, query or fragment|請輸入無帳號、參數或片段的 HTTPS 位址|กรอก HTTPS URL ที่ไม่มีบัญชี พารามิเตอร์หรือ fragment',
  'previewNetwork': '演示不访问网络，请先退出演示|Exit preview to check a service|示範不存取網路，請先退出示範|ออกจากตัวอย่างก่อนตรวจสอบบริการ',
  'language': '界面语言|Language|介面語言|ภาษา',
  'device': '目标设备|Target device|目標裝置|อุปกรณ์เป้าหมาย',
  'landscape':
      '请横屏使用收银工作台|Use the cashier in landscape|請橫向使用收銀工作台|โปรดใช้ในแนวนอน',
  'save': '保存草稿备注|Save draft note|儲存草稿備註|บันทึกหมายเหตุร่าง',
};
