enum UiLanguage { zh, en, tw, th }

String tr(UiLanguage language, String key) {
  assert(copy.containsKey(key), 'Missing translation: $key');
  return copy[key]?.split('|')[language.index] ?? key;
}

const copy = <String, String>{
  'cashPrepare': '准备现金收款|Prepare cash payment|準備現金收款|เตรียมรับเงินสด',
  'cashPrepareCancel': '暂不收款|Not now|暫不收款|ยังไม่รับเงิน',
  'cashPrepareNotice': '仅准备本笔订单的现金请求，不代表已收款。准备后先查询状态，再核对实际收妥金额。异常时处理原请求，不重复创建。|Prepare a cash request for this order only; this does not mark it paid. Then look up its state and review cash actually received. Recover the original request after an error; do not create another.|僅準備本筆訂單的現金請求，不代表已收款。準備後先查詢狀態，再核對實際收妥金額。異常時處理原請求，不重複建立。|สร้างคำขอเงินสดสำหรับคำสั่งซื้อนี้เท่านั้น ยังไม่ถือว่าชำระแล้ว ตรวจสอบสถานะและยอดเงินที่รับจริง หากผิดพลาดให้กู้คืนคำขอเดิม ไม่สร้างซ้ำ',
  'ordersSnapshotNotice': '订单明细不是整桌结账单。现金入口仅适用于获授权的员工订单，结果以服务端确认为准。|These orders are not a whole-table bill. Cash preparation is limited to authorized staff orders; the server confirms the outcome.|訂單明細不是整桌結帳單。現金入口僅適用於獲授權的員工訂單，結果以服務端確認為準。|รายการนี้ไม่ใช่บิลรวมทั้งโต๊ะ รับเงินสดได้เฉพาะคำสั่งซื้อของพนักงานที่มีสิทธิ์ ผลยืนยันจากเซิร์ฟเวอร์',
  'cashRecoveryTitle': '现金请求处理|Cash request recovery|現金請求處理|จัดการคำขอเงินสด',
  'cashRecoveryNotice': '只处理当前员工在本设备保存的原请求。先查回状态；请求金额不是付款凭证。|Original requests saved for this employee on this device. Look up first; amounts are not payment evidence.|只處理目前員工在本裝置儲存的原請求。先查回狀態；請求金額不是付款憑證。|จัดการเฉพาะคำขอเดิมของพนักงานนี้บนอุปกรณ์นี้ ตรวจสอบก่อน ยอดเงินไม่ใช่หลักฐานการชำระเงิน',
  'cashConfirm': '核对现金收妥|Review cash received|核對現金收妥|ตรวจสอบเงินสดที่รับ',
  'cashClose': '终止未收款意图|Close uncollected cash intent|終止未收款意圖|ยุติรายการที่ยังไม่ได้รับเงินสด',
  'cashRetry': '查回并重试原准备请求|Look up and retry original preparation|查回並重試原準備請求|ตรวจสอบและลองเตรียมคำขอเดิมอีกครั้ง',
  'cashDue': '应收|Amount due|應收|ยอดที่ต้องชำระ',
  'cashReceived': '实收现金|Cash received|實收現金|เงินสดที่รับ',
  'cashChange': '应找零|Change due|應找零|เงินทอน',
  'cashAmountInvalid': '请输入不低于应收的现金金额，最多两位小数。|Enter cash received, at least the amount due, with up to two decimals.|請輸入不低於應收的現金金額，最多兩位小數。|กรอกเงินสดที่รับไม่น้อยกว่ายอดชำระ ทศนิยมไม่เกินสองตำแหน่ง',
  'cashReceivedNotice': '仅在现金确已收到后确认。实收金额会持久保存，超时后不能改成未收款终止。|Confirm only after physically receiving cash. The amount is saved and cannot be changed to uncollected after a timeout.|僅在現金確已收到後確認。實收金額會持久儲存，逾時後不能改成未收款終止。|ยืนยันเมื่อได้รับเงินสดจริงเท่านั้น ยอดจะถูกบันทึก หากหมดเวลาจะเปลี่ยนเป็นยังไม่ได้รับเงินไม่ได้',
  'cashCloseNotice': '仅在确认未收取现金时终止。此操作不是退款，也不取消订单；已收到或不确定时请勿继续。|Close only if no cash was collected. This is not a refund or order cancellation. Do not continue if cash was received or you are unsure.|僅在確認未收取現金時終止。此操作不是退款，也不取消訂單；已收到或不確定時請勿繼續。|ยุติเฉพาะเมื่อยังไม่ได้รับเงินสด ไม่ใช่การคืนเงินหรือยกเลิกคำสั่งซื้อ หากรับเงินแล้วหรือไม่แน่ใจห้ามดำเนินการ',
  'cashRetryNotice': '仅重试原收款准备，不确认付款、不生成新请求号。|Retries the original preparation only; no payment confirmation or new request ID.|僅重試原收款準備，不確認付款、不產生新請求號。|ลองเตรียมคำขอเดิมเท่านั้น ไม่ยืนยันการชำระเงินหรือสร้างรหัสใหม่',
  'cashReceivedConfirm':
      '我确认现金已收妥|I have received the cash|我確認現金已收妥|ฉันได้รับเงินสดแล้ว',
  'cashNotReceivedConfirm':
      '我确认未收取现金|I have not collected cash|我確認未收取現金|ฉันยังไม่ได้รับเงินสด',
  'cashPaid': '服务器已确认该笔现金付款。|Server confirmed this cash payment.|伺服器已確認該筆現金付款。|เซิร์ฟเวอร์ยืนยันการชำระเงินสดนี้แล้ว',
  'cashClosed': '原现金意图已终止；不是退款或订单取消。|Original cash intent closed; not a refund or order cancellation.|原現金意圖已終止；不是退款或訂單取消。|รายการเงินสดเดิมยุติแล้ว ไม่ใช่การคืนเงินหรือยกเลิกคำสั่งซื้อ',
  'cashUnknown': '原请求尚待查回，不代表取消或付款失败。|Original request needs lookup; this does not mean cancellation or failed payment.|原請求尚待查回，不代表取消或付款失敗。|ต้องตรวจสอบคำขอเดิม ไม่ได้หมายถึงยกเลิกหรือชำระเงินล้มเหลว',
  'cashNeedsLookup': '已有现金意图，请查回当前状态。|Cash intent exists. Look up its current state.|已有現金意圖，請查回目前狀態。|มีรายการเงินสดแล้ว โปรดตรวจสอบสถานะปัจจุบัน',
  'cashPrepared': '服务器返回待确认；请核对金额及现金。|Server reports prepared. Verify the amount and physical cash.|伺服器回傳待確認；請核對金額及現金。|เซิร์ฟเวอร์แจ้งว่าพร้อมยืนยัน โปรดตรวจยอดและเงินสด',
  'cashCannotConfirm': '当前不可确认收款。若现金已收到，请保留记录并联系负责人核实。|Cannot confirm now. If cash was received, keep this record and ask a manager to reconcile.|目前不可確認收款。若現金已收到，請保留記錄並聯絡負責人核實。|ยังยืนยันไม่ได้ หากได้รับเงินแล้วให้เก็บบันทึกนี้และติดต่อผู้จัดการตรวจสอบ',
  'cashUnconfirmed': '结果未确认，原请求已保留。请查回；勿重复收钱或改换请求。|Result unconfirmed. Original request retained. Look it up; do not collect again or replace the request.|結果未確認，原請求已保留。請查回；勿重複收錢或改換請求。|ยังไม่ยืนยันผล เก็บคำขอเดิมไว้แล้ว โปรดตรวจสอบ ห้ามเก็บเงินซ้ำหรือเปลี่ยนคำขอ',
  'cashLoadFailed': '无法读取现金记录；不能将其视为空。请检查安全存储或员工会话。|Cannot read cash records; this is not an empty list. Check secure storage or the employee session.|無法讀取現金記錄；不能將其視為空。請檢查安全儲存或員工會話。|อ่านบันทึกเงินสดไม่ได้ ไม่ได้หมายความว่าไม่มีรายการ โปรดตรวจที่เก็บปลอดภัยหรือเซสชันพนักงาน',
  'cashEmpty': '本设备当前员工没有待处理现金请求。|No pending cash requests for this employee on this device.|本裝置目前員工沒有待處理現金請求。|ไม่มีคำขอเงินสดค้างของพนักงานนี้บนอุปกรณ์นี้',
  'cashDecisionReceived': '本机已记录现金收妥，服务器结果待核实。|Cash receipt recorded locally; server result needs verification.|本機已記錄現金收妥，伺服器結果待核實。|บันทึกว่ารับเงินสดแล้วในเครื่อง ต้องตรวจสอบผลจากเซิร์ฟเวอร์',
  'cashDecisionClose': '本机已记录未收款终止决定，服务器结果待核实。|Uncollected-cash closure recorded locally; server result needs verification.|本機已記錄未收款終止決定，伺服器結果待核實。|บันทึกการยุติโดยไม่ได้รับเงินสดในเครื่อง ต้องตรวจสอบผลจากเซิร์ฟเวอร์',
  'cartTitle': '点单购物车|Order cart|點單購物車|ตะกร้าสั่งซื้อ',
  'cartNotice': '商品与库存为查询时快照，下单由服务器重新核对。|Catalog and stock are observations, rechecked by the server on submission.|商品與庫存為查詢時快照，下單由伺服器重新核對。|สินค้าและสต็อกเป็นข้อมูลขณะค้นหา เซิร์ฟเวอร์จะตรวจสอบอีกครั้งเมื่อสั่งซื้อ',
  'cartAdd': '加入／增加|Add|加入／增加|เพิ่ม',
  'cartRemove': '减少数量|Reduce quantity|減少數量|ลดจำนวน',
  'cartDelete': '移除商品|Remove item|移除商品|นำสินค้าออก',
  'cartDraftEmpty': '尚未选择商品|No items selected|尚未選擇商品|ยังไม่ได้เลือกสินค้า',
  'cartSubmit': '核对并下单|Review and place order|核對並下單|ตรวจสอบและสั่งซื้อ',
  'cartConfirmNotice': '确认后提交真实订单：先付模式预留库存，后付模式扣减库存。此操作不是收款，选择消费会员不代表余额扣款授权。|Confirmation submits a real order: prepay reserves stock; postpay issues stock. This is not payment, and selecting a consumer does not authorize wallet debit.|確認後提交真實訂單：先付模式預留庫存，後付模式扣減庫存。此操作不是收款，選擇消費會員不代表餘額扣款授權。|การยืนยันจะส่งคำสั่งซื้อจริง จ่ายก่อนจะจองสต็อก จ่ายทีหลังจะตัดสต็อก นี่ไม่ใช่การชำระเงิน การเลือกสมาชิกไม่อนุญาตให้หักยอดเงิน',
  'cartStale': '场次或会话已变化，请返回重新选择会员和商品。|Context changed. Return and select the member and items again.|場次或會話已變化，請返回重新選擇會員和商品。|บริบทเปลี่ยนแล้ว โปรดกลับไปเลือกสมาชิกและสินค้าใหม่',
  'cartPending': '本桌已有待确认原请求，请先查回，勿重复下单。|This table has an unresolved request. Look it up before placing another order.|本桌已有待確認原請求，請先查回，勿重複下單。|โต๊ะนี้มีคำขอที่ยังไม่ยืนยัน โปรดตรวจสอบก่อนสั่งซื้ออีกครั้ง',
  'cartLimit': '无法增加：库存不足、超出数量／金额限制或商品版本变化；请核对或移除后重新选择。|Cannot add: stock, quantity or amount limit, or changed product version. Review or remove and select again.|無法增加：庫存不足、超出數量／金額限制或商品版本變化；請核對或移除後重新選擇。|เพิ่มไม่ได้ สต็อกไม่พอ เกินจำนวนหรือยอดเงิน หรือสินค้าเปลี่ยนเวอร์ชัน โปรดตรวจสอบหรือลบแล้วเลือกใหม่',
  'orderRecoveryTitle':
      '待确认订单请求|Pending order requests|待確認訂單請求|คำขอสั่งซื้อที่รอยืนยัน',
  'orderRecoveryNotice': '仅处理当前员工在本设备保存的原请求。查回不重新下单；记录金额不是付款凭证。|Original requests saved for this employee on this device only. Lookup does not resubmit; the amount is not proof of payment.|僅處理目前員工在本裝置儲存的原請求。查回不重新下單；記錄金額不是付款憑證。|เฉพาะคำขอเดิมของพนักงานนี้ที่บันทึกในอุปกรณ์นี้ การตรวจสอบไม่ส่งคำสั่งซื้อซ้ำ ยอดเงินไม่ใช่หลักฐานการชำระเงิน',
  'orderRecoveryRetry': '查回并重试原订单|Look up and retry original order|查回並重試原訂單|ตรวจสอบและลองคำสั่งซื้อเดิมอีกครั้ง',
  'orderRecoveryCancel':
      '终止原下单请求|Terminate original request|終止原下單請求|ยุติคำขอสั่งซื้อเดิม',
  'orderRecoveryConfirm': '重试可能实际成单并预留或扣减库存，沿用原商品、数量与价格。终止仅阻止尚未成单的原请求，不退单、不退款。|Retry may create the order and reserve or issue stock using the original items, quantities and prices. Termination only blocks an unsubmitted request; it does not void or refund an order.|重試可能實際成單並預留或扣減庫存，沿用原商品、數量與價格。終止僅阻止尚未成單的原請求，不退單、不退款。|การลองใหม่อาจสร้างคำสั่งซื้อและจองหรือตัดสต็อกโดยใช้สินค้า จำนวน และราคาเดิม การยุติจะปิดกั้นเฉพาะคำขอที่ยังไม่เป็นคำสั่งซื้อ ไม่ยกเลิกคำสั่งซื้อหรือคืนเงิน',
  'orderRecoveryConfirmed': '原请求已成单，不代表已付款。请返回桌台查看订单。|Original order confirmed, not payment. Return to the table to view orders.|原請求已成單，不代表已付款。請返回桌檯查看訂單。|ยืนยันคำสั่งซื้อเดิมแล้ว ไม่ใช่การยืนยันชำระเงิน กลับไปดูคำสั่งซื้อที่โต๊ะ',
  'orderRecoveryCancelled': '原下单请求已终止，不代表退单或退款。|Original request terminated, not an order cancellation or refund.|原下單請求已終止，不代表退單或退款。|ยุติคำขอเดิมแล้ว ไม่ใช่การยกเลิกคำสั่งซื้อหรือคืนเงิน',
  'orderRecoveryUnknown': '仍未确认原请求结果，不要另建重复订单。|Original result is not confirmed. Do not create a duplicate order.|仍未確認原請求結果，不要另建重複訂單。|ยังไม่ยืนยันผลคำขอเดิม อย่าสร้างคำสั่งซื้อซ้ำ',
  'orderRecoveryUnconfirmed': '本次未能确认结果，原请求保留待查。|Result could not be confirmed. Keep the original request for lookup.|本次未能確認結果，原請求保留待查。|ยังยืนยันผลไม่ได้ เก็บคำขอเดิมไว้ตรวจสอบ',
  'orderRecoveryFailed': '无法读取待确认记录，请重试；不会清除记录。|Unable to read pending records. Retry; records will not be cleared.|無法讀取待確認記錄，請重試；不會清除記錄。|อ่านรายการที่รอยืนยันไม่ได้ โปรดลองใหม่ ระบบจะไม่ลบบันทึก',
  'orderRecoveryEmpty': '本设备当前员工暂无待确认订单请求。|No pending requests for this employee on this device.|本裝置目前員工暫無待確認訂單請求。|ไม่มีคำขอที่รอยืนยันของพนักงานนี้ในอุปกรณ์นี้',
  'orderMembersTitle': '入座会员|Seated members|入座會員|สมาชิกที่นั่งอยู่',
  'orderMembersNotice': '选择本场次消费会员后进入点单；不代表付款或余额扣款授权。|Select a consumer in this session to order. Selection is not payment or wallet debit consent.|選擇本場次消費會員後進入點單；不代表付款或餘額扣款授權。|เลือกสมาชิกผู้ใช้บริการในรอบนี้เพื่อสั่งซื้อ การเลือกไม่ใช่การอนุมัติชำระเงินหรือหักยอดเงิน',
  'orderMembersEmpty': '本页暂无入座会员；人数不等于会员入座记录。|No seated members on this page. Guest count is not a membership record.|本頁暫無入座會員；人數不等於會員入座記錄。|ไม่มีสมาชิกที่นั่งในหน้านี้ จำนวนคนไม่ใช่บันทึกสมาชิก',
  'orderMembersFailed': '无法确认当前场次或会员，请刷新或返回桌台。|Unable to confirm this session or its members. Refresh or return to tables.|無法確認目前場次或會員，請重新整理或返回桌檯。|ยืนยันรอบหรือสมาชิกไม่ได้ โปรดรีเฟรชหรือกลับไปหน้าโต๊ะ',
  'orderMemberUnnamed': '未设置昵称|Nickname not set|未設定暱稱|ยังไม่ได้ตั้งชื่อเล่น',
  'orderMemberIneligible': '当前不可选择|Currently unavailable|目前不可選擇|ยังเลือกไม่ได้',
  'orderMemberSelected': '当前选择（未下单）|Selected (no order placed)|目前選擇（未下單）|เลือกแล้ว (ยังไม่ได้สั่งซื้อ)',
  'catalogTitle': '商品目录|Product catalog|商品目錄|รายการสินค้า',
  'catalogNotice': '仅浏览实时目录，不锁价、不占用库存。员工下单尚未开放。|Catalog observation only; no price lock or stock reservation. Staff ordering is not enabled.|僅瀏覽即時目錄，不鎖價、不佔用庫存。員工下單尚未開放。|ดูรายการเท่านั้น ไม่ล็อกราคาหรือจองสต็อก ยังไม่เปิดให้พนักงานสั่งซื้อ',
  'catalogEmpty': '本页暂无商品|No products on this page|本頁暫無商品|ไม่มีสินค้าในหน้านี้',
  'catalogUnknown': '库存未知|Stock unknown|庫存未知|ไม่ทราบสต็อก',
  'catalogSoldOut': '暂无可售库存|No available stock|暫無可售庫存|ไม่มีสต็อกพร้อมขาย',
  'catalogAvailable': '当前可售数量|Available quantity|目前可售數量|จำนวนพร้อมขาย',
  'openingSubmit': '确认开台|Open table|確認開檯|ยืนยันเปิดโต๊ะ',
  'openingPending': '待确认开台请求|Pending openings|待確認開檯請求|คำขอเปิดโต๊ะที่รอยืนยัน',
  'openingRefresh': '刷新开台信息|Refresh opening info|重新整理開檯資訊|รีเฟรชข้อมูลเปิดโต๊ะ',
  'openingNotice': '开台由服务器确认，不代表付款成功。人数不自动绑定会员；AA 必须核对真实入座会员。|Opening is server-confirmed, not payment. Guest count does not link members; AA requires verified seated members.|開檯由伺服器確認，不代表付款成功。人數不自動綁定會員；AA 必須核對真實入座會員。|เซิร์ฟเวอร์ยืนยันการเปิดโต๊ะ ไม่ใช่การชำระเงิน จำนวนคนไม่เชื่อมสมาชิกอัตโนมัติ AA ต้องตรวจสอบสมาชิกที่นั่งจริง',
  'openingConfirmNotice': '请核对桌台与原请求。重试沿用原参数；终止不关闭已经开出的场次。|Check the table and original request. Retry keeps original details; termination does not close an existing session.|請核對桌檯與原請求。重試沿用原參數；終止不關閉已開出的場次。|ตรวจสอบโต๊ะและคำขอเดิม การลองใหม่ใช้ข้อมูลเดิม การยุติไม่ปิดรอบที่เปิดแล้ว',
  'openingConfirmed': '原请求已确认开台，请返回桌台查看当前场次。|Opening confirmed. Return to tables to check the current session.|原請求已確認開檯，請返回桌檯查看目前場次。|ยืนยันเปิดโต๊ะแล้ว กลับไปตรวจสอบรอบปัจจุบันที่หน้าโต๊ะ',
  'openingCancelled': '原请求已永久终止；准备新请求前请刷新开台信息。|Original request terminated. Refresh opening info before a new request.|原請求已永久終止；準備新請求前請重新整理開檯資訊。|ยุติคำขอเดิมแล้ว รีเฟรชข้อมูลก่อนสร้างคำขอใหม่',
  'openingUnknown': '尚未确认结果，不代表开台失败。请先查询原请求。|Result unconfirmed, not proof of failure. Query the original request first.|尚未確認結果，不代表開檯失敗。請先查詢原請求。|ยังไม่ยืนยันผล ไม่ได้หมายความว่าเปิดโต๊ะล้มเหลว โปรดตรวจสอบคำขอเดิมก่อน',
  'openingUnconfirmed': '本次操作未能确认结果。保留待确认记录，请查询原请求，勿重复新开台。|Result could not be confirmed. Keep pending records and query the original request; do not create another opening.|本次操作未能確認結果。保留待確認記錄，請查詢原請求，勿重複新開檯。|ยืนยันผลไม่ได้ เก็บคำขอที่รอไว้และตรวจสอบคำขอเดิม อย่าเปิดโต๊ะซ้ำ',
  'openingReadFailed': '读取未完成，请检查连接及员工权限后刷新。旧规则不可用于提交。|Read incomplete. Check connection and staff access, then refresh. Old rules cannot be submitted.|讀取未完成，請檢查連線及員工權限後重新整理。舊規則不可用於提交。|อ่านข้อมูลไม่ครบ ตรวจสอบเครือข่ายและสิทธิ์แล้วรีเฟรช ห้ามส่งด้วยกฎเก่า',
  'openingRule': '今日开台规则|Daily opening rule|今日開檯規則|กฎเปิดโต๊ะวันนี้',
  'openingRevision': '版本|Revision|版本|เวอร์ชัน',
  'openingRule_manual': '人工确认|Staff confirmation|人工確認|พนักงานยืนยัน',
  'openingRule_aa': 'AA 会员开台|AA member opening|AA 會員開檯|เปิดโต๊ะสมาชิก AA',
  'openingRule_minimum_people': '最低人数|Minimum guests|最低人數|จำนวนคนขั้นต่ำ',
  'openingRule_minimum_spend': '最低消费|Minimum spend|最低消費|ยอดใช้จ่ายขั้นต่ำ',
  'openingDefaultRule': '未配置专门规则，服务端使用默认人工规则。|No custom rule; server uses the manual default.|未設定專門規則，伺服器使用預設人工規則。|ยังไม่ตั้งกฎเฉพาะ เซิร์ฟเวอร์ใช้กฎพนักงานยืนยันเริ่มต้น',
  'openingMinimumPeople': '要求人数|Required guests|要求人數|จำนวนคนที่กำหนด',
  'openingMinimumSpend': '最低消费（门店货币）|Minimum spend (store currency)|最低消費（門店貨幣）|ยอดขั้นต่ำ (สกุลเงินร้าน)',
  'openingDisabled': '服务器暂未开放开台提交。|Server opening submissions are disabled.|伺服器暫未開放開檯提交。|เซิร์ฟเวอร์ยังไม่เปิดรับคำขอเปิดโต๊ะ',
  'openingOccupied': '已有营业场次，不能再次开台。|An active session already exists.|已有營業場次，不能再次開檯。|มีรอบใช้งานอยู่แล้ว เปิดซ้ำไม่ได้',
  'openingAaUnavailable': 'AA 入座会员选择尚未接入，请勿以空会员清单开台。|AA member selection is not connected. Do not open with an empty member list.|AA 入座會員選擇尚未接入，請勿以空會員清單開檯。|ยังไม่เชื่อมการเลือกสมาชิก AA ห้ามเปิดด้วยรายชื่อว่าง',
  'openingArrival': '我已确认客人到店及桌台归属|I verified arrival and the correct table|我已確認客人到店及桌檯歸屬|ตรวจสอบลูกค้ามาถึงและโต๊ะถูกต้องแล้ว',
  'openingReservation': '我已人工核对预约，无占用冲突（系统未自动核验）|I checked reservations and conflicts manually (not automatically verified)|我已人工核對預約，無佔用衝突（系統未自動核驗）|ตรวจสอบการจองและความขัดแย้งด้วยตนเองแล้ว (ระบบยังไม่ตรวจอัตโนมัติ)',
  'openingNoPending': '当前员工没有待确认开台请求。|No pending opening requests for this employee.|目前員工沒有待確認開檯請求。|พนักงานนี้ไม่มีคำขอเปิดโต๊ะที่รอยืนยัน',
  'openingRequest': '原请求号|Original request ID|原請求號|รหัสคำขอเดิม',
  'openingQuery': '查询原结果|Query original result|查詢原結果|ตรวจสอบผลเดิม',
  'openingRetry': '重试原请求|Retry original request|重試原請求|ลองคำขอเดิมอีกครั้ง',
  'openingCancel': '终止原请求|Terminate original request|終止原請求|ยุติคำขอเดิม',
  'ordersDetails': '消费明细|Order details|消費明細|รายละเอียดรายการ',
  'ordersBack': '返回桌台|Back to tables|返回桌檯|กลับไปที่โต๊ะ',
  'ordersRefresh': '刷新明细|Refresh orders|重新整理明細|รีเฟรชรายการ',
  'ordersEmpty':
      '本场次暂无订单|No orders in this session|本場次暫無訂單|ยังไม่มีรายการในรอบนี้',
  'ordersReadOnly': '只读成交明细 · 不代表最终结账金额；付款和核销尚未开放。|Read-only order details · Not a final bill. Payment and redemption are not available.|唯讀成交明細 · 不代表最終結帳金額；付款和核銷尚未開放。|รายละเอียดแบบอ่านอย่างเดียว ไม่ใช่ยอดบิลสุดท้าย ยังไม่เปิดชำระเงินหรือใช้คูปอง',
  'order_pending': '待付款|Pending payment|待付款|รอชำระเงิน',
  'order_paid': '已付款|Paid|已付款|ชำระแล้ว',
  'order_expired': '已失效|Expired|已失效|หมดอายุ',
  'liveRealtimeReadOnly': '只读桌台快照 · 收到门店变更提示后重新查询；通知不代表付款或核销成功。|Read-only snapshot · Store change hints trigger a new query, not payment or redemption confirmation.|唯讀桌檯快照 · 收到門店變更提示後重新查詢；通知不代表付款或核銷成功。|ข้อมูลโต๊ะแบบอ่านอย่างเดียว · แจ้งการเปลี่ยนแปลงแล้วจึงอ่านใหม่ ไม่ใช่การยืนยันชำระเงินหรือใช้คูปอง',
  'realtimeOffline': '实时通道未连接，可手动刷新|Realtime disconnected; manual refresh available|即時通道未連線，可手動重新整理|ช่องทางอัปเดตขาดการเชื่อมต่อ รีเฟรชด้วยตนเองได้',
  'realtimeConnecting': '正在连接门店实时通道…|Connecting to store updates…|正在連接門店即時通道…|กำลังเชื่อมต่อการอัปเดตร้าน…',
  'realtimeConnected': '门店实时通道已连接|Store update channel connected|門店即時通道已連線|เชื่อมต่อช่องทางอัปเดตร้านแล้ว',
  'tableDisabled': '停用桌台|Disabled table|停用桌檯|โต๊ะปิดใช้งาน',
  'tableOpen': '已开台|Open session|已開檯|เปิดโต๊ะแล้ว',
  'liveRefresh': '刷新桌台|Refresh tables|重新整理桌檯|รีเฟรชโต๊ะ',
  'liveReadOnly': '只读桌台快照 · 尚未接入实时推送，请手动刷新；未付款订单合计不等于最终结账金额。|Read-only snapshot · No live updates yet; refresh manually. Pending orders are not the final bill.|唯讀桌檯快照 · 尚未接入即時推送，請手動重新整理；未付款訂單合計不等於最終結帳金額。|ข้อมูลโต๊ะ ณ เวลาที่อ่าน · ยังไม่อัปเดตอัตโนมัติ โปรดรีเฟรช ยอดคำสั่งซื้อค้างชำระไม่ใช่ยอดบิลสุดท้าย',
  'liveObserved': '本页查询时间|Page observed at|本頁查詢時間|เวลาข้อมูลหน้านี้',
  'liveBusinessDate': '营业日|Business date|營業日|วันที่ดำเนินธุรกิจ',
  'liveReadFailed': '桌台读取失败，已清除旧显示。请检查连接或门店权限后刷新。|Unable to read tables; old display cleared. Check connection or store access and refresh.|桌檯讀取失敗，已清除舊顯示。請檢查連線或門店權限後重新整理。|อ่านโต๊ะไม่สำเร็จ ล้างข้อมูลเดิมแล้ว โปรดตรวจสอบการเชื่อมต่อหรือสิทธิ์ร้านและรีเฟรช',
  'liveNoTables': '服务器返回本页无桌台|No tables returned for this page|伺服器回傳本頁無桌檯|เซิร์ฟเวอร์ไม่ส่งโต๊ะในหน้านี้',
  'livePrevious': '上一页|Previous|上一頁|ก่อนหน้า',
  'liveNext': '下一页|Next|下一頁|ถัดไป',
  'livePage': '页码|Page|頁碼|หน้า',
  'livePrepay': '先付款|Pay first|先付款|ชำระก่อน',
  'livePostpay': '后付款|Pay later|後付款|ชำระภายหลัง',
  'livePaid': '已付订单合计|Paid order total|已付訂單合計|ยอดคำสั่งซื้อที่ชำระแล้ว',
  'livePending': '未付订单合计|Pending order total|未付訂單合計|ยอดคำสั่งซื้อค้างชำระ',
  'staffExitPreview': '退出后清空演示草稿，进入员工登录；如本机保存有员工会话，将向服务器验证恢复。|Discard preview drafts and open staff sign-in. A saved staff session will be verified with the server.|退出後清空示範草稿，進入員工登入；如本機儲存有員工工作階段，將向伺服器驗證恢復。|ล้างรายการร่างตัวอย่างและเปิดหน้าล็อกอิน หากมีเซสชันที่บันทึกไว้จะตรวจสอบกับเซิร์ฟเวอร์',
  'staffLogin': '独立员工登录|Staff sign-in|獨立員工登入|เข้าสู่ระบบพนักงาน',
  'staffStore': '门店编号|Store reference|門店編號|รหัสร้าน',
  'staffAccount': '员工账号|Employee account|員工帳號|บัญชีพนักงาน',
  'staffPassword': '员工密码|Employee password|員工密碼|รหัสผ่านพนักงาน',
  'staffSignIn': '登录门店|Sign in to store|登入門店|เข้าสู่ร้าน',
  'staffSignOut': '退出员工会话|Sign out|登出員工工作階段|ออกจากระบบ',
  'staffVerifying': '正在与服务器确认会话…|Verifying session with server…|正在與伺服器確認工作階段…|กำลังตรวจสอบเซสชันกับเซิร์ฟเวอร์…',
  'staffRequired': '请填写此项|This field is required|請填寫此項|กรุณากรอกข้อมูลนี้',
  'staffAuthFailure': '无法确认员工会话，请核对网络、账号及门店授权后重试。|Could not verify staff session. Check network, account and store access.|無法確認員工工作階段，請核對網路、帳號及門店授權後重試。|ยืนยันเซสชันไม่ได้ โปรดตรวจสอบเครือข่าย บัญชีและสิทธิ์ร้าน',
  'staffStorageFailure': '安全存储操作失败，请勿将此设备交给其他员工，先处理设备存储问题。|Secure storage failed. Resolve device storage before handing over this terminal.|安全儲存操作失敗，請勿將此設備交給其他員工，先處理設備儲存問題。|พื้นที่จัดเก็บปลอดภัยขัดข้อง โปรดแก้ไขก่อนส่งมอบเครื่องให้พนักงานอื่น',
  'staffLogoutUnconfirmed': '本机已退出，但服务器撤销尚未确认。请联系管理员核查会话。|Signed out locally; server revocation is unconfirmed. Ask an administrator to check the session.|本機已登出，但伺服器撤銷尚未確認。請聯絡管理員核查工作階段。|ออกจากเครื่องแล้ว แต่ยังไม่ยืนยันการยกเลิกบนเซิร์ฟเวอร์ โปรดแจ้งผู้ดูแล',
  'staffConnected': '员工会话已验证。真实桌台界面仍在接入中；此页不会开台、下单或收款。|Staff session verified. Live tables are still being connected; this page cannot open tables, place orders or take payments.|員工工作階段已驗證。真實桌檯介面仍在接入中；此頁不會開檯、下單或收款。|ยืนยันเซสชันแล้ว กำลังเชื่อมต่อหน้าโต๊ะจริง หน้านี้ไม่เปิดโต๊ะ สั่งซื้อหรือรับชำระเงิน',
  'workbench': '门店工作台|Store workspace|門店工作台|พื้นที่ทำงานร้าน',
  'tables': '桌台|Tables|桌檯|โต๊ะ',
  'ordering': '点单|Menu|點單|เมนู',
  'orders': '订单|Orders|訂單|คำสั่งซื้อ',
  'members': '会员|Members|會員|สมาชิก',
  'reports': '交班报表|Shift reports|交班報表|รายงานกะ',
  'settings': '设置|Settings|設定|ตั้งค่า',
  'preview': '界面演示|UI preview|介面示範|ตัวอย่างหน้าจอ',
  'live': '待接入门店|Store not connected|待接入門店|ยังไม่เชื่อมต่อร้าน',
  'sampleStore': '演示空间 · 非真实门店|Sample space · fictional store|示範空間 · 非真實門店|ร้านตัวอย่าง · ไม่ใช่ร้านจริง',
  'banner': '演示模式 · 桌台、商品、订单均为虚构样例，不会下单或收款|PREVIEW · Fictional data. No orders or payments are submitted.|示範模式 · 桌檯、商品、訂單均為虛構樣例，不會下單或收款|ตัวอย่าง · ข้อมูลสมมติ ไม่มีการสั่งซื้อหรือรับชำระเงิน',
  'liveBanner': '尚未建立员工会话 · 不显示演示营业数据|No staff session · No sample trading data|尚未建立員工工作階段 · 不顯示示範營業資料|ยังไม่มีเซสชันพนักงาน · ไม่แสดงข้อมูลตัวอย่าง',
  'all': '全部|All|全部|ทั้งหมด',
  'hall': '大厅|Hall|大廳|โถง',
  'booth': '卡座|Booths|卡座|ที่นั่งส่วนตัว',
  'free': '空台|Available|空檯|ว่าง',
  'taking': '点单中|Ordering|點單中|กำลังสั่ง',
  'unpaid': '待结账|Unpaid|待結帳|รอชำระ',
  'cleaning': '待清台|To clear|待清檯|รอเก็บโต๊ะ',
  'searchTable': '搜索桌号|Search tables|搜尋桌號|ค้นหาโต๊ะ',
  'overview': '桌台总览|Table overview|桌檯總覽|ภาพรวมโต๊ะ',
  'selectTable': '请选择桌台|Select a table|請選擇桌檯|เลือกโต๊ะ',
  'selectHint': '查看当前状态，或创建本桌点单草稿|View status or prepare a local draft|查看目前狀態，或建立本檯點單草稿|ดูสถานะหรือเตรียมรายการร่าง',
  'guests': '人数|Guests|人數|จำนวนคน',
  'elapsed': '已用分钟|Minutes|已用分鐘|นาที',
  'currentBill': '场次待付（样例）|Session due (sample)|場次待付（樣例）|ยอดค้าง (ตัวอย่าง)',
  'draft': '本桌草稿|Table draft|本檯草稿|รายการร่างของโต๊ะ',
  'localOnly': '仅存本次运行内存，退出应用不保留|Memory only; lost when the app closes|僅存本次執行記憶體，退出應用不保留|เก็บในหน่วยความจำ ปิดแอปแล้วข้อมูลหาย',
  'startDraft': '进入点单|Open menu|進入點單|เปิดเมนู',
  'tableActions': '开台 / 清台|Open / clear table|開檯 / 清檯|เปิด / เก็บโต๊ะ',
  'notConnected': '接口尚未接入|Not connected yet|介面尚未接入|ยังไม่เชื่อมต่อ',
  'blocked': '员工授权与经营接口尚未接入，没有执行任何业务操作。|Staff authorization and trading APIs are not connected. No business action was performed.|員工授權與經營介面尚未接入，沒有執行任何業務操作。|ยังไม่เชื่อมต่อสิทธิ์พนักงานและ API ไม่มีการดำเนินการทางธุรกิจ',
  'emptyLive': '连接门店后查看实时桌台|Connect your store to see tables|連接門店後查看即時桌檯|เชื่อมต่อร้านเพื่อดูโต๊ะ',
  'authHint': '需要收银员工授权；不会使用手机会员会话或自动授予权限。|A cashier staff session is required. Mobile sessions and permissions are not reused.|需要收銀員工授權；不會使用手機會員工作階段或自動授予權限。|ต้องมีสิทธิ์แคชเชียร์ ไม่ใช้เซสชันสมาชิกในมือถือ',
  'enterPreview': '体验界面演示|Try UI preview|體驗介面示範|ลองหน้าจอตัวอย่าง',
  'leavePreview': '退出演示|Exit preview|退出示範|ออกจากตัวอย่าง',
  'previewConfirm': '载入虚构样例，仅用于界面体验。切换模式会清空本地草稿，不会连接经营接口。|Load fictional UI samples. Switching modes clears drafts. No trading APIs will be called.|載入虛構樣例，僅用於介面體驗。切換模式會清空本地草稿，不會連接經營介面。|โหลดข้อมูลสมมติ การสลับโหมดจะล้างรายการร่าง ไม่เรียก API ธุรกิจ',
  'cancel': '取消|Cancel|取消|ยกเลิก',
  'confirm': '确认|Confirm|確認|ยืนยัน',
  'back': '返回桌台|Back to tables|返回桌檯|กลับไปโต๊ะ',
  'searchProduct': '搜索商品名称|Search products|搜尋商品名稱|ค้นหาสินค้า',
  'beer': '啤酒|Beer|啤酒|เบียร์',
  'spirits': '烈酒|Spirits|烈酒|สุรา',
  'soft': '软饮|Soft drinks|軟飲|เครื่องดื่ม',
  'snacks': '小食|Snacks|小食|อาหารว่าง',
  'sets': '套餐|Sets|套餐|ชุด',
  'lager': '清爽拉格（样例）|Lager (sample)|清爽拉格（樣例）|ลาเกอร์ (ตัวอย่าง)',
  'wheat': '小麦白啤（样例）|Wheat beer (sample)|小麥白啤（樣例）|วีทเบียร์ (ตัวอย่าง)',
  'ipa': '精酿 IPA（样例）|Craft IPA (sample)|精釀 IPA（樣例）|คราฟต์ IPA (ตัวอย่าง)',
  'whisky': '橡木威士忌（样例）|Whisky (sample)|橡木威士忌（樣例）|วิสกี้ (ตัวอย่าง)',
  'gin': '花香金酒（样例）|Gin (sample)|花香琴酒（樣例）|จิน (ตัวอย่าง)',
  'soda': '气泡水（样例）|Soda (sample)|氣泡水（樣例）|โซดา (ตัวอย่าง)',
  'juice': '鲜橙汁（样例）|Orange juice (sample)|鮮橙汁（樣例）|น้ำส้ม (ตัวอย่าง)',
  'water': '矿泉水（样例）|Water (sample)|礦泉水（樣例）|น้ำแร่ (ตัวอย่าง)',
  'fries': '香脆薯条（样例）|Fries (sample)|香脆薯條（樣例）|เฟรนช์ฟรายส์ (ตัวอย่าง)',
  'nuts': '混合坚果（样例）|Mixed nuts (sample)|混合堅果（樣例）|ถั่วรวม (ตัวอย่าง)',
  'fruit': '时令果盘（样例）|Fruit plate (sample)|時令果盤（樣例）|ผลไม้รวม (ตัวอย่าง)',
  'sharing': '轻聚分享套餐（样例）|Sharing set (sample)|輕聚分享套餐（樣例）|ชุดแบ่งปัน (ตัวอย่าง)',
  'bottle': '单瓶|Bottle|單瓶|ขวด',
  'six': '六瓶装|6 bottles|六瓶裝|6 ขวด',
  'glass': '单杯|Glass|單杯|แก้ว',
  'plate': '一份|Plate|一份|จาน',
  'set': '一套|Set|一套|ชุด',
  'soldOut': '已售罄|Sold out|已售罄|หมด',
  'variants': '选择规格|Choose an option|選擇規格|เลือกขนาด',
  'add': '加入草稿|Add to draft|加入草稿|เพิ่มในรายการร่าง',
  'cartEmpty': '从右侧选择商品|Choose items on the right|從右側選擇商品|เลือกสินค้าด้านขวา',
  'clear': '清空草稿|Clear draft|清空草稿|ล้างรายการร่าง',
  'clearConfirm': '清空本桌未提交的商品和备注？不会修改服务端订单。|Clear this draft and note? Server orders will not change.|清空本檯未提交的商品和備註？不會修改伺服器訂單。|ล้างรายการร่างและหมายเหตุ? ไม่เปลี่ยนคำสั่งซื้อจริง',
  'note': '订单备注|Draft note|訂單備註|หมายเหตุ',
  'total': '草稿合计|Draft total|草稿合計|รวมรายการร่าง',
  'items': '件|items|件|รายการ',
  'checkout': '核对结账|Review checkout|核對結帳|ตรวจสอบยอด',
  'checkoutHint': '草稿估算，不是服务端应收账单。优惠、库存及应付金额需后台确认。|Draft estimate, not a server bill. Discounts, stock and amounts require server confirmation.|草稿估算，不是伺服器應收帳單。優惠、庫存及應付金額需後台確認。|ยอดประมาณการ ไม่ใช่ใบเรียกเก็บจริง ต้องยืนยันจากเซิร์ฟเวอร์',
  'paymentDisabled': '未接入收款 · 不可支付|Payment not connected|未接入收款 · 不可支付|ยังไม่เชื่อมต่อการชำระเงิน',
  'paid': '已结账|Paid|已結帳|ชำระแล้ว',
  'sampleOrders': '样例订单 · 非实时营业记录|Sample orders · not live records|樣例訂單 · 非即時營業記錄|คำสั่งซื้อตัวอย่าง · ไม่ใช่ข้อมูลจริง',
  'orderDetails': '订单详情|Order details|訂單詳情|รายละเอียดคำสั่งซื้อ',
  'orderId': '订单编号|Order ID|訂單編號|รหัสคำสั่งซื้อ',
  'amount': '订单金额|Order amount|訂單金額|ยอดคำสั่งซื้อ',
  'source': '订单来源|Source|訂單來源|ที่มา',
  'sampleSource': '内置演示样例|Built-in preview fixture|內建示範樣例|ข้อมูลตัวอย่างในแอป',
  'print': '打印小票|Print receipt|列印收據|พิมพ์ใบเสร็จ',
  'noResults': '没有匹配内容|No matches|沒有符合內容|ไม่พบข้อมูล',
  'pendingModule': '此模块等待真实接口接入|This module needs live APIs|此模組等待真實介面接入|โมดูลนี้รอเชื่อมต่อ API',
  'memberHint': '会员和资产需独立授权，不生成示例会员隐私。|Members and assets require authorization. No fictional personal records.|會員和資產需獨立授權，不產生示例會員隱私。|สมาชิกและสินทรัพย์ต้องมีสิทธิ์ ไม่สร้างข้อมูลส่วนบุคคล',
  'reportHint': '交班、现金、收款统计以后台账务为准，不显示虚构营业额。|Shift and payment reports need server accounting. No fictional revenue shown.|交班、現金、收款統計以後台帳務為準，不顯示虛構營業額。|รายงานกะและเงินต้องมาจากบัญชีเซิร์ฟเวอร์ ไม่แสดงรายได้สมมติ',
  'connection': '服务连接|Service connection|服務連接|การเชื่อมต่อ',
  'connectionHint': '检查统一服务的 /ready；健康不代表已登录或有门店权限。|Check /ready. Readiness is not login or store authorization.|檢查統一服務的 /ready；健康不代表已登入或有門店權限。|ตรวจสอบ /ready ไม่ได้หมายถึงเข้าสู่ระบบหรือมีสิทธิ์ร้าน',
  'endpoint': '服务地址（HTTPS）|Service URL (HTTPS)|服務位址（HTTPS）|URL บริการ (HTTPS)',
  'check': '检查连接|Check connection|檢查連接|ตรวจสอบการเชื่อมต่อ',
  'checking': '正在检查…|Checking…|正在檢查…|กำลังตรวจสอบ…',
  'ready': '服务就绪 · 尚未登录|Service ready · not signed in|服務就緒 · 尚未登入|บริการพร้อม · ยังไม่เข้าสู่ระบบ',
  'failed': '检查未通过，请核对网络及服务地址|Check failed. Verify network and URL.|檢查未通過，請核對網路及服務位址|ตรวจสอบไม่สำเร็จ โปรดตรวจเครือข่ายและ URL',
  'invalidUrl': '请输入无账号、参数或片段的 HTTPS 地址|Enter HTTPS URL without credentials, query or fragment|請輸入無帳號、參數或片段的 HTTPS 位址|กรอก HTTPS URL ที่ไม่มีบัญชี พารามิเตอร์หรือ fragment',
  'previewNetwork': '演示不访问网络，请先退出演示|Exit preview to check a service|示範不存取網路，請先退出示範|ออกจากตัวอย่างก่อนตรวจสอบบริการ',
  'language': '界面语言|Language|介面語言|ภาษา',
  'device': '目标设备|Target device|目標裝置|อุปกรณ์เป้าหมาย',
  'landscape':
      '请横屏使用收银工作台|Use the cashier in landscape|請橫向使用收銀工作台|โปรดใช้ในแนวนอน',
  'save': '保存草稿备注|Save draft note|儲存草稿備註|บันทึกหมายเหตุร่าง',
};
