enum UiLanguage { zh, en, tw, th }

String tr(UiLanguage language, String key) {
  assert(copy.containsKey(key), 'Missing translation: $key');
  return copy[key]?.split('|')[language.index] ?? key;
}

const copy = <String, String>{
  'ordersDetails': '消费明细|Order details|消費明細|รายละเอียดรายการ',
  'ordersBack': '返回桌台|Back to tables|返回桌檯|กลับไปที่โต๊ะ',
  'ordersRefresh': '刷新明细|Refresh orders|重新整理明細|รีเฟรชรายการ',
  'ordersEmpty':
      '本场次暂无订单|No orders in this session|本場次暫無訂單|ยังไม่มีรายการในรอบนี้',
  'ordersReadOnly': '只读成交明细 · 不代表最终结账金额；付款和核销尚未开放。|Read-only order details · Not a final bill. Payment and redemption are not available.|唯讀成交明細 · 不代表最終結帳金額；付款和核銷尚未開放。|รายละเอียดแบบอ่านอย่างเดียว ไม่ใช่ยอดบิลสุดท้าย ยังไม่เปิดชำระเงินหรือใช้คูปอง',
  'order_pending': '待付款|Pending payment|待付款|รอชำระเงิน',
  'order_paid': '已付款|Paid|已付款|ชำระแล้ว',
  'order_expired': '已失效|Expired|已失效|หมดอายุ',
  'liveRealtimeReadOnly': '只读桌台快照 · 收到门店变更提示后重新查询；通知不代表付款或核销成功。|Read-only snapshot · Store change hints trigger a new query, not payment or redemption confirmation.|唯讀桌檯快照 · 收到門店變更提示後重新查詢；通知不代表付款或核銷成功。|ข้อมูลโต๊ะแบบอ่านอย่างเดียว · แจ้งการเปลี่ยนแปลงแล้วจึงอ่านใหม่ ไม่ใช่การยืนยันชำระเงินหรือใช้คูปอง',
  'realtimeOffline': '实时通道未连接，可手动刷新|Realtime disconnected; manual refresh available|即時通道未連線，可手動重新整理|ช่องทางอัปเดตขาดการเชื่อมต่อ รีเฟรชด้วยตนเองได้',
  'realtimeConnecting': '正在连接门店实时通道…|Connecting to store updates…|正在連接門店即時通道…|กำลังเชื่อมต่อการอัปเดตร้าน…',
  'realtimeConnected': '门店实时通道已连接|Store update channel connected|門店即時通道已連線|เชื่อมต่อช่องทางอัปเดตร้านแล้ว',
  'tableDisabled': '停用桌台|Disabled table|停用桌檯|โต๊ะปิดใช้งาน',
  'tableOpen': '已开台|Open session|已開檯|เปิดโต๊ะแล้ว',
  'liveRefresh': '刷新桌台|Refresh tables|重新整理桌檯|รีเฟรชโต๊ะ',
  'liveReadOnly': '只读桌台快照 · 尚未接入实时推送，请手动刷新；未付款订单合计不等于最终结账金额。|Read-only snapshot · No live updates yet; refresh manually. Pending orders are not the final bill.|唯讀桌檯快照 · 尚未接入即時推送，請手動重新整理；未付款訂單合計不等於最終結帳金額。|ข้อมูลโต๊ะ ณ เวลาที่อ่าน · ยังไม่อัปเดตอัตโนมัติ โปรดรีเฟรช ยอดคำสั่งซื้อค้างชำระไม่ใช่ยอดบิลสุดท้าย',
  'liveObserved': '本页查询时间|Page observed at|本頁查詢時間|เวลาข้อมูลหน้านี้',
  'liveBusinessDate': '营业日|Business date|營業日|วันที่ดำเนินธุรกิจ',
  'liveReadFailed': '桌台读取失败，已清除旧显示。请检查连接或门店权限后刷新。|Unable to read tables; old display cleared. Check connection or store access and refresh.|桌檯讀取失敗，已清除舊顯示。請檢查連線或門店權限後重新整理。|อ่านโต๊ะไม่สำเร็จ ล้างข้อมูลเดิมแล้ว โปรดตรวจสอบการเชื่อมต่อหรือสิทธิ์ร้านและรีเฟรช',
  'liveNoTables': '服务器返回本页无桌台|No tables returned for this page|伺服器回傳本頁無桌檯|เซิร์ฟเวอร์ไม่ส่งโต๊ะในหน้านี้',
  'livePrevious': '上一页|Previous|上一頁|ก่อนหน้า',
  'liveNext': '下一页|Next|下一頁|ถัดไป',
  'livePage': '页码|Page|頁碼|หน้า',
  'livePrepay': '先付款|Pay first|先付款|ชำระก่อน',
  'livePostpay': '后付款|Pay later|後付款|ชำระภายหลัง',
  'livePaid': '已付订单合计|Paid order total|已付訂單合計|ยอดคำสั่งซื้อที่ชำระแล้ว',
  'livePending': '未付订单合计|Pending order total|未付訂單合計|ยอดคำสั่งซื้อค้างชำระ',
  'staffExitPreview': '退出后清空演示草稿，进入员工登录；如本机保存有员工会话，将向服务器验证恢复。|Discard preview drafts and open staff sign-in. A saved staff session will be verified with the server.|退出後清空示範草稿，進入員工登入；如本機儲存有員工工作階段，將向伺服器驗證恢復。|ล้างรายการร่างตัวอย่างและเปิดหน้าล็อกอิน หากมีเซสชันที่บันทึกไว้จะตรวจสอบกับเซิร์ฟเวอร์',
  'staffLogin': '独立员工登录|Staff sign-in|獨立員工登入|เข้าสู่ระบบพนักงาน',
  'staffStore': '门店编号|Store reference|門店編號|รหัสร้าน',
  'staffAccount': '员工账号|Employee account|員工帳號|บัญชีพนักงาน',
  'staffPassword': '员工密码|Employee password|員工密碼|รหัสผ่านพนักงาน',
  'staffSignIn': '登录门店|Sign in to store|登入門店|เข้าสู่ร้าน',
  'staffSignOut': '退出员工会话|Sign out|登出員工工作階段|ออกจากระบบ',
  'staffVerifying': '正在与服务器确认会话…|Verifying session with server…|正在與伺服器確認工作階段…|กำลังตรวจสอบเซสชันกับเซิร์ฟเวอร์…',
  'staffRequired': '请填写此项|This field is required|請填寫此項|กรุณากรอกข้อมูลนี้',
  'staffAuthFailure': '无法确认员工会话，请核对网络、账号及门店授权后重试。|Could not verify staff session. Check network, account and store access.|無法確認員工工作階段，請核對網路、帳號及門店授權後重試。|ยืนยันเซสชันไม่ได้ โปรดตรวจสอบเครือข่าย บัญชีและสิทธิ์ร้าน',
  'staffStorageFailure': '安全存储操作失败，请勿将此设备交给其他员工，先处理设备存储问题。|Secure storage failed. Resolve device storage before handing over this terminal.|安全儲存操作失敗，請勿將此設備交給其他員工，先處理設備儲存問題。|พื้นที่จัดเก็บปลอดภัยขัดข้อง โปรดแก้ไขก่อนส่งมอบเครื่องให้พนักงานอื่น',
  'staffLogoutUnconfirmed': '本机已退出，但服务器撤销尚未确认。请联系管理员核查会话。|Signed out locally; server revocation is unconfirmed. Ask an administrator to check the session.|本機已登出，但伺服器撤銷尚未確認。請聯絡管理員核查工作階段。|ออกจากเครื่องแล้ว แต่ยังไม่ยืนยันการยกเลิกบนเซิร์ฟเวอร์ โปรดแจ้งผู้ดูแล',
  'staffConnected': '员工会话已验证。真实桌台界面仍在接入中；此页不会开台、下单或收款。|Staff session verified. Live tables are still being connected; this page cannot open tables, place orders or take payments.|員工工作階段已驗證。真實桌檯介面仍在接入中；此頁不會開檯、下單或收款。|ยืนยันเซสชันแล้ว กำลังเชื่อมต่อหน้าโต๊ะจริง หน้านี้ไม่เปิดโต๊ะ สั่งซื้อหรือรับชำระเงิน',
  'workbench': '门店工作台|Store workspace|門店工作台|พื้นที่ทำงานร้าน',
  'tables': '桌台|Tables|桌檯|โต๊ะ',
  'ordering': '点单|Menu|點單|เมนู',
  'orders': '订单|Orders|訂單|คำสั่งซื้อ',
  'members': '会员|Members|會員|สมาชิก',
  'reports': '交班报表|Shift reports|交班報表|รายงานกะ',
  'settings': '设置|Settings|設定|ตั้งค่า',
  'preview': '界面演示|UI preview|介面示範|ตัวอย่างหน้าจอ',
  'live': '待接入门店|Store not connected|待接入門店|ยังไม่เชื่อมต่อร้าน',
  'sampleStore': '演示空间 · 非真实门店|Sample space · fictional store|示範空間 · 非真實門店|ร้านตัวอย่าง · ไม่ใช่ร้านจริง',
  'banner': '演示模式 · 桌台、商品、订单均为虚构样例，不会下单或收款|PREVIEW · Fictional data. No orders or payments are submitted.|示範模式 · 桌檯、商品、訂單均為虛構樣例，不會下單或收款|ตัวอย่าง · ข้อมูลสมมติ ไม่มีการสั่งซื้อหรือรับชำระเงิน',
  'liveBanner': '尚未建立员工会话 · 不显示演示营业数据|No staff session · No sample trading data|尚未建立員工工作階段 · 不顯示示範營業資料|ยังไม่มีเซสชันพนักงาน · ไม่แสดงข้อมูลตัวอย่าง',
  'all': '全部|All|全部|ทั้งหมด',
  'hall': '大厅|Hall|大廳|โถง',
  'booth': '卡座|Booths|卡座|ที่นั่งส่วนตัว',
  'free': '空台|Available|空檯|ว่าง',
  'taking': '点单中|Ordering|點單中|กำลังสั่ง',
  'unpaid': '待结账|Unpaid|待結帳|รอชำระ',
  'cleaning': '待清台|To clear|待清檯|รอเก็บโต๊ะ',
  'searchTable': '搜索桌号|Search tables|搜尋桌號|ค้นหาโต๊ะ',
  'overview': '桌台总览|Table overview|桌檯總覽|ภาพรวมโต๊ะ',
  'selectTable': '请选择桌台|Select a table|請選擇桌檯|เลือกโต๊ะ',
  'selectHint': '查看当前状态，或创建本桌点单草稿|View status or prepare a local draft|查看目前狀態，或建立本檯點單草稿|ดูสถานะหรือเตรียมรายการร่าง',
  'guests': '人数|Guests|人數|จำนวนคน',
  'elapsed': '已用分钟|Minutes|已用分鐘|นาที',
  'currentBill': '场次待付（样例）|Session due (sample)|場次待付（樣例）|ยอดค้าง (ตัวอย่าง)',
  'draft': '本桌草稿|Table draft|本檯草稿|รายการร่างของโต๊ะ',
  'localOnly': '仅存本次运行内存，退出应用不保留|Memory only; lost when the app closes|僅存本次執行記憶體，退出應用不保留|เก็บในหน่วยความจำ ปิดแอปแล้วข้อมูลหาย',
  'startDraft': '进入点单|Open menu|進入點單|เปิดเมนู',
  'tableActions': '开台 / 清台|Open / clear table|開檯 / 清檯|เปิด / เก็บโต๊ะ',
  'notConnected': '接口尚未接入|Not connected yet|介面尚未接入|ยังไม่เชื่อมต่อ',
  'blocked': '员工授权与经营接口尚未接入，没有执行任何业务操作。|Staff authorization and trading APIs are not connected. No business action was performed.|員工授權與經營介面尚未接入，沒有執行任何業務操作。|ยังไม่เชื่อมต่อสิทธิ์พนักงานและ API ไม่มีการดำเนินการทางธุรกิจ',
  'emptyLive': '连接门店后查看实时桌台|Connect your store to see tables|連接門店後查看即時桌檯|เชื่อมต่อร้านเพื่อดูโต๊ะ',
  'authHint': '需要收银员工授权；不会使用手机会员会话或自动授予权限。|A cashier staff session is required. Mobile sessions and permissions are not reused.|需要收銀員工授權；不會使用手機會員工作階段或自動授予權限。|ต้องมีสิทธิ์แคชเชียร์ ไม่ใช้เซสชันสมาชิกในมือถือ',
  'enterPreview': '体验界面演示|Try UI preview|體驗介面示範|ลองหน้าจอตัวอย่าง',
  'leavePreview': '退出演示|Exit preview|退出示範|ออกจากตัวอย่าง',
  'previewConfirm': '载入虚构样例，仅用于界面体验。切换模式会清空本地草稿，不会连接经营接口。|Load fictional UI samples. Switching modes clears drafts. No trading APIs will be called.|載入虛構樣例，僅用於介面體驗。切換模式會清空本地草稿，不會連接經營介面。|โหลดข้อมูลสมมติ การสลับโหมดจะล้างรายการร่าง ไม่เรียก API ธุรกิจ',
  'cancel': '取消|Cancel|取消|ยกเลิก',
  'confirm': '确认|Confirm|確認|ยืนยัน',
  'back': '返回桌台|Back to tables|返回桌檯|กลับไปโต๊ะ',
  'searchProduct': '搜索商品名称|Search products|搜尋商品名稱|ค้นหาสินค้า',
  'beer': '啤酒|Beer|啤酒|เบียร์',
  'spirits': '烈酒|Spirits|烈酒|สุรา',
  'soft': '软饮|Soft drinks|軟飲|เครื่องดื่ม',
  'snacks': '小食|Snacks|小食|อาหารว่าง',
  'sets': '套餐|Sets|套餐|ชุด',
  'lager': '清爽拉格（样例）|Lager (sample)|清爽拉格（樣例）|ลาเกอร์ (ตัวอย่าง)',
  'wheat': '小麦白啤（样例）|Wheat beer (sample)|小麥白啤（樣例）|วีทเบียร์ (ตัวอย่าง)',
  'ipa': '精酿 IPA（样例）|Craft IPA (sample)|精釀 IPA（樣例）|คราฟต์ IPA (ตัวอย่าง)',
  'whisky': '橡木威士忌（样例）|Whisky (sample)|橡木威士忌（樣例）|วิสกี้ (ตัวอย่าง)',
  'gin': '花香金酒（样例）|Gin (sample)|花香琴酒（樣例）|จิน (ตัวอย่าง)',
  'soda': '气泡水（样例）|Soda (sample)|氣泡水（樣例）|โซดา (ตัวอย่าง)',
  'juice': '鲜橙汁（样例）|Orange juice (sample)|鮮橙汁（樣例）|น้ำส้ม (ตัวอย่าง)',
  'water': '矿泉水（样例）|Water (sample)|礦泉水（樣例）|น้ำแร่ (ตัวอย่าง)',
  'fries': '香脆薯条（样例）|Fries (sample)|香脆薯條（樣例）|เฟรนช์ฟรายส์ (ตัวอย่าง)',
  'nuts': '混合坚果（样例）|Mixed nuts (sample)|混合堅果（樣例）|ถั่วรวม (ตัวอย่าง)',
  'fruit': '时令果盘（样例）|Fruit plate (sample)|時令果盤（樣例）|ผลไม้รวม (ตัวอย่าง)',
  'sharing': '轻聚分享套餐（样例）|Sharing set (sample)|輕聚分享套餐（樣例）|ชุดแบ่งปัน (ตัวอย่าง)',
  'bottle': '单瓶|Bottle|單瓶|ขวด',
  'six': '六瓶装|6 bottles|六瓶裝|6 ขวด',
  'glass': '单杯|Glass|單杯|แก้ว',
  'plate': '一份|Plate|一份|จาน',
  'set': '一套|Set|一套|ชุด',
  'soldOut': '已售罄|Sold out|已售罄|หมด',
  'variants': '选择规格|Choose an option|選擇規格|เลือกขนาด',
  'add': '加入草稿|Add to draft|加入草稿|เพิ่มในรายการร่าง',
  'cartEmpty': '从右侧选择商品|Choose items on the right|從右側選擇商品|เลือกสินค้าด้านขวา',
  'clear': '清空草稿|Clear draft|清空草稿|ล้างรายการร่าง',
  'clearConfirm': '清空本桌未提交的商品和备注？不会修改服务端订单。|Clear this draft and note? Server orders will not change.|清空本檯未提交的商品和備註？不會修改伺服器訂單。|ล้างรายการร่างและหมายเหตุ? ไม่เปลี่ยนคำสั่งซื้อจริง',
  'note': '订单备注|Draft note|訂單備註|หมายเหตุ',
  'total': '草稿合计|Draft total|草稿合計|รวมรายการร่าง',
  'items': '件|items|件|รายการ',
  'checkout': '核对结账|Review checkout|核對結帳|ตรวจสอบยอด',
  'checkoutHint': '草稿估算，不是服务端应收账单。优惠、库存及应付金额需后台确认。|Draft estimate, not a server bill. Discounts, stock and amounts require server confirmation.|草稿估算，不是伺服器應收帳單。優惠、庫存及應付金額需後台確認。|ยอดประมาณการ ไม่ใช่ใบเรียกเก็บจริง ต้องยืนยันจากเซิร์ฟเวอร์',
  'paymentDisabled': '未接入收款 · 不可支付|Payment not connected|未接入收款 · 不可支付|ยังไม่เชื่อมต่อการชำระเงิน',
  'paid': '已结账|Paid|已結帳|ชำระแล้ว',
  'sampleOrders': '样例订单 · 非实时营业记录|Sample orders · not live records|樣例訂單 · 非即時營業記錄|คำสั่งซื้อตัวอย่าง · ไม่ใช่ข้อมูลจริง',
  'orderDetails': '订单详情|Order details|訂單詳情|รายละเอียดคำสั่งซื้อ',
  'orderId': '订单编号|Order ID|訂單編號|รหัสคำสั่งซื้อ',
  'amount': '订单金额|Order amount|訂單金額|ยอดคำสั่งซื้อ',
  'source': '订单来源|Source|訂單來源|ที่มา',
  'sampleSource': '内置演示样例|Built-in preview fixture|內建示範樣例|ข้อมูลตัวอย่างในแอป',
  'print': '打印小票|Print receipt|列印收據|พิมพ์ใบเสร็จ',
  'noResults': '没有匹配内容|No matches|沒有符合內容|ไม่พบข้อมูล',
  'pendingModule': '此模块等待真实接口接入|This module needs live APIs|此模組等待真實介面接入|โมดูลนี้รอเชื่อมต่อ API',
  'memberHint': '会员和资产需独立授权，不生成示例会员隐私。|Members and assets require authorization. No fictional personal records.|會員和資產需獨立授權，不產生示例會員隱私。|สมาชิกและสินทรัพย์ต้องมีสิทธิ์ ไม่สร้างข้อมูลส่วนบุคคล',
  'reportHint': '交班、现金、收款统计以后台账务为准，不显示虚构营业额。|Shift and payment reports need server accounting. No fictional revenue shown.|交班、現金、收款統計以後台帳務為準，不顯示虛構營業額。|รายงานกะและเงินต้องมาจากบัญชีเซิร์ฟเวอร์ ไม่แสดงรายได้สมมติ',
  'connection': '服务连接|Service connection|服務連接|การเชื่อมต่อ',
  'connectionHint': '检查统一服务的 /ready；健康不代表已登录或有门店权限。|Check /ready. Readiness is not login or store authorization.|檢查統一服務的 /ready；健康不代表已登入或有門店權限。|ตรวจสอบ /ready ไม่ได้หมายถึงเข้าสู่ระบบหรือมีสิทธิ์ร้าน',
  'endpoint': '服务地址（HTTPS）|Service URL (HTTPS)|服務位址（HTTPS）|URL บริการ (HTTPS)',
  'check': '检查连接|Check connection|檢查連接|ตรวจสอบการเชื่อมต่อ',
  'checking': '正在检查…|Checking…|正在檢查…|กำลังตรวจสอบ…',
  'ready': '服务就绪 · 尚未登录|Service ready · not signed in|服務就緒 · 尚未登入|บริการพร้อม · ยังไม่เข้าสู่ระบบ',
  'failed': '检查未通过，请核对网络及服务地址|Check failed. Verify network and URL.|檢查未通過，請核對網路及服務位址|ตรวจสอบไม่สำเร็จ โปรดตรวจเครือข่ายและ URL',
  'invalidUrl': '请输入无账号、参数或片段的 HTTPS 地址|Enter HTTPS URL without credentials, query or fragment|請輸入無帳號、參數或片段的 HTTPS 位址|กรอก HTTPS URL ที่ไม่มีบัญชี พารามิเตอร์หรือ fragment',
  'previewNetwork': '演示不访问网络，请先退出演示|Exit preview to check a service|示範不存取網路，請先退出示範|ออกจากตัวอย่างก่อนตรวจสอบบริการ',
  'language': '界面语言|Language|介面語言|ภาษา',
  'device': '目标设备|Target device|目標裝置|อุปกรณ์เป้าหมาย',
  'landscape':
      '请横屏使用收银工作台|Use the cashier in landscape|請橫向使用收銀工作台|โปรดใช้ในแนวนอน',
  'save': '保存草稿备注|Save draft note|儲存草稿備註|บันทึกหมายเหตุร่าง',
};
